// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/rosneft/backend/services/passkey-service/internal/service/passkey.Store -o store_mock.go -n StoreMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/rosneft/backend/services/passkey-service/internal/domain"
)

// StoreMock implements mm_passkey.Store
type StoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, c domain.Credential) (err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, c domain.Credential)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mStoreMockCreate

	funcDeleteByCredentialID          func(ctx context.Context, userID string, credID []byte) (err error)
	funcDeleteByCredentialIDOrigin    string
	inspectFuncDeleteByCredentialID   func(ctx context.Context, userID string, credID []byte)
	afterDeleteByCredentialIDCounter  uint64
	beforeDeleteByCredentialIDCounter uint64
	DeleteByCredentialIDMock          mStoreMockDeleteByCredentialID

	funcListByUser          func(ctx context.Context, userID string) (ca1 []domain.Credential, err error)
	funcListByUserOrigin    string
	inspectFuncListByUser   func(ctx context.Context, userID string)
	afterListByUserCounter  uint64
	beforeListByUserCounter uint64
	ListByUserMock          mStoreMockListByUser

	funcUpdateSignCount          func(ctx context.Context, credID []byte, count uint32) (err error)
	funcUpdateSignCountOrigin    string
	inspectFuncUpdateSignCount   func(ctx context.Context, credID []byte, count uint32)
	afterUpdateSignCountCounter  uint64
	beforeUpdateSignCountCounter uint64
	UpdateSignCountMock          mStoreMockUpdateSignCount
}

// NewStoreMock returns a mock for mm_passkey.Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mStoreMockCreate{mock: m}
	m.CreateMock.callArgs = []*StoreMockCreateParams{}

	m.DeleteByCredentialIDMock = mStoreMockDeleteByCredentialID{mock: m}
	m.DeleteByCredentialIDMock.callArgs = []*StoreMockDeleteByCredentialIDParams{}

	m.ListByUserMock = mStoreMockListByUser{mock: m}
	m.ListByUserMock.callArgs = []*StoreMockListByUserParams{}

	m.UpdateSignCountMock = mStoreMockUpdateSignCount{mock: m}
	m.UpdateSignCountMock.callArgs = []*StoreMockUpdateSignCountParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreMockCreate struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockCreateExpectation
	expectations       []*StoreMockCreateExpectation

	callArgs []*StoreMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockCreateExpectation specifies expectation struct of the Store.Create
type StoreMockCreateExpectation struct {
	mock               *StoreMock
	params             *StoreMockCreateParams
	paramPtrs          *StoreMockCreateParamPtrs
	expectationOrigins StoreMockCreateExpectationOrigins
	results            *StoreMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockCreateParams contains parameters of the Store.Create
type StoreMockCreateParams struct {
	ctx context.Context
	c   domain.Credential
}

// StoreMockCreateParamPtrs contains pointers to parameters of the Store.Create
type StoreMockCreateParamPtrs struct {
	ctx *context.Context
	c   *domain.Credential
}

// StoreMockCreateResults contains results of the Store.Create
type StoreMockCreateResults struct {
	err error
}

// StoreMockCreateOrigins contains origins of expectations of the Store.Create
type StoreMockCreateExpectationOrigins struct {
	origin    string
	originCtx string
	originC   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mStoreMockCreate) Optional() *mStoreMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for Store.Create
func (mmCreate *mStoreMockCreate) Expect(ctx context.Context, c domain.Credential) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &StoreMockCreateParams{ctx, c}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for Store.Create
func (mmCreate *mStoreMockCreate) ExpectCtxParam1(ctx context.Context) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectCParam2 sets up expected param c for Store.Create
func (mmCreate *mStoreMockCreate) ExpectCParam2(c domain.Credential) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.c = &c
	mmCreate.defaultExpectation.expectationOrigins.originC = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the Store.Create
func (mmCreate *mStoreMockCreate) Inspect(f func(ctx context.Context, c domain.Credential)) *mStoreMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for StoreMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by Store.Create
func (mmCreate *mStoreMockCreate) Return(err error) *StoreMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &StoreMockCreateResults{err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the Store.Create method
func (mmCreate *mStoreMockCreate) Set(f func(ctx context.Context, c domain.Credential) (err error)) *StoreMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the Store.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the Store.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the Store.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mStoreMockCreate) When(ctx context.Context, c domain.Credential) *StoreMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	expectation := &StoreMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &StoreMockCreateParams{ctx, c},
		expectationOrigins: StoreMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up Store.Create return parameters for the expectation previously defined by the When method
func (e *StoreMockCreateExpectation) Then(err error) *StoreMock {
	e.results = &StoreMockCreateResults{err}
	return e.mock
}

// Times sets number of times Store.Create should be invoked
func (mmCreate *mStoreMockCreate) Times(n uint64) *mStoreMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of StoreMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mStoreMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_passkey.Store
func (mmCreate *StoreMock) Create(ctx context.Context, c domain.Credential) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, c)
	}

	mm_params := StoreMockCreateParams{ctx, c}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := StoreMockCreateParams{ctx, c}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.c != nil && !minimock.Equal(*mm_want_ptrs.c, mm_got.c) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter c, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originC, *mm_want_ptrs.c, mm_got.c, minimock.Diff(*mm_want_ptrs.c, mm_got.c))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("StoreMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the StoreMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, c)
	}
	mmCreate.t.Fatalf("Unexpected call to StoreMock.Create. %v %v", ctx, c)
	return
}

// CreateAfterCounter returns a count of finished StoreMock.Create invocations
func (mmCreate *StoreMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of StoreMock.Create invocations
func (mmCreate *StoreMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mStoreMockCreate) Calls() []*StoreMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*StoreMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *StoreMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mStoreMockDeleteByCredentialID struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockDeleteByCredentialIDExpectation
	expectations       []*StoreMockDeleteByCredentialIDExpectation

	callArgs []*StoreMockDeleteByCredentialIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockDeleteByCredentialIDExpectation specifies expectation struct of the Store.DeleteByCredentialID
type StoreMockDeleteByCredentialIDExpectation struct {
	mock               *StoreMock
	params             *StoreMockDeleteByCredentialIDParams
	paramPtrs          *StoreMockDeleteByCredentialIDParamPtrs
	expectationOrigins StoreMockDeleteByCredentialIDExpectationOrigins
	results            *StoreMockDeleteByCredentialIDResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockDeleteByCredentialIDParams contains parameters of the Store.DeleteByCredentialID
type StoreMockDeleteByCredentialIDParams struct {
	ctx    context.Context
	userID string
	credID []byte
}

// StoreMockDeleteByCredentialIDParamPtrs contains pointers to parameters of the Store.DeleteByCredentialID
type StoreMockDeleteByCredentialIDParamPtrs struct {
	ctx    *context.Context
	userID *string
	credID *[]byte
}

// StoreMockDeleteByCredentialIDResults contains results of the Store.DeleteByCredentialID
type StoreMockDeleteByCredentialIDResults struct {
	err error
}

// StoreMockDeleteByCredentialIDOrigins contains origins of expectations of the Store.DeleteByCredentialID
type StoreMockDeleteByCredentialIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
	originCredID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Optional() *mStoreMockDeleteByCredentialID {
	mmDeleteByCredentialID.optional = true
	return mmDeleteByCredentialID
}

// Expect sets up expected params for Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Expect(ctx context.Context, userID string, credID []byte) *mStoreMockDeleteByCredentialID {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	if mmDeleteByCredentialID.defaultExpectation == nil {
		mmDeleteByCredentialID.defaultExpectation = &StoreMockDeleteByCredentialIDExpectation{}
	}

	if mmDeleteByCredentialID.defaultExpectation.paramPtrs != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by ExpectParams functions")
	}

	mmDeleteByCredentialID.defaultExpectation.params = &StoreMockDeleteByCredentialIDParams{ctx, userID, credID}
	mmDeleteByCredentialID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteByCredentialID.expectations {
		if minimock.Equal(e.params, mmDeleteByCredentialID.defaultExpectation.params) {
			mmDeleteByCredentialID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteByCredentialID.defaultExpectation.params)
		}
	}

	return mmDeleteByCredentialID
}

// ExpectCtxParam1 sets up expected param ctx for Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) ExpectCtxParam1(ctx context.Context) *mStoreMockDeleteByCredentialID {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	if mmDeleteByCredentialID.defaultExpectation == nil {
		mmDeleteByCredentialID.defaultExpectation = &StoreMockDeleteByCredentialIDExpectation{}
	}

	if mmDeleteByCredentialID.defaultExpectation.params != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Expect")
	}

	if mmDeleteByCredentialID.defaultExpectation.paramPtrs == nil {
		mmDeleteByCredentialID.defaultExpectation.paramPtrs = &StoreMockDeleteByCredentialIDParamPtrs{}
	}
	mmDeleteByCredentialID.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteByCredentialID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteByCredentialID
}

// ExpectUserIDParam2 sets up expected param userID for Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) ExpectUserIDParam2(userID string) *mStoreMockDeleteByCredentialID {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	if mmDeleteByCredentialID.defaultExpectation == nil {
		mmDeleteByCredentialID.defaultExpectation = &StoreMockDeleteByCredentialIDExpectation{}
	}

	if mmDeleteByCredentialID.defaultExpectation.params != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Expect")
	}

	if mmDeleteByCredentialID.defaultExpectation.paramPtrs == nil {
		mmDeleteByCredentialID.defaultExpectation.paramPtrs = &StoreMockDeleteByCredentialIDParamPtrs{}
	}
	mmDeleteByCredentialID.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteByCredentialID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteByCredentialID
}

// ExpectCredIDParam3 sets up expected param credID for Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) ExpectCredIDParam3(credID []byte) *mStoreMockDeleteByCredentialID {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	if mmDeleteByCredentialID.defaultExpectation == nil {
		mmDeleteByCredentialID.defaultExpectation = &StoreMockDeleteByCredentialIDExpectation{}
	}

	if mmDeleteByCredentialID.defaultExpectation.params != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Expect")
	}

	if mmDeleteByCredentialID.defaultExpectation.paramPtrs == nil {
		mmDeleteByCredentialID.defaultExpectation.paramPtrs = &StoreMockDeleteByCredentialIDParamPtrs{}
	}
	mmDeleteByCredentialID.defaultExpectation.paramPtrs.credID = &credID
	mmDeleteByCredentialID.defaultExpectation.expectationOrigins.originCredID = minimock.CallerInfo(1)

	return mmDeleteByCredentialID
}

// Inspect accepts an inspector function that has same arguments as the Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Inspect(f func(ctx context.Context, userID string, credID []byte)) *mStoreMockDeleteByCredentialID {
	if mmDeleteByCredentialID.mock.inspectFuncDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("Inspect function is already set for StoreMock.DeleteByCredentialID")
	}

	mmDeleteByCredentialID.mock.inspectFuncDeleteByCredentialID = f

	return mmDeleteByCredentialID
}

// Return sets up results that will be returned by Store.DeleteByCredentialID
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Return(err error) *StoreMock {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	if mmDeleteByCredentialID.defaultExpectation == nil {
		mmDeleteByCredentialID.defaultExpectation = &StoreMockDeleteByCredentialIDExpectation{mock: mmDeleteByCredentialID.mock}
	}
	mmDeleteByCredentialID.defaultExpectation.results = &StoreMockDeleteByCredentialIDResults{err}
	mmDeleteByCredentialID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteByCredentialID.mock
}

// Set uses given function f to mock the Store.DeleteByCredentialID method
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Set(f func(ctx context.Context, userID string, credID []byte) (err error)) *StoreMock {
	if mmDeleteByCredentialID.defaultExpectation != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("Default expectation is already set for the Store.DeleteByCredentialID method")
	}

	if len(mmDeleteByCredentialID.expectations) > 0 {
		mmDeleteByCredentialID.mock.t.Fatalf("Some expectations are already set for the Store.DeleteByCredentialID method")
	}

	mmDeleteByCredentialID.mock.funcDeleteByCredentialID = f
	mmDeleteByCredentialID.mock.funcDeleteByCredentialIDOrigin = minimock.CallerInfo(1)
	return mmDeleteByCredentialID.mock
}

// When sets expectation for the Store.DeleteByCredentialID which will trigger the result defined by the following
// Then helper
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) When(ctx context.Context, userID string, credID []byte) *StoreMockDeleteByCredentialIDExpectation {
	if mmDeleteByCredentialID.mock.funcDeleteByCredentialID != nil {
		mmDeleteByCredentialID.mock.t.Fatalf("StoreMock.DeleteByCredentialID mock is already set by Set")
	}

	expectation := &StoreMockDeleteByCredentialIDExpectation{
		mock:               mmDeleteByCredentialID.mock,
		params:             &StoreMockDeleteByCredentialIDParams{ctx, userID, credID},
		expectationOrigins: StoreMockDeleteByCredentialIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteByCredentialID.expectations = append(mmDeleteByCredentialID.expectations, expectation)
	return expectation
}

// Then sets up Store.DeleteByCredentialID return parameters for the expectation previously defined by the When method
func (e *StoreMockDeleteByCredentialIDExpectation) Then(err error) *StoreMock {
	e.results = &StoreMockDeleteByCredentialIDResults{err}
	return e.mock
}

// Times sets number of times Store.DeleteByCredentialID should be invoked
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Times(n uint64) *mStoreMockDeleteByCredentialID {
	if n == 0 {
		mmDeleteByCredentialID.mock.t.Fatalf("Times of StoreMock.DeleteByCredentialID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteByCredentialID.expectedInvocations, n)
	mmDeleteByCredentialID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteByCredentialID
}

func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) invocationsDone() bool {
	if len(mmDeleteByCredentialID.expectations) == 0 && mmDeleteByCredentialID.defaultExpectation == nil && mmDeleteByCredentialID.mock.funcDeleteByCredentialID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteByCredentialID.mock.afterDeleteByCredentialIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteByCredentialID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteByCredentialID implements mm_passkey.Store
func (mmDeleteByCredentialID *StoreMock) DeleteByCredentialID(ctx context.Context, userID string, credID []byte) (err error) {
	mm_atomic.AddUint64(&mmDeleteByCredentialID.beforeDeleteByCredentialIDCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteByCredentialID.afterDeleteByCredentialIDCounter, 1)

	mmDeleteByCredentialID.t.Helper()

	if mmDeleteByCredentialID.inspectFuncDeleteByCredentialID != nil {
		mmDeleteByCredentialID.inspectFuncDeleteByCredentialID(ctx, userID, credID)
	}

	mm_params := StoreMockDeleteByCredentialIDParams{ctx, userID, credID}

	// Record call args
	mmDeleteByCredentialID.DeleteByCredentialIDMock.mutex.Lock()
	mmDeleteByCredentialID.DeleteByCredentialIDMock.callArgs = append(mmDeleteByCredentialID.DeleteByCredentialIDMock.callArgs, &mm_params)
	mmDeleteByCredentialID.DeleteByCredentialIDMock.mutex.Unlock()

	for _, e := range mmDeleteByCredentialID.DeleteByCredentialIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.paramPtrs

		mm_got := StoreMockDeleteByCredentialIDParams{ctx, userID, credID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteByCredentialID.t.Errorf("StoreMock.DeleteByCredentialID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteByCredentialID.t.Errorf("StoreMock.DeleteByCredentialID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.credID != nil && !minimock.Equal(*mm_want_ptrs.credID, mm_got.credID) {
				mmDeleteByCredentialID.t.Errorf("StoreMock.DeleteByCredentialID got unexpected parameter credID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.expectationOrigins.originCredID, *mm_want_ptrs.credID, mm_got.credID, minimock.Diff(*mm_want_ptrs.credID, mm_got.credID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteByCredentialID.t.Errorf("StoreMock.DeleteByCredentialID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteByCredentialID.DeleteByCredentialIDMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteByCredentialID.t.Fatal("No results are set for the StoreMock.DeleteByCredentialID")
		}
		return (*mm_results).err
	}
	if mmDeleteByCredentialID.funcDeleteByCredentialID != nil {
		return mmDeleteByCredentialID.funcDeleteByCredentialID(ctx, userID, credID)
	}
	mmDeleteByCredentialID.t.Fatalf("Unexpected call to StoreMock.DeleteByCredentialID. %v %v %v", ctx, userID, credID)
	return
}

// DeleteByCredentialIDAfterCounter returns a count of finished StoreMock.DeleteByCredentialID invocations
func (mmDeleteByCredentialID *StoreMock) DeleteByCredentialIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteByCredentialID.afterDeleteByCredentialIDCounter)
}

// DeleteByCredentialIDBeforeCounter returns a count of StoreMock.DeleteByCredentialID invocations
func (mmDeleteByCredentialID *StoreMock) DeleteByCredentialIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteByCredentialID.beforeDeleteByCredentialIDCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.DeleteByCredentialID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteByCredentialID *mStoreMockDeleteByCredentialID) Calls() []*StoreMockDeleteByCredentialIDParams {
	mmDeleteByCredentialID.mutex.RLock()

	argCopy := make([]*StoreMockDeleteByCredentialIDParams, len(mmDeleteByCredentialID.callArgs))
	copy(argCopy, mmDeleteByCredentialID.callArgs)

	mmDeleteByCredentialID.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteByCredentialIDDone returns true if the count of the DeleteByCredentialID invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockDeleteByCredentialIDDone() bool {
	if m.DeleteByCredentialIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteByCredentialIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteByCredentialIDMock.invocationsDone()
}

// MinimockDeleteByCredentialIDInspect logs each unmet expectation
func (m *StoreMock) MinimockDeleteByCredentialIDInspect() {
	for _, e := range m.DeleteByCredentialIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.DeleteByCredentialID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteByCredentialIDCounter := mm_atomic.LoadUint64(&m.afterDeleteByCredentialIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteByCredentialIDMock.defaultExpectation != nil && afterDeleteByCredentialIDCounter < 1 {
		if m.DeleteByCredentialIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.DeleteByCredentialID at\n%s", m.DeleteByCredentialIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.DeleteByCredentialID at\n%s with params: %#v", m.DeleteByCredentialIDMock.defaultExpectation.expectationOrigins.origin, *m.DeleteByCredentialIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteByCredentialID != nil && afterDeleteByCredentialIDCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.DeleteByCredentialID at\n%s", m.funcDeleteByCredentialIDOrigin)
	}

	if !m.DeleteByCredentialIDMock.invocationsDone() && afterDeleteByCredentialIDCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.DeleteByCredentialID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteByCredentialIDMock.expectedInvocations), m.DeleteByCredentialIDMock.expectedInvocationsOrigin, afterDeleteByCredentialIDCounter)
	}
}

type mStoreMockListByUser struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockListByUserExpectation
	expectations       []*StoreMockListByUserExpectation

	callArgs []*StoreMockListByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockListByUserExpectation specifies expectation struct of the Store.ListByUser
type StoreMockListByUserExpectation struct {
	mock               *StoreMock
	params             *StoreMockListByUserParams
	paramPtrs          *StoreMockListByUserParamPtrs
	expectationOrigins StoreMockListByUserExpectationOrigins
	results            *StoreMockListByUserResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockListByUserParams contains parameters of the Store.ListByUser
type StoreMockListByUserParams struct {
	ctx    context.Context
	userID string
}

// StoreMockListByUserParamPtrs contains pointers to parameters of the Store.ListByUser
type StoreMockListByUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// StoreMockListByUserResults contains results of the Store.ListByUser
type StoreMockListByUserResults struct {
	ca1 []domain.Credential
	err error
}

// StoreMockListByUserOrigins contains origins of expectations of the Store.ListByUser
type StoreMockListByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListByUser *mStoreMockListByUser) Optional() *mStoreMockListByUser {
	mmListByUser.optional = true
	return mmListByUser
}

// Expect sets up expected params for Store.ListByUser
func (mmListByUser *mStoreMockListByUser) Expect(ctx context.Context, userID string) *mStoreMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &StoreMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.paramPtrs != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by ExpectParams functions")
	}

	mmListByUser.defaultExpectation.params = &StoreMockListByUserParams{ctx, userID}
	mmListByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListByUser.expectations {
		if minimock.Equal(e.params, mmListByUser.defaultExpectation.params) {
			mmListByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListByUser.defaultExpectation.params)
		}
	}

	return mmListByUser
}

// ExpectCtxParam1 sets up expected param ctx for Store.ListByUser
func (mmListByUser *mStoreMockListByUser) ExpectCtxParam1(ctx context.Context) *mStoreMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &StoreMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.params != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Expect")
	}

	if mmListByUser.defaultExpectation.paramPtrs == nil {
		mmListByUser.defaultExpectation.paramPtrs = &StoreMockListByUserParamPtrs{}
	}
	mmListByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmListByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListByUser
}

// ExpectUserIDParam2 sets up expected param userID for Store.ListByUser
func (mmListByUser *mStoreMockListByUser) ExpectUserIDParam2(userID string) *mStoreMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &StoreMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.params != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Expect")
	}

	if mmListByUser.defaultExpectation.paramPtrs == nil {
		mmListByUser.defaultExpectation.paramPtrs = &StoreMockListByUserParamPtrs{}
	}
	mmListByUser.defaultExpectation.paramPtrs.userID = &userID
	mmListByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmListByUser
}

// Inspect accepts an inspector function that has same arguments as the Store.ListByUser
func (mmListByUser *mStoreMockListByUser) Inspect(f func(ctx context.Context, userID string)) *mStoreMockListByUser {
	if mmListByUser.mock.inspectFuncListByUser != nil {
		mmListByUser.mock.t.Fatalf("Inspect function is already set for StoreMock.ListByUser")
	}

	mmListByUser.mock.inspectFuncListByUser = f

	return mmListByUser
}

// Return sets up results that will be returned by Store.ListByUser
func (mmListByUser *mStoreMockListByUser) Return(ca1 []domain.Credential, err error) *StoreMock {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &StoreMockListByUserExpectation{mock: mmListByUser.mock}
	}
	mmListByUser.defaultExpectation.results = &StoreMockListByUserResults{ca1, err}
	mmListByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListByUser.mock
}

// Set uses given function f to mock the Store.ListByUser method
func (mmListByUser *mStoreMockListByUser) Set(f func(ctx context.Context, userID string) (ca1 []domain.Credential, err error)) *StoreMock {
	if mmListByUser.defaultExpectation != nil {
		mmListByUser.mock.t.Fatalf("Default expectation is already set for the Store.ListByUser method")
	}

	if len(mmListByUser.expectations) > 0 {
		mmListByUser.mock.t.Fatalf("Some expectations are already set for the Store.ListByUser method")
	}

	mmListByUser.mock.funcListByUser = f
	mmListByUser.mock.funcListByUserOrigin = minimock.CallerInfo(1)
	return mmListByUser.mock
}

// When sets expectation for the Store.ListByUser which will trigger the result defined by the following
// Then helper
func (mmListByUser *mStoreMockListByUser) When(ctx context.Context, userID string) *StoreMockListByUserExpectation {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("StoreMock.ListByUser mock is already set by Set")
	}

	expectation := &StoreMockListByUserExpectation{
		mock:               mmListByUser.mock,
		params:             &StoreMockListByUserParams{ctx, userID},
		expectationOrigins: StoreMockListByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListByUser.expectations = append(mmListByUser.expectations, expectation)
	return expectation
}

// Then sets up Store.ListByUser return parameters for the expectation previously defined by the When method
func (e *StoreMockListByUserExpectation) Then(ca1 []domain.Credential, err error) *StoreMock {
	e.results = &StoreMockListByUserResults{ca1, err}
	return e.mock
}

// Times sets number of times Store.ListByUser should be invoked
func (mmListByUser *mStoreMockListByUser) Times(n uint64) *mStoreMockListByUser {
	if n == 0 {
		mmListByUser.mock.t.Fatalf("Times of StoreMock.ListByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListByUser.expectedInvocations, n)
	mmListByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListByUser
}

func (mmListByUser *mStoreMockListByUser) invocationsDone() bool {
	if len(mmListByUser.expectations) == 0 && mmListByUser.defaultExpectation == nil && mmListByUser.mock.funcListByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListByUser.mock.afterListByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListByUser implements mm_passkey.Store
func (mmListByUser *StoreMock) ListByUser(ctx context.Context, userID string) (ca1 []domain.Credential, err error) {
	mm_atomic.AddUint64(&mmListByUser.beforeListByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmListByUser.afterListByUserCounter, 1)

	mmListByUser.t.Helper()

	if mmListByUser.inspectFuncListByUser != nil {
		mmListByUser.inspectFuncListByUser(ctx, userID)
	}

	mm_params := StoreMockListByUserParams{ctx, userID}

	// Record call args
	mmListByUser.ListByUserMock.mutex.Lock()
	mmListByUser.ListByUserMock.callArgs = append(mmListByUser.ListByUserMock.callArgs, &mm_params)
	mmListByUser.ListByUserMock.mutex.Unlock()

	for _, e := range mmListByUser.ListByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ca1, e.results.err
		}
	}

	if mmListByUser.ListByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListByUser.ListByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmListByUser.ListByUserMock.defaultExpectation.params
		mm_want_ptrs := mmListByUser.ListByUserMock.defaultExpectation.paramPtrs

		mm_got := StoreMockListByUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListByUser.t.Errorf("StoreMock.ListByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmListByUser.t.Errorf("StoreMock.ListByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListByUser.t.Errorf("StoreMock.ListByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListByUser.ListByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmListByUser.t.Fatal("No results are set for the StoreMock.ListByUser")
		}
		return (*mm_results).ca1, (*mm_results).err
	}
	if mmListByUser.funcListByUser != nil {
		return mmListByUser.funcListByUser(ctx, userID)
	}
	mmListByUser.t.Fatalf("Unexpected call to StoreMock.ListByUser. %v %v", ctx, userID)
	return
}

// ListByUserAfterCounter returns a count of finished StoreMock.ListByUser invocations
func (mmListByUser *StoreMock) ListByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByUser.afterListByUserCounter)
}

// ListByUserBeforeCounter returns a count of StoreMock.ListByUser invocations
func (mmListByUser *StoreMock) ListByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByUser.beforeListByUserCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.ListByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListByUser *mStoreMockListByUser) Calls() []*StoreMockListByUserParams {
	mmListByUser.mutex.RLock()

	argCopy := make([]*StoreMockListByUserParams, len(mmListByUser.callArgs))
	copy(argCopy, mmListByUser.callArgs)

	mmListByUser.mutex.RUnlock()

	return argCopy
}

// MinimockListByUserDone returns true if the count of the ListByUser invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockListByUserDone() bool {
	if m.ListByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListByUserMock.invocationsDone()
}

// MinimockListByUserInspect logs each unmet expectation
func (m *StoreMock) MinimockListByUserInspect() {
	for _, e := range m.ListByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.ListByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListByUserCounter := mm_atomic.LoadUint64(&m.afterListByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListByUserMock.defaultExpectation != nil && afterListByUserCounter < 1 {
		if m.ListByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.ListByUser at\n%s", m.ListByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.ListByUser at\n%s with params: %#v", m.ListByUserMock.defaultExpectation.expectationOrigins.origin, *m.ListByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListByUser != nil && afterListByUserCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.ListByUser at\n%s", m.funcListByUserOrigin)
	}

	if !m.ListByUserMock.invocationsDone() && afterListByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.ListByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListByUserMock.expectedInvocations), m.ListByUserMock.expectedInvocationsOrigin, afterListByUserCounter)
	}
}

type mStoreMockUpdateSignCount struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockUpdateSignCountExpectation
	expectations       []*StoreMockUpdateSignCountExpectation

	callArgs []*StoreMockUpdateSignCountParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockUpdateSignCountExpectation specifies expectation struct of the Store.UpdateSignCount
type StoreMockUpdateSignCountExpectation struct {
	mock               *StoreMock
	params             *StoreMockUpdateSignCountParams
	paramPtrs          *StoreMockUpdateSignCountParamPtrs
	expectationOrigins StoreMockUpdateSignCountExpectationOrigins
	results            *StoreMockUpdateSignCountResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockUpdateSignCountParams contains parameters of the Store.UpdateSignCount
type StoreMockUpdateSignCountParams struct {
	ctx    context.Context
	credID []byte
	count  uint32
}

// StoreMockUpdateSignCountParamPtrs contains pointers to parameters of the Store.UpdateSignCount
type StoreMockUpdateSignCountParamPtrs struct {
	ctx    *context.Context
	credID *[]byte
	count  *uint32
}

// StoreMockUpdateSignCountResults contains results of the Store.UpdateSignCount
type StoreMockUpdateSignCountResults struct {
	err error
}

// StoreMockUpdateSignCountOrigins contains origins of expectations of the Store.UpdateSignCount
type StoreMockUpdateSignCountExpectationOrigins struct {
	origin       string
	originCtx    string
	originCredID string
	originCount  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Optional() *mStoreMockUpdateSignCount {
	mmUpdateSignCount.optional = true
	return mmUpdateSignCount
}

// Expect sets up expected params for Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Expect(ctx context.Context, credID []byte, count uint32) *mStoreMockUpdateSignCount {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	if mmUpdateSignCount.defaultExpectation == nil {
		mmUpdateSignCount.defaultExpectation = &StoreMockUpdateSignCountExpectation{}
	}

	if mmUpdateSignCount.defaultExpectation.paramPtrs != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by ExpectParams functions")
	}

	mmUpdateSignCount.defaultExpectation.params = &StoreMockUpdateSignCountParams{ctx, credID, count}
	mmUpdateSignCount.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateSignCount.expectations {
		if minimock.Equal(e.params, mmUpdateSignCount.defaultExpectation.params) {
			mmUpdateSignCount.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateSignCount.defaultExpectation.params)
		}
	}

	return mmUpdateSignCount
}

// ExpectCtxParam1 sets up expected param ctx for Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) ExpectCtxParam1(ctx context.Context) *mStoreMockUpdateSignCount {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	if mmUpdateSignCount.defaultExpectation == nil {
		mmUpdateSignCount.defaultExpectation = &StoreMockUpdateSignCountExpectation{}
	}

	if mmUpdateSignCount.defaultExpectation.params != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Expect")
	}

	if mmUpdateSignCount.defaultExpectation.paramPtrs == nil {
		mmUpdateSignCount.defaultExpectation.paramPtrs = &StoreMockUpdateSignCountParamPtrs{}
	}
	mmUpdateSignCount.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateSignCount.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateSignCount
}

// ExpectCredIDParam2 sets up expected param credID for Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) ExpectCredIDParam2(credID []byte) *mStoreMockUpdateSignCount {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	if mmUpdateSignCount.defaultExpectation == nil {
		mmUpdateSignCount.defaultExpectation = &StoreMockUpdateSignCountExpectation{}
	}

	if mmUpdateSignCount.defaultExpectation.params != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Expect")
	}

	if mmUpdateSignCount.defaultExpectation.paramPtrs == nil {
		mmUpdateSignCount.defaultExpectation.paramPtrs = &StoreMockUpdateSignCountParamPtrs{}
	}
	mmUpdateSignCount.defaultExpectation.paramPtrs.credID = &credID
	mmUpdateSignCount.defaultExpectation.expectationOrigins.originCredID = minimock.CallerInfo(1)

	return mmUpdateSignCount
}

// ExpectCountParam3 sets up expected param count for Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) ExpectCountParam3(count uint32) *mStoreMockUpdateSignCount {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	if mmUpdateSignCount.defaultExpectation == nil {
		mmUpdateSignCount.defaultExpectation = &StoreMockUpdateSignCountExpectation{}
	}

	if mmUpdateSignCount.defaultExpectation.params != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Expect")
	}

	if mmUpdateSignCount.defaultExpectation.paramPtrs == nil {
		mmUpdateSignCount.defaultExpectation.paramPtrs = &StoreMockUpdateSignCountParamPtrs{}
	}
	mmUpdateSignCount.defaultExpectation.paramPtrs.count = &count
	mmUpdateSignCount.defaultExpectation.expectationOrigins.originCount = minimock.CallerInfo(1)

	return mmUpdateSignCount
}

// Inspect accepts an inspector function that has same arguments as the Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Inspect(f func(ctx context.Context, credID []byte, count uint32)) *mStoreMockUpdateSignCount {
	if mmUpdateSignCount.mock.inspectFuncUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("Inspect function is already set for StoreMock.UpdateSignCount")
	}

	mmUpdateSignCount.mock.inspectFuncUpdateSignCount = f

	return mmUpdateSignCount
}

// Return sets up results that will be returned by Store.UpdateSignCount
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Return(err error) *StoreMock {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	if mmUpdateSignCount.defaultExpectation == nil {
		mmUpdateSignCount.defaultExpectation = &StoreMockUpdateSignCountExpectation{mock: mmUpdateSignCount.mock}
	}
	mmUpdateSignCount.defaultExpectation.results = &StoreMockUpdateSignCountResults{err}
	mmUpdateSignCount.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateSignCount.mock
}

// Set uses given function f to mock the Store.UpdateSignCount method
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Set(f func(ctx context.Context, credID []byte, count uint32) (err error)) *StoreMock {
	if mmUpdateSignCount.defaultExpectation != nil {
		mmUpdateSignCount.mock.t.Fatalf("Default expectation is already set for the Store.UpdateSignCount method")
	}

	if len(mmUpdateSignCount.expectations) > 0 {
		mmUpdateSignCount.mock.t.Fatalf("Some expectations are already set for the Store.UpdateSignCount method")
	}

	mmUpdateSignCount.mock.funcUpdateSignCount = f
	mmUpdateSignCount.mock.funcUpdateSignCountOrigin = minimock.CallerInfo(1)
	return mmUpdateSignCount.mock
}

// When sets expectation for the Store.UpdateSignCount which will trigger the result defined by the following
// Then helper
func (mmUpdateSignCount *mStoreMockUpdateSignCount) When(ctx context.Context, credID []byte, count uint32) *StoreMockUpdateSignCountExpectation {
	if mmUpdateSignCount.mock.funcUpdateSignCount != nil {
		mmUpdateSignCount.mock.t.Fatalf("StoreMock.UpdateSignCount mock is already set by Set")
	}

	expectation := &StoreMockUpdateSignCountExpectation{
		mock:               mmUpdateSignCount.mock,
		params:             &StoreMockUpdateSignCountParams{ctx, credID, count},
		expectationOrigins: StoreMockUpdateSignCountExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateSignCount.expectations = append(mmUpdateSignCount.expectations, expectation)
	return expectation
}

// Then sets up Store.UpdateSignCount return parameters for the expectation previously defined by the When method
func (e *StoreMockUpdateSignCountExpectation) Then(err error) *StoreMock {
	e.results = &StoreMockUpdateSignCountResults{err}
	return e.mock
}

// Times sets number of times Store.UpdateSignCount should be invoked
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Times(n uint64) *mStoreMockUpdateSignCount {
	if n == 0 {
		mmUpdateSignCount.mock.t.Fatalf("Times of StoreMock.UpdateSignCount mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateSignCount.expectedInvocations, n)
	mmUpdateSignCount.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateSignCount
}

func (mmUpdateSignCount *mStoreMockUpdateSignCount) invocationsDone() bool {
	if len(mmUpdateSignCount.expectations) == 0 && mmUpdateSignCount.defaultExpectation == nil && mmUpdateSignCount.mock.funcUpdateSignCount == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateSignCount.mock.afterUpdateSignCountCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateSignCount.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateSignCount implements mm_passkey.Store
func (mmUpdateSignCount *StoreMock) UpdateSignCount(ctx context.Context, credID []byte, count uint32) (err error) {
	mm_atomic.AddUint64(&mmUpdateSignCount.beforeUpdateSignCountCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateSignCount.afterUpdateSignCountCounter, 1)

	mmUpdateSignCount.t.Helper()

	if mmUpdateSignCount.inspectFuncUpdateSignCount != nil {
		mmUpdateSignCount.inspectFuncUpdateSignCount(ctx, credID, count)
	}

	mm_params := StoreMockUpdateSignCountParams{ctx, credID, count}

	// Record call args
	mmUpdateSignCount.UpdateSignCountMock.mutex.Lock()
	mmUpdateSignCount.UpdateSignCountMock.callArgs = append(mmUpdateSignCount.UpdateSignCountMock.callArgs, &mm_params)
	mmUpdateSignCount.UpdateSignCountMock.mutex.Unlock()

	for _, e := range mmUpdateSignCount.UpdateSignCountMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateSignCount.UpdateSignCountMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.paramPtrs

		mm_got := StoreMockUpdateSignCountParams{ctx, credID, count}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateSignCount.t.Errorf("StoreMock.UpdateSignCount got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.credID != nil && !minimock.Equal(*mm_want_ptrs.credID, mm_got.credID) {
				mmUpdateSignCount.t.Errorf("StoreMock.UpdateSignCount got unexpected parameter credID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.expectationOrigins.originCredID, *mm_want_ptrs.credID, mm_got.credID, minimock.Diff(*mm_want_ptrs.credID, mm_got.credID))
			}

			if mm_want_ptrs.count != nil && !minimock.Equal(*mm_want_ptrs.count, mm_got.count) {
				mmUpdateSignCount.t.Errorf("StoreMock.UpdateSignCount got unexpected parameter count, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.expectationOrigins.originCount, *mm_want_ptrs.count, mm_got.count, minimock.Diff(*mm_want_ptrs.count, mm_got.count))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateSignCount.t.Errorf("StoreMock.UpdateSignCount got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateSignCount.UpdateSignCountMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateSignCount.t.Fatal("No results are set for the StoreMock.UpdateSignCount")
		}
		return (*mm_results).err
	}
	if mmUpdateSignCount.funcUpdateSignCount != nil {
		return mmUpdateSignCount.funcUpdateSignCount(ctx, credID, count)
	}
	mmUpdateSignCount.t.Fatalf("Unexpected call to StoreMock.UpdateSignCount. %v %v %v", ctx, credID, count)
	return
}

// UpdateSignCountAfterCounter returns a count of finished StoreMock.UpdateSignCount invocations
func (mmUpdateSignCount *StoreMock) UpdateSignCountAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateSignCount.afterUpdateSignCountCounter)
}

// UpdateSignCountBeforeCounter returns a count of StoreMock.UpdateSignCount invocations
func (mmUpdateSignCount *StoreMock) UpdateSignCountBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateSignCount.beforeUpdateSignCountCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.UpdateSignCount.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateSignCount *mStoreMockUpdateSignCount) Calls() []*StoreMockUpdateSignCountParams {
	mmUpdateSignCount.mutex.RLock()

	argCopy := make([]*StoreMockUpdateSignCountParams, len(mmUpdateSignCount.callArgs))
	copy(argCopy, mmUpdateSignCount.callArgs)

	mmUpdateSignCount.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateSignCountDone returns true if the count of the UpdateSignCount invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockUpdateSignCountDone() bool {
	if m.UpdateSignCountMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateSignCountMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateSignCountMock.invocationsDone()
}

// MinimockUpdateSignCountInspect logs each unmet expectation
func (m *StoreMock) MinimockUpdateSignCountInspect() {
	for _, e := range m.UpdateSignCountMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.UpdateSignCount at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateSignCountCounter := mm_atomic.LoadUint64(&m.afterUpdateSignCountCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateSignCountMock.defaultExpectation != nil && afterUpdateSignCountCounter < 1 {
		if m.UpdateSignCountMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.UpdateSignCount at\n%s", m.UpdateSignCountMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.UpdateSignCount at\n%s with params: %#v", m.UpdateSignCountMock.defaultExpectation.expectationOrigins.origin, *m.UpdateSignCountMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateSignCount != nil && afterUpdateSignCountCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.UpdateSignCount at\n%s", m.funcUpdateSignCountOrigin)
	}

	if !m.UpdateSignCountMock.invocationsDone() && afterUpdateSignCountCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.UpdateSignCount at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateSignCountMock.expectedInvocations), m.UpdateSignCountMock.expectedInvocationsOrigin, afterUpdateSignCountCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteByCredentialIDInspect()

			m.MinimockListByUserInspect()

			m.MinimockUpdateSignCountInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteByCredentialIDDone() &&
		m.MinimockListByUserDone() &&
		m.MinimockUpdateSignCountDone()
}
