/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/territories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List territories */
        get: operations["listTerritories"];
        put?: never;
        /** Register a territory and queue its conversion */
        post: operations["createTerritory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Get a territory by slug */
        get: operations["getTerritory"];
        put?: never;
        post?: never;
        /** Delete a territory and its placements */
        delete: operations["deleteTerritory"];
        options?: never;
        head?: never;
        /** Update mutable territory fields (no re-conversion) */
        patch: operations["updateTerritory"];
        trace?: never;
    };
    "/api/territories/{slug}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace a territory's source archive and re-queue conversion
         * @description Swaps the territory's source ZIP in place and queues a fresh
         *     conversion. The territory (and its placements) are kept; existing
         *     artifacts are cleared so the viewer shows the conversion screen until
         *     the new mesh lands. Response mirrors createTerritory.
         */
        post: operations["replaceTerritorySource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/scene": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Single-shot bundle for the viewer page */
        get: operations["getSceneBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** List converted artifacts for a territory */
        get: operations["listTerritoryArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/artifacts/{lod}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                lod: number;
            };
            cookie?: never;
        };
        /** Get one converted artifact (territory) */
        get: operations["getTerritoryArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** List placements on a territory */
        get: operations["listPlacements"];
        put?: never;
        /** Add a placement to a territory */
        post: operations["createPlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/placements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a placement's transform */
        put: operations["updatePlacement"];
        post?: never;
        /** Remove a placement */
        delete: operations["deletePlacement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/placements/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a placement's panorama allowlist */
        put: operations["setPlacementVisibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/panoramas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** List panoramas anchored to a territory */
        get: operations["listPanoramas"];
        put?: never;
        /** Anchor a new equirect panorama in the territory */
        post: operations["createPanorama"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territories/{slug}/panoramas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a panorama's title, position, and yaw offset */
        put: operations["updatePanorama"];
        post?: never;
        /** Remove a panorama */
        delete: operations["deletePanorama"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List models */
        get: operations["listModels"];
        put?: never;
        /** Register a model and queue its conversion */
        post: operations["createModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Get a model by slug */
        get: operations["getModel"];
        put?: never;
        post?: never;
        /**
         * Delete a model
         * @description Refuses to delete a model still referenced by placements.
         */
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{slug}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** List converted artifacts for a model */
        get: operations["listModelArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{slug}/artifacts/{lod}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                lod: number;
            };
            cookie?: never;
        };
        /** Get one converted artifact (model) */
        get: operations["getModelArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a chunked upload session */
        post: operations["initiateUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard an in-progress session */
        delete: operations["abortUpload"];
        options?: never;
        /** Query the current offset of a session */
        head: operations["getUploadStatus"];
        /**
         * Append bytes to a session at the given offset
         * @description Body is the raw chunk; the absolute byte offset goes in the
         *     `Upload-Offset` header. The server returns the new total in
         *     the `Upload-Offset` response header.
         */
        patch: operations["appendUploadChunk"];
        trace?: never;
    };
    "/api/uploads/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a session and publish the bytes to BlobStore */
        post: operations["finalizeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Vec3: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            /** Format: double */
            z: number;
        };
        Territory: {
            slug: string;
            title: string;
            description?: string;
            externalPanoramaUrl?: string;
            sourceBlobHash: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Model: {
            slug: string;
            title: string;
            description?: string;
            sourceBlobHash: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description Minimal descriptor for one LOD level. Carries only size/geometry
         *     stats — bbox, contentType, createdAt are LOD-invariant and live
         *     on the parent Artifact.
         */
        LodArtifact: {
            /** Format: int32 */
            lod: number;
            hash: string;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            vertices?: number;
            /** Format: int64 */
            faces?: number;
        };
        Artifact: {
            /** @description Owner slug (territory or model, depending on the endpoint). */
            slug: string;
            /** Format: int32 */
            lod: number;
            hash: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            vertices?: number;
            /** Format: int64 */
            faces?: number;
            bboxMin?: components["schemas"]["Vec3"];
            bboxMax?: components["schemas"]["Vec3"];
            /** Format: date-time */
            createdAt?: string;
            /**
             * @description All available LODs for this owner, sorted by lod ascending.
             *     Populated by /scene; absent on /artifacts list/get endpoints
             *     where the array would be redundant.
             */
            artifacts?: components["schemas"]["LodArtifact"][];
        };
        /** @enum {string} */
        JobStatus: "pending" | "running" | "succeeded" | "failed";
        /**
         * @description Which catalog domain the job's outputs belong to.
         * @enum {string}
         */
        JobKind: "territory" | "model";
        Job: {
            id: string;
            kind: components["schemas"]["JobKind"];
            slug: string;
            status: components["schemas"]["JobStatus"];
            errorMessage?: string;
            artifactHash?: string;
            /**
             * Format: float
             * @description Fraction of conversion work completed (0..1).
             */
            progress?: number;
            /**
             * @description Coarse-grained phase label set by the worker — one of
             *     "fetching" / "extracting" / "parsing" / "encoding" /
             *     "compressing" / "lod-N" / "registering".
             */
            stage?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Placement: {
            /** Format: int64 */
            id: number;
            territorySlug: string;
            modelSlug: string;
            position: components["schemas"]["Vec3"];
            rotation: components["schemas"]["Vec3"];
            scale: components["schemas"]["Vec3"];
            label?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @description Allowlist of panorama ids this placement is shown in (panorama mode only — the 3D view always shows every placement). Empty means hidden in every panorama. */
            visiblePanoramaIds?: number[];
        };
        PlacementCreate: {
            modelSlug: string;
            position?: components["schemas"]["Vec3"];
            rotation?: components["schemas"]["Vec3"];
            scale?: components["schemas"]["Vec3"];
            label?: string;
            /** @description Initial panorama allowlist (e.g. the active panorama). */
            visiblePanoramaIds?: number[];
        };
        PlacementUpdate: {
            position?: components["schemas"]["Vec3"];
            rotation?: components["schemas"]["Vec3"];
            scale?: components["schemas"]["Vec3"];
            label?: string;
        };
        PlacementVisibilityUpdate: {
            /** @description Full replacement allowlist of panorama ids. */
            panoramaIds: number[];
        };
        /**
         * @description Equirectangular panorama (Insta360 Pro source) anchored to a point
         *     in a territory's scene-units space. The viewer "panorama mode"
         *     teleports the camera to position and renders a sphere skybox;
         *     placements stay shared with the 3D view so equipment placed in
         *     either mode is visible from the other.
         */
        Panorama: {
            /** Format: int64 */
            id: number;
            territorySlug: string;
            slug: string;
            title: string;
            /** @description BlobStore hash for the equirect JPG/PNG; served via /api/assets/{hash}. */
            sourceBlobHash: string;
            position: components["schemas"]["Vec3"];
            /**
             * Format: double
             * @description Rotation around the sphere's Y axis (radians) to align the
             *     panorama's implicit "north" with the territory's axes.
             */
            yawOffset: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description Body for POST /api/territories/{slug}/panoramas. The slug is derived
         *     from the title by the catalog and made unique within the territory —
         *     it is not client-supplied.
         */
        PanoramaCreate: {
            title: string;
            sourceBlobHash: string;
            position?: components["schemas"]["Vec3"];
            /** Format: double */
            yawOffset?: number;
        };
        PanoramaUpdate: {
            title?: string;
            position?: components["schemas"]["Vec3"];
            /** Format: double */
            yawOffset?: number;
        };
        /**
         * @description Body for POST /api/territories and POST /api/models. The client
         *     first uploads the source ZIP via /api/uploads, then attaches the
         *     returned hash here. The gateway forwards the entity to catalog
         *     and queues a conversion job; the response carries both the new
         *     entity and the queued Job for SSE subscription. The slug is derived
         *     from the title by the catalog and made unique — not client-supplied.
         */
        EntityCreate: {
            title: string;
            description?: string;
            externalPanoramaUrl?: string;
            sourceBlobHash: string;
        };
        /**
         * @description Body for PATCH /api/territories/{slug}. Updates mutable fields only;
         *     the source archive and conversion are untouched. Omitted fields are
         *     left unchanged.
         */
        TerritoryUpdate: {
            externalPanoramaUrl?: string;
        };
        /**
         * @description Body for POST /api/territories/{slug}/source. Carries the hash of a
         *     freshly uploaded ZIP (via /api/uploads); the territory's source is
         *     swapped to it and a new conversion is queued.
         */
        TerritorySourceReplace: {
            sourceBlobHash: string;
        };
        TerritoryCreated: {
            territory: components["schemas"]["Territory"];
            job: components["schemas"]["Job"];
        };
        ModelCreated: {
            model: components["schemas"]["Model"];
            job: components["schemas"]["Job"];
        };
        AssetOption: {
            slug: string;
            title: string;
            /**
             * @description Original (pre-normalize) bounding-box minimum of the source
             *     mesh. Carried so the frontend can compute a real-size scale
             *     when dropping a model onto a territory.
             */
            bboxMin?: components["schemas"]["Vec3"];
            /** @description Original (pre-normalize) bounding-box maximum. */
            bboxMax?: components["schemas"]["Vec3"];
            /**
             * @description All available LODs for this model, sorted by lod ascending.
             *     Empty when the model has no successful conversion yet — the
             *     frontend can grey it out in the picker.
             */
            artifacts: components["schemas"]["LodArtifact"][];
        };
        /**
         * @description Single-shot bundle for the viewer page. Includes the requested
         *     territory, its current LOD0 artifact (when present), all
         *     placements on it, and the list of available models with their
         *     artifacts for the placement picker.
         */
        SceneBundle: {
            territory: components["schemas"]["Territory"];
            artifact?: components["schemas"]["Artifact"];
            placements: components["schemas"]["Placement"][];
            modelOptions: components["schemas"]["AssetOption"][];
            /**
             * @description Equirect panoramas anchored to this territory. The viewer
             *     renders them as toggleable alternate camera modes; placements
             *     stay shared between the 3D and panorama views.
             */
            panoramas?: components["schemas"]["Panorama"][];
        };
        UploadInitiate: {
            /** Format: int64 */
            size: number;
            contentType?: string;
        };
        UploadSession: {
            id: string;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            offset: number;
            contentType?: string;
        };
        UploadFinalized: {
            hash: string;
            /** Format: int64 */
            size: number;
        };
        Error: {
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTerritories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Territory"][];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    createTerritory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Territory created and conversion queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["Internal"];
        };
    };
    getTerritory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Territory"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    deleteTerritory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updateTerritory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerritoryUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Territory"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    replaceTerritorySource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerritorySourceReplace"];
            };
        };
        responses: {
            /** @description Source replaced and conversion queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getSceneBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneBundle"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listTerritoryArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getTerritoryArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                lod: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listPlacements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    createPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updatePlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    deletePlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    setPlacementVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementVisibilityUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listPanoramas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Panorama"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    createPanorama: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PanoramaCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Panorama"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updatePanorama: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PanoramaUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Panorama"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    deletePanorama: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    createModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Model created and conversion queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["Internal"];
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listModelArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getModelArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                lod: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    initiateUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInitiate"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["Internal"];
        };
    };
    abortUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aborted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["Internal"];
        };
    };
    getUploadStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Upload-Offset"?: number;
                    "Upload-Length"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    appendUploadChunk: {
        parameters: {
            query?: never;
            header: {
                "Upload-Offset": number;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Accepted; current offset returned in Upload-Offset */
            204: {
                headers: {
                    "Upload-Offset"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    finalizeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFinalized"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
}
