version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - errname
    - gocritic
    - govet
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unused

  settings:
    revive:
      rules:
        - name: var-naming
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true

formatters:
  enable:
    - gofumpt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
