{
  "apiVersion": 1,
  "contactPoints": [
    {
      "orgId": 1,
      "name": "in-app",
      "receivers": [
        {
          "uid": "in-app-null",
          "type": "webhook",
          "disableResolveMessage": true,
          "settings": {
            "url": "http://localhost:3000/api/health"
          }
        }
      ]
    }
  ]
}
