// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/rosneft/backend/services/audit-service/internal/service.Store -o store_mock.go -n StoreMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/rosneft/backend/services/audit-service/internal/domain"
)

// StoreMock implements mm_service.Store
type StoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDistinctActors          func(ctx context.Context, f domain.Filter) (sa1 []string, err error)
	funcDistinctActorsOrigin    string
	inspectFuncDistinctActors   func(ctx context.Context, f domain.Filter)
	afterDistinctActorsCounter  uint64
	beforeDistinctActorsCounter uint64
	DistinctActorsMock          mStoreMockDistinctActors

	funcList          func(ctx context.Context, f domain.Filter) (ea1 []domain.Entry, err error)
	funcListOrigin    string
	inspectFuncList   func(ctx context.Context, f domain.Filter)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mStoreMockList

	funcRecord          func(ctx context.Context, e domain.Entry) (i1 int64, err error)
	funcRecordOrigin    string
	inspectFuncRecord   func(ctx context.Context, e domain.Entry)
	afterRecordCounter  uint64
	beforeRecordCounter uint64
	RecordMock          mStoreMockRecord
}

// NewStoreMock returns a mock for mm_service.Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DistinctActorsMock = mStoreMockDistinctActors{mock: m}
	m.DistinctActorsMock.callArgs = []*StoreMockDistinctActorsParams{}

	m.ListMock = mStoreMockList{mock: m}
	m.ListMock.callArgs = []*StoreMockListParams{}

	m.RecordMock = mStoreMockRecord{mock: m}
	m.RecordMock.callArgs = []*StoreMockRecordParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreMockDistinctActors struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockDistinctActorsExpectation
	expectations       []*StoreMockDistinctActorsExpectation

	callArgs []*StoreMockDistinctActorsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockDistinctActorsExpectation specifies expectation struct of the Store.DistinctActors
type StoreMockDistinctActorsExpectation struct {
	mock               *StoreMock
	params             *StoreMockDistinctActorsParams
	paramPtrs          *StoreMockDistinctActorsParamPtrs
	expectationOrigins StoreMockDistinctActorsExpectationOrigins
	results            *StoreMockDistinctActorsResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockDistinctActorsParams contains parameters of the Store.DistinctActors
type StoreMockDistinctActorsParams struct {
	ctx context.Context
	f   domain.Filter
}

// StoreMockDistinctActorsParamPtrs contains pointers to parameters of the Store.DistinctActors
type StoreMockDistinctActorsParamPtrs struct {
	ctx *context.Context
	f   *domain.Filter
}

// StoreMockDistinctActorsResults contains results of the Store.DistinctActors
type StoreMockDistinctActorsResults struct {
	sa1 []string
	err error
}

// StoreMockDistinctActorsOrigins contains origins of expectations of the Store.DistinctActors
type StoreMockDistinctActorsExpectationOrigins struct {
	origin    string
	originCtx string
	originF   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDistinctActors *mStoreMockDistinctActors) Optional() *mStoreMockDistinctActors {
	mmDistinctActors.optional = true
	return mmDistinctActors
}

// Expect sets up expected params for Store.DistinctActors
func (mmDistinctActors *mStoreMockDistinctActors) Expect(ctx context.Context, f domain.Filter) *mStoreMockDistinctActors {
	if mmDistinctActors.mock.funcDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Set")
	}

	if mmDistinctActors.defaultExpectation == nil {
		mmDistinctActors.defaultExpectation = &StoreMockDistinctActorsExpectation{}
	}

	if mmDistinctActors.defaultExpectation.paramPtrs != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by ExpectParams functions")
	}

	mmDistinctActors.defaultExpectation.params = &StoreMockDistinctActorsParams{ctx, f}
	mmDistinctActors.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDistinctActors.expectations {
		if minimock.Equal(e.params, mmDistinctActors.defaultExpectation.params) {
			mmDistinctActors.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDistinctActors.defaultExpectation.params)
		}
	}

	return mmDistinctActors
}

// ExpectCtxParam1 sets up expected param ctx for Store.DistinctActors
func (mmDistinctActors *mStoreMockDistinctActors) ExpectCtxParam1(ctx context.Context) *mStoreMockDistinctActors {
	if mmDistinctActors.mock.funcDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Set")
	}

	if mmDistinctActors.defaultExpectation == nil {
		mmDistinctActors.defaultExpectation = &StoreMockDistinctActorsExpectation{}
	}

	if mmDistinctActors.defaultExpectation.params != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Expect")
	}

	if mmDistinctActors.defaultExpectation.paramPtrs == nil {
		mmDistinctActors.defaultExpectation.paramPtrs = &StoreMockDistinctActorsParamPtrs{}
	}
	mmDistinctActors.defaultExpectation.paramPtrs.ctx = &ctx
	mmDistinctActors.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDistinctActors
}

// ExpectFParam2 sets up expected param f for Store.DistinctActors
func (mmDistinctActors *mStoreMockDistinctActors) ExpectFParam2(f domain.Filter) *mStoreMockDistinctActors {
	if mmDistinctActors.mock.funcDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Set")
	}

	if mmDistinctActors.defaultExpectation == nil {
		mmDistinctActors.defaultExpectation = &StoreMockDistinctActorsExpectation{}
	}

	if mmDistinctActors.defaultExpectation.params != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Expect")
	}

	if mmDistinctActors.defaultExpectation.paramPtrs == nil {
		mmDistinctActors.defaultExpectation.paramPtrs = &StoreMockDistinctActorsParamPtrs{}
	}
	mmDistinctActors.defaultExpectation.paramPtrs.f = &f
	mmDistinctActors.defaultExpectation.expectationOrigins.originF = minimock.CallerInfo(1)

	return mmDistinctActors
}

// Inspect accepts an inspector function that has same arguments as the Store.DistinctActors
func (mmDistinctActors *mStoreMockDistinctActors) Inspect(f func(ctx context.Context, f domain.Filter)) *mStoreMockDistinctActors {
	if mmDistinctActors.mock.inspectFuncDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("Inspect function is already set for StoreMock.DistinctActors")
	}

	mmDistinctActors.mock.inspectFuncDistinctActors = f

	return mmDistinctActors
}

// Return sets up results that will be returned by Store.DistinctActors
func (mmDistinctActors *mStoreMockDistinctActors) Return(sa1 []string, err error) *StoreMock {
	if mmDistinctActors.mock.funcDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Set")
	}

	if mmDistinctActors.defaultExpectation == nil {
		mmDistinctActors.defaultExpectation = &StoreMockDistinctActorsExpectation{mock: mmDistinctActors.mock}
	}
	mmDistinctActors.defaultExpectation.results = &StoreMockDistinctActorsResults{sa1, err}
	mmDistinctActors.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDistinctActors.mock
}

// Set uses given function f to mock the Store.DistinctActors method
func (mmDistinctActors *mStoreMockDistinctActors) Set(f func(ctx context.Context, f domain.Filter) (sa1 []string, err error)) *StoreMock {
	if mmDistinctActors.defaultExpectation != nil {
		mmDistinctActors.mock.t.Fatalf("Default expectation is already set for the Store.DistinctActors method")
	}

	if len(mmDistinctActors.expectations) > 0 {
		mmDistinctActors.mock.t.Fatalf("Some expectations are already set for the Store.DistinctActors method")
	}

	mmDistinctActors.mock.funcDistinctActors = f
	mmDistinctActors.mock.funcDistinctActorsOrigin = minimock.CallerInfo(1)
	return mmDistinctActors.mock
}

// When sets expectation for the Store.DistinctActors which will trigger the result defined by the following
// Then helper
func (mmDistinctActors *mStoreMockDistinctActors) When(ctx context.Context, f domain.Filter) *StoreMockDistinctActorsExpectation {
	if mmDistinctActors.mock.funcDistinctActors != nil {
		mmDistinctActors.mock.t.Fatalf("StoreMock.DistinctActors mock is already set by Set")
	}

	expectation := &StoreMockDistinctActorsExpectation{
		mock:               mmDistinctActors.mock,
		params:             &StoreMockDistinctActorsParams{ctx, f},
		expectationOrigins: StoreMockDistinctActorsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDistinctActors.expectations = append(mmDistinctActors.expectations, expectation)
	return expectation
}

// Then sets up Store.DistinctActors return parameters for the expectation previously defined by the When method
func (e *StoreMockDistinctActorsExpectation) Then(sa1 []string, err error) *StoreMock {
	e.results = &StoreMockDistinctActorsResults{sa1, err}
	return e.mock
}

// Times sets number of times Store.DistinctActors should be invoked
func (mmDistinctActors *mStoreMockDistinctActors) Times(n uint64) *mStoreMockDistinctActors {
	if n == 0 {
		mmDistinctActors.mock.t.Fatalf("Times of StoreMock.DistinctActors mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDistinctActors.expectedInvocations, n)
	mmDistinctActors.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDistinctActors
}

func (mmDistinctActors *mStoreMockDistinctActors) invocationsDone() bool {
	if len(mmDistinctActors.expectations) == 0 && mmDistinctActors.defaultExpectation == nil && mmDistinctActors.mock.funcDistinctActors == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDistinctActors.mock.afterDistinctActorsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDistinctActors.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DistinctActors implements mm_service.Store
func (mmDistinctActors *StoreMock) DistinctActors(ctx context.Context, f domain.Filter) (sa1 []string, err error) {
	mm_atomic.AddUint64(&mmDistinctActors.beforeDistinctActorsCounter, 1)
	defer mm_atomic.AddUint64(&mmDistinctActors.afterDistinctActorsCounter, 1)

	mmDistinctActors.t.Helper()

	if mmDistinctActors.inspectFuncDistinctActors != nil {
		mmDistinctActors.inspectFuncDistinctActors(ctx, f)
	}

	mm_params := StoreMockDistinctActorsParams{ctx, f}

	// Record call args
	mmDistinctActors.DistinctActorsMock.mutex.Lock()
	mmDistinctActors.DistinctActorsMock.callArgs = append(mmDistinctActors.DistinctActorsMock.callArgs, &mm_params)
	mmDistinctActors.DistinctActorsMock.mutex.Unlock()

	for _, e := range mmDistinctActors.DistinctActorsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmDistinctActors.DistinctActorsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDistinctActors.DistinctActorsMock.defaultExpectation.Counter, 1)
		mm_want := mmDistinctActors.DistinctActorsMock.defaultExpectation.params
		mm_want_ptrs := mmDistinctActors.DistinctActorsMock.defaultExpectation.paramPtrs

		mm_got := StoreMockDistinctActorsParams{ctx, f}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDistinctActors.t.Errorf("StoreMock.DistinctActors got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDistinctActors.DistinctActorsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.f != nil && !minimock.Equal(*mm_want_ptrs.f, mm_got.f) {
				mmDistinctActors.t.Errorf("StoreMock.DistinctActors got unexpected parameter f, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDistinctActors.DistinctActorsMock.defaultExpectation.expectationOrigins.originF, *mm_want_ptrs.f, mm_got.f, minimock.Diff(*mm_want_ptrs.f, mm_got.f))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDistinctActors.t.Errorf("StoreMock.DistinctActors got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDistinctActors.DistinctActorsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDistinctActors.DistinctActorsMock.defaultExpectation.results
		if mm_results == nil {
			mmDistinctActors.t.Fatal("No results are set for the StoreMock.DistinctActors")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmDistinctActors.funcDistinctActors != nil {
		return mmDistinctActors.funcDistinctActors(ctx, f)
	}
	mmDistinctActors.t.Fatalf("Unexpected call to StoreMock.DistinctActors. %v %v", ctx, f)
	return
}

// DistinctActorsAfterCounter returns a count of finished StoreMock.DistinctActors invocations
func (mmDistinctActors *StoreMock) DistinctActorsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDistinctActors.afterDistinctActorsCounter)
}

// DistinctActorsBeforeCounter returns a count of StoreMock.DistinctActors invocations
func (mmDistinctActors *StoreMock) DistinctActorsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDistinctActors.beforeDistinctActorsCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.DistinctActors.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDistinctActors *mStoreMockDistinctActors) Calls() []*StoreMockDistinctActorsParams {
	mmDistinctActors.mutex.RLock()

	argCopy := make([]*StoreMockDistinctActorsParams, len(mmDistinctActors.callArgs))
	copy(argCopy, mmDistinctActors.callArgs)

	mmDistinctActors.mutex.RUnlock()

	return argCopy
}

// MinimockDistinctActorsDone returns true if the count of the DistinctActors invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockDistinctActorsDone() bool {
	if m.DistinctActorsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DistinctActorsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DistinctActorsMock.invocationsDone()
}

// MinimockDistinctActorsInspect logs each unmet expectation
func (m *StoreMock) MinimockDistinctActorsInspect() {
	for _, e := range m.DistinctActorsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.DistinctActors at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDistinctActorsCounter := mm_atomic.LoadUint64(&m.afterDistinctActorsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DistinctActorsMock.defaultExpectation != nil && afterDistinctActorsCounter < 1 {
		if m.DistinctActorsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.DistinctActors at\n%s", m.DistinctActorsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.DistinctActors at\n%s with params: %#v", m.DistinctActorsMock.defaultExpectation.expectationOrigins.origin, *m.DistinctActorsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDistinctActors != nil && afterDistinctActorsCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.DistinctActors at\n%s", m.funcDistinctActorsOrigin)
	}

	if !m.DistinctActorsMock.invocationsDone() && afterDistinctActorsCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.DistinctActors at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DistinctActorsMock.expectedInvocations), m.DistinctActorsMock.expectedInvocationsOrigin, afterDistinctActorsCounter)
	}
}

type mStoreMockList struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockListExpectation
	expectations       []*StoreMockListExpectation

	callArgs []*StoreMockListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockListExpectation specifies expectation struct of the Store.List
type StoreMockListExpectation struct {
	mock               *StoreMock
	params             *StoreMockListParams
	paramPtrs          *StoreMockListParamPtrs
	expectationOrigins StoreMockListExpectationOrigins
	results            *StoreMockListResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockListParams contains parameters of the Store.List
type StoreMockListParams struct {
	ctx context.Context
	f   domain.Filter
}

// StoreMockListParamPtrs contains pointers to parameters of the Store.List
type StoreMockListParamPtrs struct {
	ctx *context.Context
	f   *domain.Filter
}

// StoreMockListResults contains results of the Store.List
type StoreMockListResults struct {
	ea1 []domain.Entry
	err error
}

// StoreMockListOrigins contains origins of expectations of the Store.List
type StoreMockListExpectationOrigins struct {
	origin    string
	originCtx string
	originF   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mStoreMockList) Optional() *mStoreMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for Store.List
func (mmList *mStoreMockList) Expect(ctx context.Context, f domain.Filter) *mStoreMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &StoreMockListParams{ctx, f}
	mmList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for Store.List
func (mmList *mStoreMockList) ExpectCtxParam1(ctx context.Context) *mStoreMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &StoreMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx
	mmList.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmList
}

// ExpectFParam2 sets up expected param f for Store.List
func (mmList *mStoreMockList) ExpectFParam2(f domain.Filter) *mStoreMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &StoreMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.f = &f
	mmList.defaultExpectation.expectationOrigins.originF = minimock.CallerInfo(1)

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the Store.List
func (mmList *mStoreMockList) Inspect(f func(ctx context.Context, f domain.Filter)) *mStoreMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for StoreMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by Store.List
func (mmList *mStoreMockList) Return(ea1 []domain.Entry, err error) *StoreMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &StoreMockListResults{ea1, err}
	mmList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// Set uses given function f to mock the Store.List method
func (mmList *mStoreMockList) Set(f func(ctx context.Context, f domain.Filter) (ea1 []domain.Entry, err error)) *StoreMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the Store.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the Store.List method")
	}

	mmList.mock.funcList = f
	mmList.mock.funcListOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// When sets expectation for the Store.List which will trigger the result defined by the following
// Then helper
func (mmList *mStoreMockList) When(ctx context.Context, f domain.Filter) *StoreMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	expectation := &StoreMockListExpectation{
		mock:               mmList.mock,
		params:             &StoreMockListParams{ctx, f},
		expectationOrigins: StoreMockListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up Store.List return parameters for the expectation previously defined by the When method
func (e *StoreMockListExpectation) Then(ea1 []domain.Entry, err error) *StoreMock {
	e.results = &StoreMockListResults{ea1, err}
	return e.mock
}

// Times sets number of times Store.List should be invoked
func (mmList *mStoreMockList) Times(n uint64) *mStoreMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of StoreMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	mmList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmList
}

func (mmList *mStoreMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements mm_service.Store
func (mmList *StoreMock) List(ctx context.Context, f domain.Filter) (ea1 []domain.Entry, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	mmList.t.Helper()

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx, f)
	}

	mm_params := StoreMockListParams{ctx, f}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ea1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := StoreMockListParams{ctx, f}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("StoreMock.List got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.f != nil && !minimock.Equal(*mm_want_ptrs.f, mm_got.f) {
				mmList.t.Errorf("StoreMock.List got unexpected parameter f, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originF, *mm_want_ptrs.f, mm_got.f, minimock.Diff(*mm_want_ptrs.f, mm_got.f))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("StoreMock.List got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmList.ListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the StoreMock.List")
		}
		return (*mm_results).ea1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx, f)
	}
	mmList.t.Fatalf("Unexpected call to StoreMock.List. %v %v", ctx, f)
	return
}

// ListAfterCounter returns a count of finished StoreMock.List invocations
func (mmList *StoreMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of StoreMock.List invocations
func (mmList *StoreMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mStoreMockList) Calls() []*StoreMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*StoreMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *StoreMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.List at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.List at\n%s", m.ListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.List at\n%s with params: %#v", m.ListMock.defaultExpectation.expectationOrigins.origin, *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.List at\n%s", m.funcListOrigin)
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.List at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), m.ListMock.expectedInvocationsOrigin, afterListCounter)
	}
}

type mStoreMockRecord struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockRecordExpectation
	expectations       []*StoreMockRecordExpectation

	callArgs []*StoreMockRecordParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockRecordExpectation specifies expectation struct of the Store.Record
type StoreMockRecordExpectation struct {
	mock               *StoreMock
	params             *StoreMockRecordParams
	paramPtrs          *StoreMockRecordParamPtrs
	expectationOrigins StoreMockRecordExpectationOrigins
	results            *StoreMockRecordResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockRecordParams contains parameters of the Store.Record
type StoreMockRecordParams struct {
	ctx context.Context
	e   domain.Entry
}

// StoreMockRecordParamPtrs contains pointers to parameters of the Store.Record
type StoreMockRecordParamPtrs struct {
	ctx *context.Context
	e   *domain.Entry
}

// StoreMockRecordResults contains results of the Store.Record
type StoreMockRecordResults struct {
	i1  int64
	err error
}

// StoreMockRecordOrigins contains origins of expectations of the Store.Record
type StoreMockRecordExpectationOrigins struct {
	origin    string
	originCtx string
	originE   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRecord *mStoreMockRecord) Optional() *mStoreMockRecord {
	mmRecord.optional = true
	return mmRecord
}

// Expect sets up expected params for Store.Record
func (mmRecord *mStoreMockRecord) Expect(ctx context.Context, e domain.Entry) *mStoreMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &StoreMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.paramPtrs != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by ExpectParams functions")
	}

	mmRecord.defaultExpectation.params = &StoreMockRecordParams{ctx, e}
	mmRecord.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRecord.expectations {
		if minimock.Equal(e.params, mmRecord.defaultExpectation.params) {
			mmRecord.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRecord.defaultExpectation.params)
		}
	}

	return mmRecord
}

// ExpectCtxParam1 sets up expected param ctx for Store.Record
func (mmRecord *mStoreMockRecord) ExpectCtxParam1(ctx context.Context) *mStoreMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &StoreMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.params != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Expect")
	}

	if mmRecord.defaultExpectation.paramPtrs == nil {
		mmRecord.defaultExpectation.paramPtrs = &StoreMockRecordParamPtrs{}
	}
	mmRecord.defaultExpectation.paramPtrs.ctx = &ctx
	mmRecord.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRecord
}

// ExpectEParam2 sets up expected param e for Store.Record
func (mmRecord *mStoreMockRecord) ExpectEParam2(e domain.Entry) *mStoreMockRecord {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &StoreMockRecordExpectation{}
	}

	if mmRecord.defaultExpectation.params != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Expect")
	}

	if mmRecord.defaultExpectation.paramPtrs == nil {
		mmRecord.defaultExpectation.paramPtrs = &StoreMockRecordParamPtrs{}
	}
	mmRecord.defaultExpectation.paramPtrs.e = &e
	mmRecord.defaultExpectation.expectationOrigins.originE = minimock.CallerInfo(1)

	return mmRecord
}

// Inspect accepts an inspector function that has same arguments as the Store.Record
func (mmRecord *mStoreMockRecord) Inspect(f func(ctx context.Context, e domain.Entry)) *mStoreMockRecord {
	if mmRecord.mock.inspectFuncRecord != nil {
		mmRecord.mock.t.Fatalf("Inspect function is already set for StoreMock.Record")
	}

	mmRecord.mock.inspectFuncRecord = f

	return mmRecord
}

// Return sets up results that will be returned by Store.Record
func (mmRecord *mStoreMockRecord) Return(i1 int64, err error) *StoreMock {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Set")
	}

	if mmRecord.defaultExpectation == nil {
		mmRecord.defaultExpectation = &StoreMockRecordExpectation{mock: mmRecord.mock}
	}
	mmRecord.defaultExpectation.results = &StoreMockRecordResults{i1, err}
	mmRecord.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRecord.mock
}

// Set uses given function f to mock the Store.Record method
func (mmRecord *mStoreMockRecord) Set(f func(ctx context.Context, e domain.Entry) (i1 int64, err error)) *StoreMock {
	if mmRecord.defaultExpectation != nil {
		mmRecord.mock.t.Fatalf("Default expectation is already set for the Store.Record method")
	}

	if len(mmRecord.expectations) > 0 {
		mmRecord.mock.t.Fatalf("Some expectations are already set for the Store.Record method")
	}

	mmRecord.mock.funcRecord = f
	mmRecord.mock.funcRecordOrigin = minimock.CallerInfo(1)
	return mmRecord.mock
}

// When sets expectation for the Store.Record which will trigger the result defined by the following
// Then helper
func (mmRecord *mStoreMockRecord) When(ctx context.Context, e domain.Entry) *StoreMockRecordExpectation {
	if mmRecord.mock.funcRecord != nil {
		mmRecord.mock.t.Fatalf("StoreMock.Record mock is already set by Set")
	}

	expectation := &StoreMockRecordExpectation{
		mock:               mmRecord.mock,
		params:             &StoreMockRecordParams{ctx, e},
		expectationOrigins: StoreMockRecordExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRecord.expectations = append(mmRecord.expectations, expectation)
	return expectation
}

// Then sets up Store.Record return parameters for the expectation previously defined by the When method
func (e *StoreMockRecordExpectation) Then(i1 int64, err error) *StoreMock {
	e.results = &StoreMockRecordResults{i1, err}
	return e.mock
}

// Times sets number of times Store.Record should be invoked
func (mmRecord *mStoreMockRecord) Times(n uint64) *mStoreMockRecord {
	if n == 0 {
		mmRecord.mock.t.Fatalf("Times of StoreMock.Record mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRecord.expectedInvocations, n)
	mmRecord.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRecord
}

func (mmRecord *mStoreMockRecord) invocationsDone() bool {
	if len(mmRecord.expectations) == 0 && mmRecord.defaultExpectation == nil && mmRecord.mock.funcRecord == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRecord.mock.afterRecordCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRecord.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Record implements mm_service.Store
func (mmRecord *StoreMock) Record(ctx context.Context, e domain.Entry) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmRecord.beforeRecordCounter, 1)
	defer mm_atomic.AddUint64(&mmRecord.afterRecordCounter, 1)

	mmRecord.t.Helper()

	if mmRecord.inspectFuncRecord != nil {
		mmRecord.inspectFuncRecord(ctx, e)
	}

	mm_params := StoreMockRecordParams{ctx, e}

	// Record call args
	mmRecord.RecordMock.mutex.Lock()
	mmRecord.RecordMock.callArgs = append(mmRecord.RecordMock.callArgs, &mm_params)
	mmRecord.RecordMock.mutex.Unlock()

	for _, e := range mmRecord.RecordMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmRecord.RecordMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRecord.RecordMock.defaultExpectation.Counter, 1)
		mm_want := mmRecord.RecordMock.defaultExpectation.params
		mm_want_ptrs := mmRecord.RecordMock.defaultExpectation.paramPtrs

		mm_got := StoreMockRecordParams{ctx, e}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRecord.t.Errorf("StoreMock.Record got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecord.RecordMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.e != nil && !minimock.Equal(*mm_want_ptrs.e, mm_got.e) {
				mmRecord.t.Errorf("StoreMock.Record got unexpected parameter e, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecord.RecordMock.defaultExpectation.expectationOrigins.originE, *mm_want_ptrs.e, mm_got.e, minimock.Diff(*mm_want_ptrs.e, mm_got.e))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRecord.t.Errorf("StoreMock.Record got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRecord.RecordMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRecord.RecordMock.defaultExpectation.results
		if mm_results == nil {
			mmRecord.t.Fatal("No results are set for the StoreMock.Record")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmRecord.funcRecord != nil {
		return mmRecord.funcRecord(ctx, e)
	}
	mmRecord.t.Fatalf("Unexpected call to StoreMock.Record. %v %v", ctx, e)
	return
}

// RecordAfterCounter returns a count of finished StoreMock.Record invocations
func (mmRecord *StoreMock) RecordAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecord.afterRecordCounter)
}

// RecordBeforeCounter returns a count of StoreMock.Record invocations
func (mmRecord *StoreMock) RecordBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecord.beforeRecordCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Record.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRecord *mStoreMockRecord) Calls() []*StoreMockRecordParams {
	mmRecord.mutex.RLock()

	argCopy := make([]*StoreMockRecordParams, len(mmRecord.callArgs))
	copy(argCopy, mmRecord.callArgs)

	mmRecord.mutex.RUnlock()

	return argCopy
}

// MinimockRecordDone returns true if the count of the Record invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockRecordDone() bool {
	if m.RecordMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RecordMock.invocationsDone()
}

// MinimockRecordInspect logs each unmet expectation
func (m *StoreMock) MinimockRecordInspect() {
	for _, e := range m.RecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Record at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRecordCounter := mm_atomic.LoadUint64(&m.afterRecordCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RecordMock.defaultExpectation != nil && afterRecordCounter < 1 {
		if m.RecordMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Record at\n%s", m.RecordMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Record at\n%s with params: %#v", m.RecordMock.defaultExpectation.expectationOrigins.origin, *m.RecordMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRecord != nil && afterRecordCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Record at\n%s", m.funcRecordOrigin)
	}

	if !m.RecordMock.invocationsDone() && afterRecordCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Record at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RecordMock.expectedInvocations), m.RecordMock.expectedInvocationsOrigin, afterRecordCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDistinctActorsInspect()

			m.MinimockListInspect()

			m.MinimockRecordInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDistinctActorsDone() &&
		m.MinimockListDone() &&
		m.MinimockRecordDone()
}
