// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/rosneft/backend/services/twofa-service/internal/service/twofa.Cipher -o cipher_mock.go -n CipherMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CipherMock implements mm_twofa.Cipher
type CipherMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDecrypt          func(ct []byte) (ba1 []byte, err error)
	funcDecryptOrigin    string
	inspectFuncDecrypt   func(ct []byte)
	afterDecryptCounter  uint64
	beforeDecryptCounter uint64
	DecryptMock          mCipherMockDecrypt

	funcEncrypt          func(plain []byte) (ba1 []byte, err error)
	funcEncryptOrigin    string
	inspectFuncEncrypt   func(plain []byte)
	afterEncryptCounter  uint64
	beforeEncryptCounter uint64
	EncryptMock          mCipherMockEncrypt
}

// NewCipherMock returns a mock for mm_twofa.Cipher
func NewCipherMock(t minimock.Tester) *CipherMock {
	m := &CipherMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DecryptMock = mCipherMockDecrypt{mock: m}
	m.DecryptMock.callArgs = []*CipherMockDecryptParams{}

	m.EncryptMock = mCipherMockEncrypt{mock: m}
	m.EncryptMock.callArgs = []*CipherMockEncryptParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCipherMockDecrypt struct {
	optional           bool
	mock               *CipherMock
	defaultExpectation *CipherMockDecryptExpectation
	expectations       []*CipherMockDecryptExpectation

	callArgs []*CipherMockDecryptParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CipherMockDecryptExpectation specifies expectation struct of the Cipher.Decrypt
type CipherMockDecryptExpectation struct {
	mock               *CipherMock
	params             *CipherMockDecryptParams
	paramPtrs          *CipherMockDecryptParamPtrs
	expectationOrigins CipherMockDecryptExpectationOrigins
	results            *CipherMockDecryptResults
	returnOrigin       string
	Counter            uint64
}

// CipherMockDecryptParams contains parameters of the Cipher.Decrypt
type CipherMockDecryptParams struct {
	ct []byte
}

// CipherMockDecryptParamPtrs contains pointers to parameters of the Cipher.Decrypt
type CipherMockDecryptParamPtrs struct {
	ct *[]byte
}

// CipherMockDecryptResults contains results of the Cipher.Decrypt
type CipherMockDecryptResults struct {
	ba1 []byte
	err error
}

// CipherMockDecryptOrigins contains origins of expectations of the Cipher.Decrypt
type CipherMockDecryptExpectationOrigins struct {
	origin   string
	originCt string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDecrypt *mCipherMockDecrypt) Optional() *mCipherMockDecrypt {
	mmDecrypt.optional = true
	return mmDecrypt
}

// Expect sets up expected params for Cipher.Decrypt
func (mmDecrypt *mCipherMockDecrypt) Expect(ct []byte) *mCipherMockDecrypt {
	if mmDecrypt.mock.funcDecrypt != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by Set")
	}

	if mmDecrypt.defaultExpectation == nil {
		mmDecrypt.defaultExpectation = &CipherMockDecryptExpectation{}
	}

	if mmDecrypt.defaultExpectation.paramPtrs != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by ExpectParams functions")
	}

	mmDecrypt.defaultExpectation.params = &CipherMockDecryptParams{ct}
	mmDecrypt.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDecrypt.expectations {
		if minimock.Equal(e.params, mmDecrypt.defaultExpectation.params) {
			mmDecrypt.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDecrypt.defaultExpectation.params)
		}
	}

	return mmDecrypt
}

// ExpectCtParam1 sets up expected param ct for Cipher.Decrypt
func (mmDecrypt *mCipherMockDecrypt) ExpectCtParam1(ct []byte) *mCipherMockDecrypt {
	if mmDecrypt.mock.funcDecrypt != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by Set")
	}

	if mmDecrypt.defaultExpectation == nil {
		mmDecrypt.defaultExpectation = &CipherMockDecryptExpectation{}
	}

	if mmDecrypt.defaultExpectation.params != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by Expect")
	}

	if mmDecrypt.defaultExpectation.paramPtrs == nil {
		mmDecrypt.defaultExpectation.paramPtrs = &CipherMockDecryptParamPtrs{}
	}
	mmDecrypt.defaultExpectation.paramPtrs.ct = &ct
	mmDecrypt.defaultExpectation.expectationOrigins.originCt = minimock.CallerInfo(1)

	return mmDecrypt
}

// Inspect accepts an inspector function that has same arguments as the Cipher.Decrypt
func (mmDecrypt *mCipherMockDecrypt) Inspect(f func(ct []byte)) *mCipherMockDecrypt {
	if mmDecrypt.mock.inspectFuncDecrypt != nil {
		mmDecrypt.mock.t.Fatalf("Inspect function is already set for CipherMock.Decrypt")
	}

	mmDecrypt.mock.inspectFuncDecrypt = f

	return mmDecrypt
}

// Return sets up results that will be returned by Cipher.Decrypt
func (mmDecrypt *mCipherMockDecrypt) Return(ba1 []byte, err error) *CipherMock {
	if mmDecrypt.mock.funcDecrypt != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by Set")
	}

	if mmDecrypt.defaultExpectation == nil {
		mmDecrypt.defaultExpectation = &CipherMockDecryptExpectation{mock: mmDecrypt.mock}
	}
	mmDecrypt.defaultExpectation.results = &CipherMockDecryptResults{ba1, err}
	mmDecrypt.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDecrypt.mock
}

// Set uses given function f to mock the Cipher.Decrypt method
func (mmDecrypt *mCipherMockDecrypt) Set(f func(ct []byte) (ba1 []byte, err error)) *CipherMock {
	if mmDecrypt.defaultExpectation != nil {
		mmDecrypt.mock.t.Fatalf("Default expectation is already set for the Cipher.Decrypt method")
	}

	if len(mmDecrypt.expectations) > 0 {
		mmDecrypt.mock.t.Fatalf("Some expectations are already set for the Cipher.Decrypt method")
	}

	mmDecrypt.mock.funcDecrypt = f
	mmDecrypt.mock.funcDecryptOrigin = minimock.CallerInfo(1)
	return mmDecrypt.mock
}

// When sets expectation for the Cipher.Decrypt which will trigger the result defined by the following
// Then helper
func (mmDecrypt *mCipherMockDecrypt) When(ct []byte) *CipherMockDecryptExpectation {
	if mmDecrypt.mock.funcDecrypt != nil {
		mmDecrypt.mock.t.Fatalf("CipherMock.Decrypt mock is already set by Set")
	}

	expectation := &CipherMockDecryptExpectation{
		mock:               mmDecrypt.mock,
		params:             &CipherMockDecryptParams{ct},
		expectationOrigins: CipherMockDecryptExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDecrypt.expectations = append(mmDecrypt.expectations, expectation)
	return expectation
}

// Then sets up Cipher.Decrypt return parameters for the expectation previously defined by the When method
func (e *CipherMockDecryptExpectation) Then(ba1 []byte, err error) *CipherMock {
	e.results = &CipherMockDecryptResults{ba1, err}
	return e.mock
}

// Times sets number of times Cipher.Decrypt should be invoked
func (mmDecrypt *mCipherMockDecrypt) Times(n uint64) *mCipherMockDecrypt {
	if n == 0 {
		mmDecrypt.mock.t.Fatalf("Times of CipherMock.Decrypt mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDecrypt.expectedInvocations, n)
	mmDecrypt.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDecrypt
}

func (mmDecrypt *mCipherMockDecrypt) invocationsDone() bool {
	if len(mmDecrypt.expectations) == 0 && mmDecrypt.defaultExpectation == nil && mmDecrypt.mock.funcDecrypt == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDecrypt.mock.afterDecryptCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDecrypt.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Decrypt implements mm_twofa.Cipher
func (mmDecrypt *CipherMock) Decrypt(ct []byte) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmDecrypt.beforeDecryptCounter, 1)
	defer mm_atomic.AddUint64(&mmDecrypt.afterDecryptCounter, 1)

	mmDecrypt.t.Helper()

	if mmDecrypt.inspectFuncDecrypt != nil {
		mmDecrypt.inspectFuncDecrypt(ct)
	}

	mm_params := CipherMockDecryptParams{ct}

	// Record call args
	mmDecrypt.DecryptMock.mutex.Lock()
	mmDecrypt.DecryptMock.callArgs = append(mmDecrypt.DecryptMock.callArgs, &mm_params)
	mmDecrypt.DecryptMock.mutex.Unlock()

	for _, e := range mmDecrypt.DecryptMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmDecrypt.DecryptMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDecrypt.DecryptMock.defaultExpectation.Counter, 1)
		mm_want := mmDecrypt.DecryptMock.defaultExpectation.params
		mm_want_ptrs := mmDecrypt.DecryptMock.defaultExpectation.paramPtrs

		mm_got := CipherMockDecryptParams{ct}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ct != nil && !minimock.Equal(*mm_want_ptrs.ct, mm_got.ct) {
				mmDecrypt.t.Errorf("CipherMock.Decrypt got unexpected parameter ct, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDecrypt.DecryptMock.defaultExpectation.expectationOrigins.originCt, *mm_want_ptrs.ct, mm_got.ct, minimock.Diff(*mm_want_ptrs.ct, mm_got.ct))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDecrypt.t.Errorf("CipherMock.Decrypt got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDecrypt.DecryptMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDecrypt.DecryptMock.defaultExpectation.results
		if mm_results == nil {
			mmDecrypt.t.Fatal("No results are set for the CipherMock.Decrypt")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmDecrypt.funcDecrypt != nil {
		return mmDecrypt.funcDecrypt(ct)
	}
	mmDecrypt.t.Fatalf("Unexpected call to CipherMock.Decrypt. %v", ct)
	return
}

// DecryptAfterCounter returns a count of finished CipherMock.Decrypt invocations
func (mmDecrypt *CipherMock) DecryptAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDecrypt.afterDecryptCounter)
}

// DecryptBeforeCounter returns a count of CipherMock.Decrypt invocations
func (mmDecrypt *CipherMock) DecryptBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDecrypt.beforeDecryptCounter)
}

// Calls returns a list of arguments used in each call to CipherMock.Decrypt.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDecrypt *mCipherMockDecrypt) Calls() []*CipherMockDecryptParams {
	mmDecrypt.mutex.RLock()

	argCopy := make([]*CipherMockDecryptParams, len(mmDecrypt.callArgs))
	copy(argCopy, mmDecrypt.callArgs)

	mmDecrypt.mutex.RUnlock()

	return argCopy
}

// MinimockDecryptDone returns true if the count of the Decrypt invocations corresponds
// the number of defined expectations
func (m *CipherMock) MinimockDecryptDone() bool {
	if m.DecryptMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DecryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DecryptMock.invocationsDone()
}

// MinimockDecryptInspect logs each unmet expectation
func (m *CipherMock) MinimockDecryptInspect() {
	for _, e := range m.DecryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CipherMock.Decrypt at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDecryptCounter := mm_atomic.LoadUint64(&m.afterDecryptCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DecryptMock.defaultExpectation != nil && afterDecryptCounter < 1 {
		if m.DecryptMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CipherMock.Decrypt at\n%s", m.DecryptMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CipherMock.Decrypt at\n%s with params: %#v", m.DecryptMock.defaultExpectation.expectationOrigins.origin, *m.DecryptMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDecrypt != nil && afterDecryptCounter < 1 {
		m.t.Errorf("Expected call to CipherMock.Decrypt at\n%s", m.funcDecryptOrigin)
	}

	if !m.DecryptMock.invocationsDone() && afterDecryptCounter > 0 {
		m.t.Errorf("Expected %d calls to CipherMock.Decrypt at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DecryptMock.expectedInvocations), m.DecryptMock.expectedInvocationsOrigin, afterDecryptCounter)
	}
}

type mCipherMockEncrypt struct {
	optional           bool
	mock               *CipherMock
	defaultExpectation *CipherMockEncryptExpectation
	expectations       []*CipherMockEncryptExpectation

	callArgs []*CipherMockEncryptParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CipherMockEncryptExpectation specifies expectation struct of the Cipher.Encrypt
type CipherMockEncryptExpectation struct {
	mock               *CipherMock
	params             *CipherMockEncryptParams
	paramPtrs          *CipherMockEncryptParamPtrs
	expectationOrigins CipherMockEncryptExpectationOrigins
	results            *CipherMockEncryptResults
	returnOrigin       string
	Counter            uint64
}

// CipherMockEncryptParams contains parameters of the Cipher.Encrypt
type CipherMockEncryptParams struct {
	plain []byte
}

// CipherMockEncryptParamPtrs contains pointers to parameters of the Cipher.Encrypt
type CipherMockEncryptParamPtrs struct {
	plain *[]byte
}

// CipherMockEncryptResults contains results of the Cipher.Encrypt
type CipherMockEncryptResults struct {
	ba1 []byte
	err error
}

// CipherMockEncryptOrigins contains origins of expectations of the Cipher.Encrypt
type CipherMockEncryptExpectationOrigins struct {
	origin      string
	originPlain string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmEncrypt *mCipherMockEncrypt) Optional() *mCipherMockEncrypt {
	mmEncrypt.optional = true
	return mmEncrypt
}

// Expect sets up expected params for Cipher.Encrypt
func (mmEncrypt *mCipherMockEncrypt) Expect(plain []byte) *mCipherMockEncrypt {
	if mmEncrypt.mock.funcEncrypt != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by Set")
	}

	if mmEncrypt.defaultExpectation == nil {
		mmEncrypt.defaultExpectation = &CipherMockEncryptExpectation{}
	}

	if mmEncrypt.defaultExpectation.paramPtrs != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by ExpectParams functions")
	}

	mmEncrypt.defaultExpectation.params = &CipherMockEncryptParams{plain}
	mmEncrypt.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmEncrypt.expectations {
		if minimock.Equal(e.params, mmEncrypt.defaultExpectation.params) {
			mmEncrypt.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmEncrypt.defaultExpectation.params)
		}
	}

	return mmEncrypt
}

// ExpectPlainParam1 sets up expected param plain for Cipher.Encrypt
func (mmEncrypt *mCipherMockEncrypt) ExpectPlainParam1(plain []byte) *mCipherMockEncrypt {
	if mmEncrypt.mock.funcEncrypt != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by Set")
	}

	if mmEncrypt.defaultExpectation == nil {
		mmEncrypt.defaultExpectation = &CipherMockEncryptExpectation{}
	}

	if mmEncrypt.defaultExpectation.params != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by Expect")
	}

	if mmEncrypt.defaultExpectation.paramPtrs == nil {
		mmEncrypt.defaultExpectation.paramPtrs = &CipherMockEncryptParamPtrs{}
	}
	mmEncrypt.defaultExpectation.paramPtrs.plain = &plain
	mmEncrypt.defaultExpectation.expectationOrigins.originPlain = minimock.CallerInfo(1)

	return mmEncrypt
}

// Inspect accepts an inspector function that has same arguments as the Cipher.Encrypt
func (mmEncrypt *mCipherMockEncrypt) Inspect(f func(plain []byte)) *mCipherMockEncrypt {
	if mmEncrypt.mock.inspectFuncEncrypt != nil {
		mmEncrypt.mock.t.Fatalf("Inspect function is already set for CipherMock.Encrypt")
	}

	mmEncrypt.mock.inspectFuncEncrypt = f

	return mmEncrypt
}

// Return sets up results that will be returned by Cipher.Encrypt
func (mmEncrypt *mCipherMockEncrypt) Return(ba1 []byte, err error) *CipherMock {
	if mmEncrypt.mock.funcEncrypt != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by Set")
	}

	if mmEncrypt.defaultExpectation == nil {
		mmEncrypt.defaultExpectation = &CipherMockEncryptExpectation{mock: mmEncrypt.mock}
	}
	mmEncrypt.defaultExpectation.results = &CipherMockEncryptResults{ba1, err}
	mmEncrypt.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmEncrypt.mock
}

// Set uses given function f to mock the Cipher.Encrypt method
func (mmEncrypt *mCipherMockEncrypt) Set(f func(plain []byte) (ba1 []byte, err error)) *CipherMock {
	if mmEncrypt.defaultExpectation != nil {
		mmEncrypt.mock.t.Fatalf("Default expectation is already set for the Cipher.Encrypt method")
	}

	if len(mmEncrypt.expectations) > 0 {
		mmEncrypt.mock.t.Fatalf("Some expectations are already set for the Cipher.Encrypt method")
	}

	mmEncrypt.mock.funcEncrypt = f
	mmEncrypt.mock.funcEncryptOrigin = minimock.CallerInfo(1)
	return mmEncrypt.mock
}

// When sets expectation for the Cipher.Encrypt which will trigger the result defined by the following
// Then helper
func (mmEncrypt *mCipherMockEncrypt) When(plain []byte) *CipherMockEncryptExpectation {
	if mmEncrypt.mock.funcEncrypt != nil {
		mmEncrypt.mock.t.Fatalf("CipherMock.Encrypt mock is already set by Set")
	}

	expectation := &CipherMockEncryptExpectation{
		mock:               mmEncrypt.mock,
		params:             &CipherMockEncryptParams{plain},
		expectationOrigins: CipherMockEncryptExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmEncrypt.expectations = append(mmEncrypt.expectations, expectation)
	return expectation
}

// Then sets up Cipher.Encrypt return parameters for the expectation previously defined by the When method
func (e *CipherMockEncryptExpectation) Then(ba1 []byte, err error) *CipherMock {
	e.results = &CipherMockEncryptResults{ba1, err}
	return e.mock
}

// Times sets number of times Cipher.Encrypt should be invoked
func (mmEncrypt *mCipherMockEncrypt) Times(n uint64) *mCipherMockEncrypt {
	if n == 0 {
		mmEncrypt.mock.t.Fatalf("Times of CipherMock.Encrypt mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmEncrypt.expectedInvocations, n)
	mmEncrypt.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmEncrypt
}

func (mmEncrypt *mCipherMockEncrypt) invocationsDone() bool {
	if len(mmEncrypt.expectations) == 0 && mmEncrypt.defaultExpectation == nil && mmEncrypt.mock.funcEncrypt == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmEncrypt.mock.afterEncryptCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmEncrypt.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Encrypt implements mm_twofa.Cipher
func (mmEncrypt *CipherMock) Encrypt(plain []byte) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmEncrypt.beforeEncryptCounter, 1)
	defer mm_atomic.AddUint64(&mmEncrypt.afterEncryptCounter, 1)

	mmEncrypt.t.Helper()

	if mmEncrypt.inspectFuncEncrypt != nil {
		mmEncrypt.inspectFuncEncrypt(plain)
	}

	mm_params := CipherMockEncryptParams{plain}

	// Record call args
	mmEncrypt.EncryptMock.mutex.Lock()
	mmEncrypt.EncryptMock.callArgs = append(mmEncrypt.EncryptMock.callArgs, &mm_params)
	mmEncrypt.EncryptMock.mutex.Unlock()

	for _, e := range mmEncrypt.EncryptMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmEncrypt.EncryptMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEncrypt.EncryptMock.defaultExpectation.Counter, 1)
		mm_want := mmEncrypt.EncryptMock.defaultExpectation.params
		mm_want_ptrs := mmEncrypt.EncryptMock.defaultExpectation.paramPtrs

		mm_got := CipherMockEncryptParams{plain}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.plain != nil && !minimock.Equal(*mm_want_ptrs.plain, mm_got.plain) {
				mmEncrypt.t.Errorf("CipherMock.Encrypt got unexpected parameter plain, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEncrypt.EncryptMock.defaultExpectation.expectationOrigins.originPlain, *mm_want_ptrs.plain, mm_got.plain, minimock.Diff(*mm_want_ptrs.plain, mm_got.plain))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmEncrypt.t.Errorf("CipherMock.Encrypt got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmEncrypt.EncryptMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmEncrypt.EncryptMock.defaultExpectation.results
		if mm_results == nil {
			mmEncrypt.t.Fatal("No results are set for the CipherMock.Encrypt")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmEncrypt.funcEncrypt != nil {
		return mmEncrypt.funcEncrypt(plain)
	}
	mmEncrypt.t.Fatalf("Unexpected call to CipherMock.Encrypt. %v", plain)
	return
}

// EncryptAfterCounter returns a count of finished CipherMock.Encrypt invocations
func (mmEncrypt *CipherMock) EncryptAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEncrypt.afterEncryptCounter)
}

// EncryptBeforeCounter returns a count of CipherMock.Encrypt invocations
func (mmEncrypt *CipherMock) EncryptBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEncrypt.beforeEncryptCounter)
}

// Calls returns a list of arguments used in each call to CipherMock.Encrypt.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmEncrypt *mCipherMockEncrypt) Calls() []*CipherMockEncryptParams {
	mmEncrypt.mutex.RLock()

	argCopy := make([]*CipherMockEncryptParams, len(mmEncrypt.callArgs))
	copy(argCopy, mmEncrypt.callArgs)

	mmEncrypt.mutex.RUnlock()

	return argCopy
}

// MinimockEncryptDone returns true if the count of the Encrypt invocations corresponds
// the number of defined expectations
func (m *CipherMock) MinimockEncryptDone() bool {
	if m.EncryptMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.EncryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.EncryptMock.invocationsDone()
}

// MinimockEncryptInspect logs each unmet expectation
func (m *CipherMock) MinimockEncryptInspect() {
	for _, e := range m.EncryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CipherMock.Encrypt at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterEncryptCounter := mm_atomic.LoadUint64(&m.afterEncryptCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.EncryptMock.defaultExpectation != nil && afterEncryptCounter < 1 {
		if m.EncryptMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CipherMock.Encrypt at\n%s", m.EncryptMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CipherMock.Encrypt at\n%s with params: %#v", m.EncryptMock.defaultExpectation.expectationOrigins.origin, *m.EncryptMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEncrypt != nil && afterEncryptCounter < 1 {
		m.t.Errorf("Expected call to CipherMock.Encrypt at\n%s", m.funcEncryptOrigin)
	}

	if !m.EncryptMock.invocationsDone() && afterEncryptCounter > 0 {
		m.t.Errorf("Expected %d calls to CipherMock.Encrypt at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.EncryptMock.expectedInvocations), m.EncryptMock.expectedInvocationsOrigin, afterEncryptCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CipherMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDecryptInspect()

			m.MinimockEncryptInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CipherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CipherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDecryptDone() &&
		m.MinimockEncryptDone()
}
