// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/rosneft/backend/services/auth-service/internal/service/roles.Store -o store_mock.go -n StoreMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/rosneft/backend/services/auth-service/internal/domain"
)

// StoreMock implements mm_roles.Store
type StoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, r domain.Role) (r1 domain.Role, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, r domain.Role)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mStoreMockCreate

	funcDelete          func(ctx context.Context, slug string) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, slug string)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mStoreMockDelete

	funcList          func(ctx context.Context) (ra1 []domain.Role, err error)
	funcListOrigin    string
	inspectFuncList   func(ctx context.Context)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mStoreMockList

	funcSetPermissions          func(ctx context.Context, slug string, permSlugs []string) (r1 domain.Role, err error)
	funcSetPermissionsOrigin    string
	inspectFuncSetPermissions   func(ctx context.Context, slug string, permSlugs []string)
	afterSetPermissionsCounter  uint64
	beforeSetPermissionsCounter uint64
	SetPermissionsMock          mStoreMockSetPermissions

	funcUpdateTitle          func(ctx context.Context, slug string, title string) (r1 domain.Role, err error)
	funcUpdateTitleOrigin    string
	inspectFuncUpdateTitle   func(ctx context.Context, slug string, title string)
	afterUpdateTitleCounter  uint64
	beforeUpdateTitleCounter uint64
	UpdateTitleMock          mStoreMockUpdateTitle
}

// NewStoreMock returns a mock for mm_roles.Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mStoreMockCreate{mock: m}
	m.CreateMock.callArgs = []*StoreMockCreateParams{}

	m.DeleteMock = mStoreMockDelete{mock: m}
	m.DeleteMock.callArgs = []*StoreMockDeleteParams{}

	m.ListMock = mStoreMockList{mock: m}
	m.ListMock.callArgs = []*StoreMockListParams{}

	m.SetPermissionsMock = mStoreMockSetPermissions{mock: m}
	m.SetPermissionsMock.callArgs = []*StoreMockSetPermissionsParams{}

	m.UpdateTitleMock = mStoreMockUpdateTitle{mock: m}
	m.UpdateTitleMock.callArgs = []*StoreMockUpdateTitleParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreMockCreate struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockCreateExpectation
	expectations       []*StoreMockCreateExpectation

	callArgs []*StoreMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockCreateExpectation specifies expectation struct of the Store.Create
type StoreMockCreateExpectation struct {
	mock               *StoreMock
	params             *StoreMockCreateParams
	paramPtrs          *StoreMockCreateParamPtrs
	expectationOrigins StoreMockCreateExpectationOrigins
	results            *StoreMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockCreateParams contains parameters of the Store.Create
type StoreMockCreateParams struct {
	ctx context.Context
	r   domain.Role
}

// StoreMockCreateParamPtrs contains pointers to parameters of the Store.Create
type StoreMockCreateParamPtrs struct {
	ctx *context.Context
	r   *domain.Role
}

// StoreMockCreateResults contains results of the Store.Create
type StoreMockCreateResults struct {
	r1  domain.Role
	err error
}

// StoreMockCreateOrigins contains origins of expectations of the Store.Create
type StoreMockCreateExpectationOrigins struct {
	origin    string
	originCtx string
	originR   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mStoreMockCreate) Optional() *mStoreMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for Store.Create
func (mmCreate *mStoreMockCreate) Expect(ctx context.Context, r domain.Role) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &StoreMockCreateParams{ctx, r}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for Store.Create
func (mmCreate *mStoreMockCreate) ExpectCtxParam1(ctx context.Context) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectRParam2 sets up expected param r for Store.Create
func (mmCreate *mStoreMockCreate) ExpectRParam2(r domain.Role) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.r = &r
	mmCreate.defaultExpectation.expectationOrigins.originR = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the Store.Create
func (mmCreate *mStoreMockCreate) Inspect(f func(ctx context.Context, r domain.Role)) *mStoreMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for StoreMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by Store.Create
func (mmCreate *mStoreMockCreate) Return(r1 domain.Role, err error) *StoreMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &StoreMockCreateResults{r1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the Store.Create method
func (mmCreate *mStoreMockCreate) Set(f func(ctx context.Context, r domain.Role) (r1 domain.Role, err error)) *StoreMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the Store.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the Store.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the Store.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mStoreMockCreate) When(ctx context.Context, r domain.Role) *StoreMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	expectation := &StoreMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &StoreMockCreateParams{ctx, r},
		expectationOrigins: StoreMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up Store.Create return parameters for the expectation previously defined by the When method
func (e *StoreMockCreateExpectation) Then(r1 domain.Role, err error) *StoreMock {
	e.results = &StoreMockCreateResults{r1, err}
	return e.mock
}

// Times sets number of times Store.Create should be invoked
func (mmCreate *mStoreMockCreate) Times(n uint64) *mStoreMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of StoreMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mStoreMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_roles.Store
func (mmCreate *StoreMock) Create(ctx context.Context, r domain.Role) (r1 domain.Role, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, r)
	}

	mm_params := StoreMockCreateParams{ctx, r}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := StoreMockCreateParams{ctx, r}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.r != nil && !minimock.Equal(*mm_want_ptrs.r, mm_got.r) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter r, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originR, *mm_want_ptrs.r, mm_got.r, minimock.Diff(*mm_want_ptrs.r, mm_got.r))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("StoreMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the StoreMock.Create")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, r)
	}
	mmCreate.t.Fatalf("Unexpected call to StoreMock.Create. %v %v", ctx, r)
	return
}

// CreateAfterCounter returns a count of finished StoreMock.Create invocations
func (mmCreate *StoreMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of StoreMock.Create invocations
func (mmCreate *StoreMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mStoreMockCreate) Calls() []*StoreMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*StoreMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *StoreMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mStoreMockDelete struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockDeleteExpectation
	expectations       []*StoreMockDeleteExpectation

	callArgs []*StoreMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockDeleteExpectation specifies expectation struct of the Store.Delete
type StoreMockDeleteExpectation struct {
	mock               *StoreMock
	params             *StoreMockDeleteParams
	paramPtrs          *StoreMockDeleteParamPtrs
	expectationOrigins StoreMockDeleteExpectationOrigins
	results            *StoreMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockDeleteParams contains parameters of the Store.Delete
type StoreMockDeleteParams struct {
	ctx  context.Context
	slug string
}

// StoreMockDeleteParamPtrs contains pointers to parameters of the Store.Delete
type StoreMockDeleteParamPtrs struct {
	ctx  *context.Context
	slug *string
}

// StoreMockDeleteResults contains results of the Store.Delete
type StoreMockDeleteResults struct {
	err error
}

// StoreMockDeleteOrigins contains origins of expectations of the Store.Delete
type StoreMockDeleteExpectationOrigins struct {
	origin     string
	originCtx  string
	originSlug string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mStoreMockDelete) Optional() *mStoreMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for Store.Delete
func (mmDelete *mStoreMockDelete) Expect(ctx context.Context, slug string) *mStoreMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StoreMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &StoreMockDeleteParams{ctx, slug}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for Store.Delete
func (mmDelete *mStoreMockDelete) ExpectCtxParam1(ctx context.Context) *mStoreMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StoreMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &StoreMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectSlugParam2 sets up expected param slug for Store.Delete
func (mmDelete *mStoreMockDelete) ExpectSlugParam2(slug string) *mStoreMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StoreMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &StoreMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.slug = &slug
	mmDelete.defaultExpectation.expectationOrigins.originSlug = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the Store.Delete
func (mmDelete *mStoreMockDelete) Inspect(f func(ctx context.Context, slug string)) *mStoreMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for StoreMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by Store.Delete
func (mmDelete *mStoreMockDelete) Return(err error) *StoreMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StoreMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &StoreMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the Store.Delete method
func (mmDelete *mStoreMockDelete) Set(f func(ctx context.Context, slug string) (err error)) *StoreMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the Store.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the Store.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the Store.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mStoreMockDelete) When(ctx context.Context, slug string) *StoreMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StoreMock.Delete mock is already set by Set")
	}

	expectation := &StoreMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &StoreMockDeleteParams{ctx, slug},
		expectationOrigins: StoreMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up Store.Delete return parameters for the expectation previously defined by the When method
func (e *StoreMockDeleteExpectation) Then(err error) *StoreMock {
	e.results = &StoreMockDeleteResults{err}
	return e.mock
}

// Times sets number of times Store.Delete should be invoked
func (mmDelete *mStoreMockDelete) Times(n uint64) *mStoreMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of StoreMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mStoreMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_roles.Store
func (mmDelete *StoreMock) Delete(ctx context.Context, slug string) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, slug)
	}

	mm_params := StoreMockDeleteParams{ctx, slug}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := StoreMockDeleteParams{ctx, slug}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("StoreMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.slug != nil && !minimock.Equal(*mm_want_ptrs.slug, mm_got.slug) {
				mmDelete.t.Errorf("StoreMock.Delete got unexpected parameter slug, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originSlug, *mm_want_ptrs.slug, mm_got.slug, minimock.Diff(*mm_want_ptrs.slug, mm_got.slug))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("StoreMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the StoreMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, slug)
	}
	mmDelete.t.Fatalf("Unexpected call to StoreMock.Delete. %v %v", ctx, slug)
	return
}

// DeleteAfterCounter returns a count of finished StoreMock.Delete invocations
func (mmDelete *StoreMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of StoreMock.Delete invocations
func (mmDelete *StoreMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mStoreMockDelete) Calls() []*StoreMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*StoreMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *StoreMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mStoreMockList struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockListExpectation
	expectations       []*StoreMockListExpectation

	callArgs []*StoreMockListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockListExpectation specifies expectation struct of the Store.List
type StoreMockListExpectation struct {
	mock               *StoreMock
	params             *StoreMockListParams
	paramPtrs          *StoreMockListParamPtrs
	expectationOrigins StoreMockListExpectationOrigins
	results            *StoreMockListResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockListParams contains parameters of the Store.List
type StoreMockListParams struct {
	ctx context.Context
}

// StoreMockListParamPtrs contains pointers to parameters of the Store.List
type StoreMockListParamPtrs struct {
	ctx *context.Context
}

// StoreMockListResults contains results of the Store.List
type StoreMockListResults struct {
	ra1 []domain.Role
	err error
}

// StoreMockListOrigins contains origins of expectations of the Store.List
type StoreMockListExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mStoreMockList) Optional() *mStoreMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for Store.List
func (mmList *mStoreMockList) Expect(ctx context.Context) *mStoreMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &StoreMockListParams{ctx}
	mmList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for Store.List
func (mmList *mStoreMockList) ExpectCtxParam1(ctx context.Context) *mStoreMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &StoreMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx
	mmList.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the Store.List
func (mmList *mStoreMockList) Inspect(f func(ctx context.Context)) *mStoreMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for StoreMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by Store.List
func (mmList *mStoreMockList) Return(ra1 []domain.Role, err error) *StoreMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &StoreMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &StoreMockListResults{ra1, err}
	mmList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// Set uses given function f to mock the Store.List method
func (mmList *mStoreMockList) Set(f func(ctx context.Context) (ra1 []domain.Role, err error)) *StoreMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the Store.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the Store.List method")
	}

	mmList.mock.funcList = f
	mmList.mock.funcListOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// When sets expectation for the Store.List which will trigger the result defined by the following
// Then helper
func (mmList *mStoreMockList) When(ctx context.Context) *StoreMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("StoreMock.List mock is already set by Set")
	}

	expectation := &StoreMockListExpectation{
		mock:               mmList.mock,
		params:             &StoreMockListParams{ctx},
		expectationOrigins: StoreMockListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up Store.List return parameters for the expectation previously defined by the When method
func (e *StoreMockListExpectation) Then(ra1 []domain.Role, err error) *StoreMock {
	e.results = &StoreMockListResults{ra1, err}
	return e.mock
}

// Times sets number of times Store.List should be invoked
func (mmList *mStoreMockList) Times(n uint64) *mStoreMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of StoreMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	mmList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmList
}

func (mmList *mStoreMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements mm_roles.Store
func (mmList *StoreMock) List(ctx context.Context) (ra1 []domain.Role, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	mmList.t.Helper()

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx)
	}

	mm_params := StoreMockListParams{ctx}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ra1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := StoreMockListParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("StoreMock.List got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("StoreMock.List got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmList.ListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the StoreMock.List")
		}
		return (*mm_results).ra1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx)
	}
	mmList.t.Fatalf("Unexpected call to StoreMock.List. %v", ctx)
	return
}

// ListAfterCounter returns a count of finished StoreMock.List invocations
func (mmList *StoreMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of StoreMock.List invocations
func (mmList *StoreMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mStoreMockList) Calls() []*StoreMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*StoreMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *StoreMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.List at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.List at\n%s", m.ListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.List at\n%s with params: %#v", m.ListMock.defaultExpectation.expectationOrigins.origin, *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.List at\n%s", m.funcListOrigin)
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.List at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), m.ListMock.expectedInvocationsOrigin, afterListCounter)
	}
}

type mStoreMockSetPermissions struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockSetPermissionsExpectation
	expectations       []*StoreMockSetPermissionsExpectation

	callArgs []*StoreMockSetPermissionsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockSetPermissionsExpectation specifies expectation struct of the Store.SetPermissions
type StoreMockSetPermissionsExpectation struct {
	mock               *StoreMock
	params             *StoreMockSetPermissionsParams
	paramPtrs          *StoreMockSetPermissionsParamPtrs
	expectationOrigins StoreMockSetPermissionsExpectationOrigins
	results            *StoreMockSetPermissionsResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockSetPermissionsParams contains parameters of the Store.SetPermissions
type StoreMockSetPermissionsParams struct {
	ctx       context.Context
	slug      string
	permSlugs []string
}

// StoreMockSetPermissionsParamPtrs contains pointers to parameters of the Store.SetPermissions
type StoreMockSetPermissionsParamPtrs struct {
	ctx       *context.Context
	slug      *string
	permSlugs *[]string
}

// StoreMockSetPermissionsResults contains results of the Store.SetPermissions
type StoreMockSetPermissionsResults struct {
	r1  domain.Role
	err error
}

// StoreMockSetPermissionsOrigins contains origins of expectations of the Store.SetPermissions
type StoreMockSetPermissionsExpectationOrigins struct {
	origin          string
	originCtx       string
	originSlug      string
	originPermSlugs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetPermissions *mStoreMockSetPermissions) Optional() *mStoreMockSetPermissions {
	mmSetPermissions.optional = true
	return mmSetPermissions
}

// Expect sets up expected params for Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) Expect(ctx context.Context, slug string, permSlugs []string) *mStoreMockSetPermissions {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	if mmSetPermissions.defaultExpectation == nil {
		mmSetPermissions.defaultExpectation = &StoreMockSetPermissionsExpectation{}
	}

	if mmSetPermissions.defaultExpectation.paramPtrs != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by ExpectParams functions")
	}

	mmSetPermissions.defaultExpectation.params = &StoreMockSetPermissionsParams{ctx, slug, permSlugs}
	mmSetPermissions.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetPermissions.expectations {
		if minimock.Equal(e.params, mmSetPermissions.defaultExpectation.params) {
			mmSetPermissions.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetPermissions.defaultExpectation.params)
		}
	}

	return mmSetPermissions
}

// ExpectCtxParam1 sets up expected param ctx for Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) ExpectCtxParam1(ctx context.Context) *mStoreMockSetPermissions {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	if mmSetPermissions.defaultExpectation == nil {
		mmSetPermissions.defaultExpectation = &StoreMockSetPermissionsExpectation{}
	}

	if mmSetPermissions.defaultExpectation.params != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Expect")
	}

	if mmSetPermissions.defaultExpectation.paramPtrs == nil {
		mmSetPermissions.defaultExpectation.paramPtrs = &StoreMockSetPermissionsParamPtrs{}
	}
	mmSetPermissions.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetPermissions.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetPermissions
}

// ExpectSlugParam2 sets up expected param slug for Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) ExpectSlugParam2(slug string) *mStoreMockSetPermissions {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	if mmSetPermissions.defaultExpectation == nil {
		mmSetPermissions.defaultExpectation = &StoreMockSetPermissionsExpectation{}
	}

	if mmSetPermissions.defaultExpectation.params != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Expect")
	}

	if mmSetPermissions.defaultExpectation.paramPtrs == nil {
		mmSetPermissions.defaultExpectation.paramPtrs = &StoreMockSetPermissionsParamPtrs{}
	}
	mmSetPermissions.defaultExpectation.paramPtrs.slug = &slug
	mmSetPermissions.defaultExpectation.expectationOrigins.originSlug = minimock.CallerInfo(1)

	return mmSetPermissions
}

// ExpectPermSlugsParam3 sets up expected param permSlugs for Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) ExpectPermSlugsParam3(permSlugs []string) *mStoreMockSetPermissions {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	if mmSetPermissions.defaultExpectation == nil {
		mmSetPermissions.defaultExpectation = &StoreMockSetPermissionsExpectation{}
	}

	if mmSetPermissions.defaultExpectation.params != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Expect")
	}

	if mmSetPermissions.defaultExpectation.paramPtrs == nil {
		mmSetPermissions.defaultExpectation.paramPtrs = &StoreMockSetPermissionsParamPtrs{}
	}
	mmSetPermissions.defaultExpectation.paramPtrs.permSlugs = &permSlugs
	mmSetPermissions.defaultExpectation.expectationOrigins.originPermSlugs = minimock.CallerInfo(1)

	return mmSetPermissions
}

// Inspect accepts an inspector function that has same arguments as the Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) Inspect(f func(ctx context.Context, slug string, permSlugs []string)) *mStoreMockSetPermissions {
	if mmSetPermissions.mock.inspectFuncSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("Inspect function is already set for StoreMock.SetPermissions")
	}

	mmSetPermissions.mock.inspectFuncSetPermissions = f

	return mmSetPermissions
}

// Return sets up results that will be returned by Store.SetPermissions
func (mmSetPermissions *mStoreMockSetPermissions) Return(r1 domain.Role, err error) *StoreMock {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	if mmSetPermissions.defaultExpectation == nil {
		mmSetPermissions.defaultExpectation = &StoreMockSetPermissionsExpectation{mock: mmSetPermissions.mock}
	}
	mmSetPermissions.defaultExpectation.results = &StoreMockSetPermissionsResults{r1, err}
	mmSetPermissions.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetPermissions.mock
}

// Set uses given function f to mock the Store.SetPermissions method
func (mmSetPermissions *mStoreMockSetPermissions) Set(f func(ctx context.Context, slug string, permSlugs []string) (r1 domain.Role, err error)) *StoreMock {
	if mmSetPermissions.defaultExpectation != nil {
		mmSetPermissions.mock.t.Fatalf("Default expectation is already set for the Store.SetPermissions method")
	}

	if len(mmSetPermissions.expectations) > 0 {
		mmSetPermissions.mock.t.Fatalf("Some expectations are already set for the Store.SetPermissions method")
	}

	mmSetPermissions.mock.funcSetPermissions = f
	mmSetPermissions.mock.funcSetPermissionsOrigin = minimock.CallerInfo(1)
	return mmSetPermissions.mock
}

// When sets expectation for the Store.SetPermissions which will trigger the result defined by the following
// Then helper
func (mmSetPermissions *mStoreMockSetPermissions) When(ctx context.Context, slug string, permSlugs []string) *StoreMockSetPermissionsExpectation {
	if mmSetPermissions.mock.funcSetPermissions != nil {
		mmSetPermissions.mock.t.Fatalf("StoreMock.SetPermissions mock is already set by Set")
	}

	expectation := &StoreMockSetPermissionsExpectation{
		mock:               mmSetPermissions.mock,
		params:             &StoreMockSetPermissionsParams{ctx, slug, permSlugs},
		expectationOrigins: StoreMockSetPermissionsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetPermissions.expectations = append(mmSetPermissions.expectations, expectation)
	return expectation
}

// Then sets up Store.SetPermissions return parameters for the expectation previously defined by the When method
func (e *StoreMockSetPermissionsExpectation) Then(r1 domain.Role, err error) *StoreMock {
	e.results = &StoreMockSetPermissionsResults{r1, err}
	return e.mock
}

// Times sets number of times Store.SetPermissions should be invoked
func (mmSetPermissions *mStoreMockSetPermissions) Times(n uint64) *mStoreMockSetPermissions {
	if n == 0 {
		mmSetPermissions.mock.t.Fatalf("Times of StoreMock.SetPermissions mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetPermissions.expectedInvocations, n)
	mmSetPermissions.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetPermissions
}

func (mmSetPermissions *mStoreMockSetPermissions) invocationsDone() bool {
	if len(mmSetPermissions.expectations) == 0 && mmSetPermissions.defaultExpectation == nil && mmSetPermissions.mock.funcSetPermissions == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetPermissions.mock.afterSetPermissionsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetPermissions.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetPermissions implements mm_roles.Store
func (mmSetPermissions *StoreMock) SetPermissions(ctx context.Context, slug string, permSlugs []string) (r1 domain.Role, err error) {
	mm_atomic.AddUint64(&mmSetPermissions.beforeSetPermissionsCounter, 1)
	defer mm_atomic.AddUint64(&mmSetPermissions.afterSetPermissionsCounter, 1)

	mmSetPermissions.t.Helper()

	if mmSetPermissions.inspectFuncSetPermissions != nil {
		mmSetPermissions.inspectFuncSetPermissions(ctx, slug, permSlugs)
	}

	mm_params := StoreMockSetPermissionsParams{ctx, slug, permSlugs}

	// Record call args
	mmSetPermissions.SetPermissionsMock.mutex.Lock()
	mmSetPermissions.SetPermissionsMock.callArgs = append(mmSetPermissions.SetPermissionsMock.callArgs, &mm_params)
	mmSetPermissions.SetPermissionsMock.mutex.Unlock()

	for _, e := range mmSetPermissions.SetPermissionsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmSetPermissions.SetPermissionsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetPermissions.SetPermissionsMock.defaultExpectation.Counter, 1)
		mm_want := mmSetPermissions.SetPermissionsMock.defaultExpectation.params
		mm_want_ptrs := mmSetPermissions.SetPermissionsMock.defaultExpectation.paramPtrs

		mm_got := StoreMockSetPermissionsParams{ctx, slug, permSlugs}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetPermissions.t.Errorf("StoreMock.SetPermissions got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetPermissions.SetPermissionsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.slug != nil && !minimock.Equal(*mm_want_ptrs.slug, mm_got.slug) {
				mmSetPermissions.t.Errorf("StoreMock.SetPermissions got unexpected parameter slug, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetPermissions.SetPermissionsMock.defaultExpectation.expectationOrigins.originSlug, *mm_want_ptrs.slug, mm_got.slug, minimock.Diff(*mm_want_ptrs.slug, mm_got.slug))
			}

			if mm_want_ptrs.permSlugs != nil && !minimock.Equal(*mm_want_ptrs.permSlugs, mm_got.permSlugs) {
				mmSetPermissions.t.Errorf("StoreMock.SetPermissions got unexpected parameter permSlugs, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetPermissions.SetPermissionsMock.defaultExpectation.expectationOrigins.originPermSlugs, *mm_want_ptrs.permSlugs, mm_got.permSlugs, minimock.Diff(*mm_want_ptrs.permSlugs, mm_got.permSlugs))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetPermissions.t.Errorf("StoreMock.SetPermissions got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetPermissions.SetPermissionsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetPermissions.SetPermissionsMock.defaultExpectation.results
		if mm_results == nil {
			mmSetPermissions.t.Fatal("No results are set for the StoreMock.SetPermissions")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmSetPermissions.funcSetPermissions != nil {
		return mmSetPermissions.funcSetPermissions(ctx, slug, permSlugs)
	}
	mmSetPermissions.t.Fatalf("Unexpected call to StoreMock.SetPermissions. %v %v %v", ctx, slug, permSlugs)
	return
}

// SetPermissionsAfterCounter returns a count of finished StoreMock.SetPermissions invocations
func (mmSetPermissions *StoreMock) SetPermissionsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetPermissions.afterSetPermissionsCounter)
}

// SetPermissionsBeforeCounter returns a count of StoreMock.SetPermissions invocations
func (mmSetPermissions *StoreMock) SetPermissionsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetPermissions.beforeSetPermissionsCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.SetPermissions.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetPermissions *mStoreMockSetPermissions) Calls() []*StoreMockSetPermissionsParams {
	mmSetPermissions.mutex.RLock()

	argCopy := make([]*StoreMockSetPermissionsParams, len(mmSetPermissions.callArgs))
	copy(argCopy, mmSetPermissions.callArgs)

	mmSetPermissions.mutex.RUnlock()

	return argCopy
}

// MinimockSetPermissionsDone returns true if the count of the SetPermissions invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockSetPermissionsDone() bool {
	if m.SetPermissionsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetPermissionsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetPermissionsMock.invocationsDone()
}

// MinimockSetPermissionsInspect logs each unmet expectation
func (m *StoreMock) MinimockSetPermissionsInspect() {
	for _, e := range m.SetPermissionsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.SetPermissions at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetPermissionsCounter := mm_atomic.LoadUint64(&m.afterSetPermissionsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetPermissionsMock.defaultExpectation != nil && afterSetPermissionsCounter < 1 {
		if m.SetPermissionsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.SetPermissions at\n%s", m.SetPermissionsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.SetPermissions at\n%s with params: %#v", m.SetPermissionsMock.defaultExpectation.expectationOrigins.origin, *m.SetPermissionsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetPermissions != nil && afterSetPermissionsCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.SetPermissions at\n%s", m.funcSetPermissionsOrigin)
	}

	if !m.SetPermissionsMock.invocationsDone() && afterSetPermissionsCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.SetPermissions at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetPermissionsMock.expectedInvocations), m.SetPermissionsMock.expectedInvocationsOrigin, afterSetPermissionsCounter)
	}
}

type mStoreMockUpdateTitle struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockUpdateTitleExpectation
	expectations       []*StoreMockUpdateTitleExpectation

	callArgs []*StoreMockUpdateTitleParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockUpdateTitleExpectation specifies expectation struct of the Store.UpdateTitle
type StoreMockUpdateTitleExpectation struct {
	mock               *StoreMock
	params             *StoreMockUpdateTitleParams
	paramPtrs          *StoreMockUpdateTitleParamPtrs
	expectationOrigins StoreMockUpdateTitleExpectationOrigins
	results            *StoreMockUpdateTitleResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockUpdateTitleParams contains parameters of the Store.UpdateTitle
type StoreMockUpdateTitleParams struct {
	ctx   context.Context
	slug  string
	title string
}

// StoreMockUpdateTitleParamPtrs contains pointers to parameters of the Store.UpdateTitle
type StoreMockUpdateTitleParamPtrs struct {
	ctx   *context.Context
	slug  *string
	title *string
}

// StoreMockUpdateTitleResults contains results of the Store.UpdateTitle
type StoreMockUpdateTitleResults struct {
	r1  domain.Role
	err error
}

// StoreMockUpdateTitleOrigins contains origins of expectations of the Store.UpdateTitle
type StoreMockUpdateTitleExpectationOrigins struct {
	origin      string
	originCtx   string
	originSlug  string
	originTitle string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateTitle *mStoreMockUpdateTitle) Optional() *mStoreMockUpdateTitle {
	mmUpdateTitle.optional = true
	return mmUpdateTitle
}

// Expect sets up expected params for Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) Expect(ctx context.Context, slug string, title string) *mStoreMockUpdateTitle {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	if mmUpdateTitle.defaultExpectation == nil {
		mmUpdateTitle.defaultExpectation = &StoreMockUpdateTitleExpectation{}
	}

	if mmUpdateTitle.defaultExpectation.paramPtrs != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by ExpectParams functions")
	}

	mmUpdateTitle.defaultExpectation.params = &StoreMockUpdateTitleParams{ctx, slug, title}
	mmUpdateTitle.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateTitle.expectations {
		if minimock.Equal(e.params, mmUpdateTitle.defaultExpectation.params) {
			mmUpdateTitle.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateTitle.defaultExpectation.params)
		}
	}

	return mmUpdateTitle
}

// ExpectCtxParam1 sets up expected param ctx for Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) ExpectCtxParam1(ctx context.Context) *mStoreMockUpdateTitle {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	if mmUpdateTitle.defaultExpectation == nil {
		mmUpdateTitle.defaultExpectation = &StoreMockUpdateTitleExpectation{}
	}

	if mmUpdateTitle.defaultExpectation.params != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Expect")
	}

	if mmUpdateTitle.defaultExpectation.paramPtrs == nil {
		mmUpdateTitle.defaultExpectation.paramPtrs = &StoreMockUpdateTitleParamPtrs{}
	}
	mmUpdateTitle.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateTitle.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateTitle
}

// ExpectSlugParam2 sets up expected param slug for Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) ExpectSlugParam2(slug string) *mStoreMockUpdateTitle {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	if mmUpdateTitle.defaultExpectation == nil {
		mmUpdateTitle.defaultExpectation = &StoreMockUpdateTitleExpectation{}
	}

	if mmUpdateTitle.defaultExpectation.params != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Expect")
	}

	if mmUpdateTitle.defaultExpectation.paramPtrs == nil {
		mmUpdateTitle.defaultExpectation.paramPtrs = &StoreMockUpdateTitleParamPtrs{}
	}
	mmUpdateTitle.defaultExpectation.paramPtrs.slug = &slug
	mmUpdateTitle.defaultExpectation.expectationOrigins.originSlug = minimock.CallerInfo(1)

	return mmUpdateTitle
}

// ExpectTitleParam3 sets up expected param title for Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) ExpectTitleParam3(title string) *mStoreMockUpdateTitle {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	if mmUpdateTitle.defaultExpectation == nil {
		mmUpdateTitle.defaultExpectation = &StoreMockUpdateTitleExpectation{}
	}

	if mmUpdateTitle.defaultExpectation.params != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Expect")
	}

	if mmUpdateTitle.defaultExpectation.paramPtrs == nil {
		mmUpdateTitle.defaultExpectation.paramPtrs = &StoreMockUpdateTitleParamPtrs{}
	}
	mmUpdateTitle.defaultExpectation.paramPtrs.title = &title
	mmUpdateTitle.defaultExpectation.expectationOrigins.originTitle = minimock.CallerInfo(1)

	return mmUpdateTitle
}

// Inspect accepts an inspector function that has same arguments as the Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) Inspect(f func(ctx context.Context, slug string, title string)) *mStoreMockUpdateTitle {
	if mmUpdateTitle.mock.inspectFuncUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("Inspect function is already set for StoreMock.UpdateTitle")
	}

	mmUpdateTitle.mock.inspectFuncUpdateTitle = f

	return mmUpdateTitle
}

// Return sets up results that will be returned by Store.UpdateTitle
func (mmUpdateTitle *mStoreMockUpdateTitle) Return(r1 domain.Role, err error) *StoreMock {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	if mmUpdateTitle.defaultExpectation == nil {
		mmUpdateTitle.defaultExpectation = &StoreMockUpdateTitleExpectation{mock: mmUpdateTitle.mock}
	}
	mmUpdateTitle.defaultExpectation.results = &StoreMockUpdateTitleResults{r1, err}
	mmUpdateTitle.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateTitle.mock
}

// Set uses given function f to mock the Store.UpdateTitle method
func (mmUpdateTitle *mStoreMockUpdateTitle) Set(f func(ctx context.Context, slug string, title string) (r1 domain.Role, err error)) *StoreMock {
	if mmUpdateTitle.defaultExpectation != nil {
		mmUpdateTitle.mock.t.Fatalf("Default expectation is already set for the Store.UpdateTitle method")
	}

	if len(mmUpdateTitle.expectations) > 0 {
		mmUpdateTitle.mock.t.Fatalf("Some expectations are already set for the Store.UpdateTitle method")
	}

	mmUpdateTitle.mock.funcUpdateTitle = f
	mmUpdateTitle.mock.funcUpdateTitleOrigin = minimock.CallerInfo(1)
	return mmUpdateTitle.mock
}

// When sets expectation for the Store.UpdateTitle which will trigger the result defined by the following
// Then helper
func (mmUpdateTitle *mStoreMockUpdateTitle) When(ctx context.Context, slug string, title string) *StoreMockUpdateTitleExpectation {
	if mmUpdateTitle.mock.funcUpdateTitle != nil {
		mmUpdateTitle.mock.t.Fatalf("StoreMock.UpdateTitle mock is already set by Set")
	}

	expectation := &StoreMockUpdateTitleExpectation{
		mock:               mmUpdateTitle.mock,
		params:             &StoreMockUpdateTitleParams{ctx, slug, title},
		expectationOrigins: StoreMockUpdateTitleExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateTitle.expectations = append(mmUpdateTitle.expectations, expectation)
	return expectation
}

// Then sets up Store.UpdateTitle return parameters for the expectation previously defined by the When method
func (e *StoreMockUpdateTitleExpectation) Then(r1 domain.Role, err error) *StoreMock {
	e.results = &StoreMockUpdateTitleResults{r1, err}
	return e.mock
}

// Times sets number of times Store.UpdateTitle should be invoked
func (mmUpdateTitle *mStoreMockUpdateTitle) Times(n uint64) *mStoreMockUpdateTitle {
	if n == 0 {
		mmUpdateTitle.mock.t.Fatalf("Times of StoreMock.UpdateTitle mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateTitle.expectedInvocations, n)
	mmUpdateTitle.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateTitle
}

func (mmUpdateTitle *mStoreMockUpdateTitle) invocationsDone() bool {
	if len(mmUpdateTitle.expectations) == 0 && mmUpdateTitle.defaultExpectation == nil && mmUpdateTitle.mock.funcUpdateTitle == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateTitle.mock.afterUpdateTitleCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateTitle.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateTitle implements mm_roles.Store
func (mmUpdateTitle *StoreMock) UpdateTitle(ctx context.Context, slug string, title string) (r1 domain.Role, err error) {
	mm_atomic.AddUint64(&mmUpdateTitle.beforeUpdateTitleCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateTitle.afterUpdateTitleCounter, 1)

	mmUpdateTitle.t.Helper()

	if mmUpdateTitle.inspectFuncUpdateTitle != nil {
		mmUpdateTitle.inspectFuncUpdateTitle(ctx, slug, title)
	}

	mm_params := StoreMockUpdateTitleParams{ctx, slug, title}

	// Record call args
	mmUpdateTitle.UpdateTitleMock.mutex.Lock()
	mmUpdateTitle.UpdateTitleMock.callArgs = append(mmUpdateTitle.UpdateTitleMock.callArgs, &mm_params)
	mmUpdateTitle.UpdateTitleMock.mutex.Unlock()

	for _, e := range mmUpdateTitle.UpdateTitleMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmUpdateTitle.UpdateTitleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateTitle.UpdateTitleMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateTitle.UpdateTitleMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateTitle.UpdateTitleMock.defaultExpectation.paramPtrs

		mm_got := StoreMockUpdateTitleParams{ctx, slug, title}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateTitle.t.Errorf("StoreMock.UpdateTitle got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTitle.UpdateTitleMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.slug != nil && !minimock.Equal(*mm_want_ptrs.slug, mm_got.slug) {
				mmUpdateTitle.t.Errorf("StoreMock.UpdateTitle got unexpected parameter slug, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTitle.UpdateTitleMock.defaultExpectation.expectationOrigins.originSlug, *mm_want_ptrs.slug, mm_got.slug, minimock.Diff(*mm_want_ptrs.slug, mm_got.slug))
			}

			if mm_want_ptrs.title != nil && !minimock.Equal(*mm_want_ptrs.title, mm_got.title) {
				mmUpdateTitle.t.Errorf("StoreMock.UpdateTitle got unexpected parameter title, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateTitle.UpdateTitleMock.defaultExpectation.expectationOrigins.originTitle, *mm_want_ptrs.title, mm_got.title, minimock.Diff(*mm_want_ptrs.title, mm_got.title))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateTitle.t.Errorf("StoreMock.UpdateTitle got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateTitle.UpdateTitleMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateTitle.UpdateTitleMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateTitle.t.Fatal("No results are set for the StoreMock.UpdateTitle")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmUpdateTitle.funcUpdateTitle != nil {
		return mmUpdateTitle.funcUpdateTitle(ctx, slug, title)
	}
	mmUpdateTitle.t.Fatalf("Unexpected call to StoreMock.UpdateTitle. %v %v %v", ctx, slug, title)
	return
}

// UpdateTitleAfterCounter returns a count of finished StoreMock.UpdateTitle invocations
func (mmUpdateTitle *StoreMock) UpdateTitleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTitle.afterUpdateTitleCounter)
}

// UpdateTitleBeforeCounter returns a count of StoreMock.UpdateTitle invocations
func (mmUpdateTitle *StoreMock) UpdateTitleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateTitle.beforeUpdateTitleCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.UpdateTitle.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateTitle *mStoreMockUpdateTitle) Calls() []*StoreMockUpdateTitleParams {
	mmUpdateTitle.mutex.RLock()

	argCopy := make([]*StoreMockUpdateTitleParams, len(mmUpdateTitle.callArgs))
	copy(argCopy, mmUpdateTitle.callArgs)

	mmUpdateTitle.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateTitleDone returns true if the count of the UpdateTitle invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockUpdateTitleDone() bool {
	if m.UpdateTitleMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateTitleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateTitleMock.invocationsDone()
}

// MinimockUpdateTitleInspect logs each unmet expectation
func (m *StoreMock) MinimockUpdateTitleInspect() {
	for _, e := range m.UpdateTitleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.UpdateTitle at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateTitleCounter := mm_atomic.LoadUint64(&m.afterUpdateTitleCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateTitleMock.defaultExpectation != nil && afterUpdateTitleCounter < 1 {
		if m.UpdateTitleMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.UpdateTitle at\n%s", m.UpdateTitleMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.UpdateTitle at\n%s with params: %#v", m.UpdateTitleMock.defaultExpectation.expectationOrigins.origin, *m.UpdateTitleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateTitle != nil && afterUpdateTitleCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.UpdateTitle at\n%s", m.funcUpdateTitleOrigin)
	}

	if !m.UpdateTitleMock.invocationsDone() && afterUpdateTitleCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.UpdateTitle at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateTitleMock.expectedInvocations), m.UpdateTitleMock.expectedInvocationsOrigin, afterUpdateTitleCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockListInspect()

			m.MinimockSetPermissionsInspect()

			m.MinimockUpdateTitleInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockListDone() &&
		m.MinimockSetPermissionsDone() &&
		m.MinimockUpdateTitleDone()
}
