// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3LciNJktivhEFrVqQaANlV3bM7pK3JWK/u6qkHl2TN7M6g1QxkOoBoJiJyIiIJotsoG9NBHyDTB8h0",
	"0FkH6aKDvmH2F+ZLZOEekQ8gE0iQBIrV23PoKSIz4+Fv9/Bw/7kTqWmqJEhrOkc/dzSYVEkD+MdzHp/B",
	"nzMw1v0VKWlB4j95miYi4lYoefCjUdL9ZqIJTLn7199pGHWOOv/uoBj6gJ6ag1daK925vb3tdmIwkRap",
	"G6Rz1Hkjr3kiYqb9hLfdzmulhyKOQW5/9lPQU2GMUJLFIAXEffZCxcAu7UyN+A8gtUqSKUj7g1uf0BBf",
	"silwaZidAONRpDJpmTAsPGZWsYhrPWecGYiUjNmIR1ZpxmXMJtwwqSyjcSFmSsIRUzKZswOeigOe2cnB",
	"FLqlvxI1VpnFr92UxYOnI86K9TGQcaqEtIZxDUwDjyZ8mADLpBUJE5bFCkx/IB2A30gLWvJkF9ilmZgB",
	"fQ2aAb3Y7bxX9rXKZLz9JZyBUZmOAAE/wjlvu52P0gFRafET7GAN7xyNyTFTmglP7waI7Ky6Atlxn/hR",
	"3CQn2gpHNu7fqVYpaCuINbl/gn9UJzlJEsavuUgQ728/vDRspDSzE2GYmknQXWaUthCz4ZwlKmbcRCBj",
	"Icf9gTxVaZZw//DAPYBjxofGkZaS7CCflyXC2IMxlChuIGcT0EAsoTWfs5nKkpgNHR3GmYy5tI7yuh1h",
	"YWrWQfGtivP933Y7dp5C56iDA7u/h0N1847frBvl9xA9y18Xsu3rng4ucNKfw+TGaiHH+FyDg9IJomak",
	"9JTbzlEn5hZ6Vkyh013+ZMQjwl3+upD2N18VrwppYQzIFhNuJrXzJipeHOLZ0063MxVSTLNp5+iwbjgj",
	"foKWM5skGy/T1AdHN8w9Y3sWtBZW6bkj46mKIemyGFIiIUckDv+BKPb7daC4doTcFhq33U6Qqp2jP9EC",
	"CRAeTlVs+d1+nw+khj8CkdCJMWA/+D09EEd5ADRz1KtpaudsNgECDL7vFQAzWRSBMaMsYZGS16BRFMzB",
	"sr/95b+51wdypHFvMYu4ZGMNcyfDnSYQNF4qoivQnwtbBepaogg7yaZDyUXyPFHDbz31L9Ag/oMnLH+X",
	"iSkfAxsmauggOvFYyYHCEPYHXnz940BKVXzcZ6/BRhM20mrq1akjD3Pw89Jabgm8y4sWNqkTD/UUS293",
	"S4RWS6NZLOyJsxSWSVTENbTpXn1iWGZAMxEf4/6veZKBM0FGIrGg2XBey4aJGhPqqkMSxYoRDoXjOnI1",
	"QkbAhgDORErAQlwz5sLORdy8x1fS6nkNG0aBPauLgv64z3LR089SJ2u7zGnvPu2jZoNocb2Jm7boyIUz",
	"MzcWpiyacDkGtjcFM+nNlL5yinIqxhotAFMvyHCCt/VgxJ/ZECZCxsyvpMs0GJVco8nnrLPYE2ndWrr+",
	"R0QBgd9DvosWxAh3zyJUss6qGXqDD+IgP9iPKkO7i0szA23YTNgJE7FhmtsJOG7hko24SEhY1e5xAx3n",
	"WJ/L+TqQnyll3RYq2+2vGLANiPO5++xiAuFPduVEJtnpaiadinLwfGKYiJ3YJimOL3AbHiFBBcxkMgYS",
	"K4ZP3bgyFkgSjBtWEEAD9EBaYee1Mo8eEawaHr7lQ0iW933uFLHSDKZOCnLDFDErXIO0x8xk+lpcA21a",
	"q9kTQ4QjlKwFsohbGgcSZmdqtryeMz5j351/eM+M5KmZKMv4yHqgEXKPGSAwVZAetQtRSdxy/CGMlDc1",
	"lyYQ0oC2ngoS4WR/DDoHSCxGo9rZNZgsQWIH6UypP3XUVcfZbSKBsiArKYAgj85rrSZCE6Em5dotJP+i",
	"mysrxLQAw2YTZRBf6Dm6X5QEtpcmPALn23VZyqXSfMq7LFZRRr/lI/7AjRFj6X7d77Mz4DHaCX5+N2yB",
	"HRmvFERwDXpuJ45ZIDHQZUJGSYb2HS8mdCvXcy9quMXV8sSNNc93ICw6HWQ6CslKZF3LMMsKBAVQN+iF",
	"nKFydDUqmFM+hmX94tYc1Gkbc6mkq2qsJQk39kWmDWnrhZgCN4YNeXTlGPQywrcuc6y7L1nKx9BnJ969",
	"0uwwDyoIw2ac6DXhxr/piHE9k2oYkSaNSU7x5LQCgSUqri7722zKZc9hEa1dyadg8lU7zSGkETEw4tUD",
	"EgldJ2YhZoPOIDs8fBaNBCQx/hOO6Bc0SeiXQQdpBjX6oKNVAj+I+Oi3w7//GoajqPe3v/zPQeeIDTp/",
	"/e9//T9//d9//V9//b//+p//+v/+9S+DTp/9DqcZzr2JM4SIZwYY91IgZjgzkwCxYRxX7wh8qOyEuWXn",
	"opJrrWZkLflP3Ks8cUQciNc9vBKS9IRUXpj0cPsWoaNG/mv3GqoRNzPEfXYimXBaeagcN5CKdjMI493p",
	"bh7L8TJqxJPEE4xVzEzUzPEbQT0nEkf9GpJ58LNenP+ewU2qtO2y2UREE5ZqjP4478Kzu6lwWsElVlle",
	"o1y+VTM2dZrTs0qh+siaNGzKneEsJONJ4oTSGAUDgsUhduaEAWcymw5BQ4y0qwklfXaqIQQTvnl1EeJY",
	"sbAHUyGBEBJUdzBehGEpxckcyGIFFD1L+TwnTAzA0T6XWGSVb7wgb4J0qBcqdlLECZclSwWKNWzW4Pvc",
	"Nkx1ppIa8SXMOdpMpYGGSiXAMaCX5stzqqcq5JaV14Isa/bNmt2c2pV/NFDjvERGjy4wyLVs20cTlUvK",
	"f+69OD973cNXHZWcfji/ODj9eHFwenLx4tuDl6/evrp4dVwEWjFq6sggUupKQAiomVpjzNlLtXsU9VaY",
	"MBj5qIe2kkPFtdOKFyrT5hxob+0hnnJjrmD+SjpZUmMy/2EC3kgv+WHcsgScSnCSyo/ANIyFsY7bcklB",
	"miSTV1LNZJfBDY9sMncQRp5RNvXz9tlJMuNzUwnzFUHoQr9rlVlgOpPOMCEbAXmbJYp71oREDEFz6yRU",
	"LZ8mSl1lade7M1KRkWExbhgpabIpGg0ViVVL4BsSt9Myd+AJ99mFI//7aFQ0A//2X/4ri4VJEz5nyFBk",
	"aPFo4s0oIVm+SLJdyWYiGHLJ+HCo4VqgOxq0GI50RG8OOjyeCjnooDfjHjh9/MLLUqTjQccpicTpS2cF",
	"A5qkblb3iRtkjN8oehfVHmcf35BOCdoIJyOzwP0500qOcZA+O6GHnpAwsoIxL56WTktwPmfceGeWDcHO",
	"AMgKNUhuThXWakI3fIM2M5bbzJStd2cyXjs3daTVT+A+8jPW2/IFRzRz4sWHi1NmZ6oXDnOcAy4cP/TZ",
	"yfPzV+8v2LtXJ+/P2cf3v3v/4Q/vcz/cu54G9LWIgO3hudJ+re/ubHd0ORHnCEkydrhhg45naIcd6ViQ",
	"flWjkbOZ3HJ6YY6c/5z9jRblKOHj3OoYcwszPmfqGnTi2F9Yj/CpP6XwnjNn5AF53sUBkCQdPSO8/NFW",
	"E9M6yJ7lSnYpgCUZ0q0wVnMHUy/ZzdLJGdK8WxAdt/XZS2GskFGgtAKBwRbS4Cwj51kR+pzIFCY/dmta",
	"sJO1jsDXh/bQPyGtUvosJ8aFvZfFUFWWFZqmzvJ4gbat8ydmSpePZKsaVsIsvFPx59PwY73HveE3CxAo",
	"D9CtLKF2J3hs4kybxl08iA1TJTHlI8fHPg4QF6KJRDFG59VUWAvxPQK99Frzvp1h1LjvZtsk3RSpd1R2",
	"7cm+huLTVWh/SYLi6euTxu1HKm4xMb5VO4OPh9TIF3b68jXj1lJg1KpyCKPPzkE7guCm5wSkI4vniRqe",
	"W6WBXQs+kJWjATpCzs8FjlEQ0tENhmVJVUcT5SxTf0KDh6gkaha2vPkZYutIXXWhy1ApNlk5ODl9+fqY",
	"zuhjt/vqucgEj0I6beJgd+UglKfV0YqDk4U9rSID4reabTtv3G3WeRW0uzCbAIffJBvfHoTgmukv4WwZ",
	"rvcTFq12RVpti9xTmoDSf5Zn0BA5S2H+QsWwkVy5rZ3PCju/G5LQ/iie4HmqKQd7B3IktLEsS51f4sMX",
	"lPrxxzenBVn75133ggwCwtCpqwabaQkxcYfzTmiGYDSNlJ5x7QeniCRl/FieqPFAujX+OYMMrZjS0e6P",
	"akghjpBnlceaMEJFgcHZQPohg62GQ8XsOzVEuJyfv2ImG+Ywq7oLXsfh0XFZyQ3nFCmhNeLYUx4Dy6T4",
	"c0ZuHkozH+TK0jQRwUbaLNIBN5Ttc+rD1R91vWJbZqaUW/dp56jzH/902Pst742+//k3X93+Xa3Q2eDI",
	"mE7dmw+O94iMMJhwzMRYogAfKT2QJdLb77OPSDQUlcMxFsmJIfF5qBW72StvZ/8//N29rYx2ggMTkdpK",
	"i25nCsb4qHkLSVK8Xzf3t8ATO6mZfALR1X3c6VPQvVQrdJhMlthjlhYxxQM8fviJLDp8KyTC5QGSWueR",
	"fKZ6Kl1yLPFYSCr7A06GfuVY87jBsfS83yJPIDgNYTV1YP1ODZtzVxp10h1MDUzRe9dIEI0hsytB2Xyr",
	"DlW+U8PfCUrAS7UaazA1WTevNZ35OL+vJEJnSl9hhJiCB3uH/f6X+5WjkVGi8Mhoym8o7vtlbQyY4tMr",
	"I5/G+s1XV/ZCcW2gN9ZcOB2RTrgBlvAhJMyADYKWcghQrjq/U40GctAZgY0mQo4HHXbABk5S4i7zH1Ku",
	"TemxjFTs/3Rfu207YBVvJCruvff/DjSOTxuOowtiXoOfc3rRuQWYarEB7dTZdEgV3ZAK41fRQN+/8xS0",
	"GIJxHn3QXrGacm9f/6iGTwxTmU0za9gQEiXHzKo+nhUSw+YWpaMKJ+lrGbXYdYnXfV6b890zKelfmLYF",
	"MfqKK06Hy5lWS9t55wiSJyz8qjSqdkcpbz+8ZAlcQ9JnL/KD4GTOjPgJDsagpmD1fCAdEClcNhyqmy4r",
	"JcF1Wc7wKP3efnjZE/Kaa8Elnf4m4hoG0h8i+bPpsNg6lf95JC/eJ6+wklDYmEKIqR4rLfEJTxKQY8jP",
	"OmpyWuIaoYKhRQx/kaHNvI6tSVOYAkqupSEoG0KJCMiy45YZC6kjqi7TkCJJ5CHJYMteAaR0Xmi5hTwa",
	"i4bjzNm0SWJqwmSLFkF1391mZwNB2Ag/ETvbdyTq9kfpLkqzUtzhAaIljfAc8cQAE8aQHT/UamZA90LK",
	"tj9w2pOKveM3vZMx7NNBSUzZHB6I/jMWJcqAOWZWZ+A24WO7BH6rYj5/YljqtJxxfOyHXw/5EsTWhGE8",
	"5JtcvGXSrYIjmFm4s6evT8r3HWpztx7BiZ9tmL+UlDtTrzG+fLZiK8sv1ZwI1nm674CbTENTaMrwa4iZ",
	"zhJHHxOn0ZQsx6e6zEy4powHPHBz+mE2UZgNrFKQAylsn50WNz68UsxHeOJYW095IgzEFItiJuUR5HIA",
	"/xrIPM2Ipcr4BLfM0GtCsljzGV1diEH32QmRc+xXjQeTbjHTNBGRsJS0YmCMA4aTHGG9e8QwN7w2Joaj",
	"1p+3bjNeRjcYWmcFhXzmqZBv6P2ny/HU9VGxBzGtFsNlfivdAMsy4MpTfr+aXP+gRV1w5mICbJQlCSH+",
	"mJ1+vHCqxRGPYeHmkYwDeVg1xqOXPjvx59YD6bQKvdktTrPtRIMPxNOn+GyqjGVfHh4edhlPEjYSUlgk",
	"yYHkspSh5kTRV4eHm1LUXbHObzzWcWmrqGABYYu4WYMD89IfWNYkm+QPGrJ3pqVh2AzQB56qa3KAN0iJ",
	"WT4zLS/VahGh9FleYo3A+yjFDXOUbSyfpk6s0AmfKbtvscqGSYn2Cz/tuibFkjtHkA5I2wyyGEvpuFGb",
	"t3YOIVmwurekIS8XX/eu4NJZ06l2pvsEMsOmODq9WKu3/JO7R0nO+Kw8IY3XZx+c7sT8twS0NSzlEhKf",
	"LmcnMGV7VjELyGtuYFq9d4L2jx3Xa0tfGR8nw+/67AMdnxELo35tOKjfkOnKNHa7hr0ILfkUtXhF92/Z",
	"9tlct9wx32uXYc/GgOfi1RhWuRkzkHQ1pohytr8k80Axzzvoxm4nM3wML1RWZ2vluQLlowSntii1pLjJ",
	"xSOtjPHpTaWDwgp9/wRabShHzcaHWUiqdEhSowF+pEDgmjAOqqtA8ivZDF9aXDR92sXJGpf4ETG16hzH",
	"2fHl4xp/0NZn9Klh04zyaTGZNoTh8STGn9xwHU3ENZBpUQQDncWbSasySpwJOPLDuKcJjOxAZtLnB9dZ",
	"CC046j3MSsyUs1G4dEAkyKIEuMb0tU0Zoc51CKcnNVdpEEGR5XKcJVzn1wLY3htpLH/2m0Mn+v2h135x",
	"II1n3ygbB1JU/IwnhlyDXiadkY4uAZ0qXQuYgcbIpJ/EoXDQGUgLiU+voWOlKWjupgjug79lIGPQmMuT",
	"YpKfuZoP1c1xyd8wzFg+D44OXlByAz57iXMzo5gjyJRcE/dRzIQcSBCY0uNW46y/a2EEUlDQtgrNzoc5",
	"do9hxLPE/guvuZvykp4xvESupOVJgMWcz9ie5rHg0nTZTOkk7pHrxS2XT/diof+5y2Kh/7h/PJCH7B/Z",
	"F3/cp/t7BHQMuhWBhBwDzvEzC8nOzVbTBj4QIe7elznvmHwAnqzZd6ffHJy+/2a3mQh30jhzPvswGhmo",
	"UThnylKqJtcq8+e4xANPDPsXxm+EyaljH1kzEWNJQi9g+olhuUc96Eil7WTQKVikzL78BtqSRBsncrW2",
	"KtFKGQYVRvl+hUi7X3pGgI55kHNvB83FoAl5mMKG7NsWZ+IbM8/dE0kWyG5jn6e9BZIf4OcaftELLcvF",
	"FrJoUyg9IAhqNoe5889hZVB0lKhZwxVNSis035m6+8qn2TAR0e9gzvxrdIHREbfk12LMrdL9SAMGb3md",
	"E7hizS/y79Z4Mm0PbRNu7EfT+FVzVmDTCilwsTZfqd0RyFLU2b0tsyRZE/6vjr48ymhUFpcrU16b9vlW",
	"GLsiol7Cb1t/dxnFrVKqwnrUWMjXQgozaQS+06LaAaWecmvJsz8Gu7fvMy6QlGtLnDQxy4II8u91F5by",
	"ffO+zvzZ9pqtFSveZG/EMvfY3ioOqd33wjprNx7s4wcJVrQ2AvPI1nJykHPdGs2qTSW79uZRa30ZcdIE",
	"rdTGw0feux3vYQSd+CaurxSjZokweO06t9dF7K/0FmcswuC9FsmEZHsV14qOt8LhTPCCOF3Rct+E2EQ+",
	"2H64uk13bCZYMw0vW/srWjT6Qo2YFrSwMtZWazYWNFIxEXNkBzyuJPjCOmwIun7OpNmGit5I4URDQUA8",
	"J6s9qoOCReesuC6cQkyBejDkFgBdiakmu7AZU48IF7erdvZ7hyaRCDtv2mO6CoOvsyQJx2LI77xJMDwo",
	"2sprqkPceQQSnmcyTmqsr3Mhxwn0qLwGvpN75j4eQeUK3mAtiFBdhDSxc7tKh9bCGhZlGrOK3n54echC",
	"giLb84mZmEmwj6d6lVCQ887oULxyfqUkXk8L+dABkHlRroH0CbzBNxaaFaXq8rJQxRF3qWpWfSrl2roQ",
	"pRpa+X2BGjfg5eu8Voep3EJBhVDEl9uW78ovutRc4CmDrO6obAGsdIRrqJRAeTFd5zOLOEQ3EWVSSWi9",
	"yHLWQ906Ha7okGKDQhyl4m21d6l9UKA5XJrznamERBcQUYp6DmQIX+LRGDfMqvE4AQxV8wST3G0e+nS7",
	"MscFkRlM0csDm+W8qmcvkZRzOeCmMxvUcMtDw3WAyOdv73LkpubtiiyGdaNc5C8uRRxK6Zel5S0QwgL9",
	"1sovsGcqgaIKg9nGNcJFobowUsPCsnTl/RllU57ZSeNVCIg02JY+9kUZJVs/x2x7myPHbMMJ3Gkh5Zck",
	"zh2O17Z3wPpwAeJ7HwHmmD6Jp0LWJCJkBnS9J+I+CFUBDaPaUEHglUOde5jNY8BWLcjNeCQsY+UeHuAo",
	"84GFUdOxZv71OaLojAy5u8arCc9FMreDPx58OAtmIEcazCSZ+/tqEOMttb3Fe0X7x0shf380KpyimfE0",
	"JewKSvDmTMKsfFQqjL9GVmf13IdjFol8A6re5OR4GbCrj48HsnTx767HxwOZwMiylcfH7eRjrRxXV7Aq",
	"H/cx5c+22U5Iki1uUSzWXsvLayzn4vmHJ7a2+oYsV92Y0WWvvNQN6gw6rVGjEbkJoQaJ0lTugRQPHvyU",
	"agf6cuQaIqUd61GFXjSO8T4kVtgYZ2AM5c2106ghfn0GUy7wzsjy6WA5xE2HTHPA+pNxQ1E3ev+ivmYX",
	"3sqlTPX83nlwwOhkbm3hK0JN3eIXZ69jaeLElYUd7l1Egea4YxGFSk2EKvDy9NVQZ+mJwSI1ZgN9uK56",
	"Qs1mnFh/LSRPQu356lYab9G0vg+zANh1V1toRRR7qgt4rCuJ3riu3Ir7cn2S1OrFnUND7bV1a2s49lLL",
	"J4grSircEe4YKMWP8wnrdohBqaWN3bQ8WJ23fO+nu5wY33TcBO7j5YWT75JpYefnzvaiZQ+Ba9Anma3N",
	"TuR/zqDa+IDSdgorKrS8EBQyduM6bYGjFsudWJtSmwUhR6rpDJadvTq/YCbTIx4VIa0TGWuYh/g6aBYK",
	"rffZhXNNwu0oZ11hOpFTmkHV4z9Tuv8QbM9jp4GohJMJyQb5pbzuAPtMdBnWfeqGum1dhtWmeSpIaZGt",
	"hyWZmAgtM8Znpy/w8UBqp48M9FKtbrAUgjFg84JPbmtDIbmeY4aa6Q/kQF6UUh+EYSZNnKKUzg2YKX+N",
	"0hwNJGN/+8v/YBel5EinAP3NQMwNM+VQYJ7XhQUOuLzmbjoa5B2F4vB/OIiTrmifPXtJSza+6pSIF+67",
	"4JLJ6GYjkYBhex+ef8e+YO8u3rIvmIUbm2kw+2S5BYMZF+GsZm/mOYxplY0nvj5wJq8grt7Sz5tW5OUY",
	"sgQrnBU1ATzm5ULtmIty+wPcKoWMSnXDGd7yDbUkgu1ZLS7TpUJ6VLuS6sfork+Zo6NOevjN2+duiBDK",
	"RJsvKHhCK6F5phZavziTwvFJTIkHaBNp8PdNh6VMO+GwyZOBnEIsOH5TLQ/OGXlVOZVcFpU7ywlZl3Rq",
	"pbk0nm48vTJHr3NmlRuALVAtldpwoNd8xi4xJHQwTuyoR7R82WVnzvbu8Rl3YHPL9uMwY7H43KsLX9dM",
	"TIMnEHG8Zt1fXvKPamgOfhbx7QFWyza0as4uHXHRbz1jNfDppXPQsOaG5lMgdnIiDaT1fWGwPJpkiiQa",
	"iaeyQLusk2iX/YF8hbafWywS3SW+8u8vfYlFN2qe9Z/MURZ5TklB9/ClgSziUsfs8qvDZ+WOREG4CsOo",
	"zcwwsyzh0VWpuCKZYx0vCJ/z6ApkzL7xcu/k9E2nVLugc9h/1j+krBeQPBWdo86z/mH/GWW6TlDqL5OE",
	"+3Vclx13sYJKqgTSr6K/imLolmnAWehOeSJu3sSdo843YE9SgaFjEzLXuMOm46/O0Z+WYuTfnvSefv2b",
	"ILaZt5kEXn/k1v2bbLxgTRVq0uoMuqUGQUs24M80zAR4jErMD4S769zlyzej3nslofeO22iycoTvu9XG",
	"Xk8PDxeaHS2xXbXbUW4x+IfLQYClCyjPC03kyObp4W/qSmRrPOgM4N5DYIRDpX333bPDr2rSsZV1oleM",
	"BMRsrwIHKk7sXTlHFDjKVzRKXcQoB8xB3osKjZpsOkUwdM5RGFAdH7fKHo9jjR6hE84HJY3rwMKdh/Gn",
	"DnFB5/vbLqINI8AVyvwWeLyGNB+C6howv3BnDAmL4ib3hdZz1J+lAdneCw+3tyDHzgZCrKAcV5mlK9IK",
	"y6gsAe+22ykKRDfKEuwmYQBCYgTWUz1mXOJtWbweiE+Vv/skNJbE9FWmn5hQvNyHRn0I/YfhnA7ISL1b",
	"kFza0FAlUlgVPSSaenEbSnLi75zl6Oyzs1DTEk/u3W6ONPCYFTKc7eE2hnNnGmIN3P0+O6XS2sIwtxis",
	"IE/GoQOAb7jk21ikfAwhk57kI1V6lTDLC3knFBhR1/7OljNKw1J+cCDJS4aiHUsxetQ2ffbGUtp5XdVu",
	"JqSxbjsha8WZlr54NxkjBhwwLNBohvpucMsGnbzpgRl02EgliZp5wFIJT7zwzA2WIQgV9kqPx9phhayh",
	"JMESySku0yo2UYkP2FVZ760wFsv6r9MGr0P3HEY1WkI4vR9Uwp8zQGHouROjU+tE+cLZ5A2PLKNCN11W",
	"2+RmxWwhpWbD6Xx1MSptvzBnw2R514X1amrhS4esynftDk7qB7PqTkMtJAHmTRsKDk41XAuVGeSjY6wF",
	"WmrVMINSC4a6dRFv1q+tOUywrA7HgFVeusxnVrOvD7ssSvjUB/efHh42LSERU6To+hVQnZVQEOmpv7Xc",
	"HJZZbzHcvT1i0Z2jxmz48DvSQIfrNVCpPSl+8uX6TyrtHvGjZ+s/KvqQ3nY7X7dZWd5Ys6obsSdLqcHB",
	"E0O6IMjKsgpE+bSgAfuRuW7UguflDg2URjMFZiKVUneGBcGNhjPwKbnPL85/7zuElptGCcPgZsIz49yP",
	"skdIpefHWGGG44XuvJCqyiz1x5gAOZ5TEccJOOOd1OlRbpmVHznDJhQUn6ikVCDR2QahnjP1k3RuDhtm",
	"oxGWuspLMGrwnTDqZP4rfIKU9+L89w221l3E+d0l8y9dzJ5brkk1E1qwNNfM99uKvYy1KjzNRbEXt2jF",
	"Pai8XS/TMATgmawZA0syy3EPcdMvV3YRAxX2a9FZDqXHkujq0v/3CLuLkuwAecs0CrPnGKooyaInvtWa",
	"l3DOoraZlqZSFcdApWeNtwgjLp39T6bjFLB7jsWX8/Jn4/y0LJkzCipSLXwZZs00Sr+YaulXRKSxAhMo",
	"EojQ8O6z80il0OgjLHTiqIrlkqtQ2OYrjdgTguQ99XX7XljUm3I5IeTflCZ30A9Z2EqbvAJpHpl1lPfE",
	"MJOICEKzjpZaHl2q5sBZeXhHjZ7iu0FuUv1Z9FmJduvp0OfSBgeP8SiClPpG0We5gkQlnyTo3KHfBhr8",
	"xUhq3qIcV40hNIYIP46UHgNKeOeyzrTAfp0yZsI6nvRNLyxPrvDMutTpw6gpYN8s57vjYezMYFcp9K7L",
	"zp5KYrwFym3o8RisB24wZ5jBjTDW5A5oMidILBpDJD0MMq4wZSOtP5A1LInuMjYAyZmUuloKw1IhZcjF",
	"IRyRQWAYtcdWqmJMjcU1hLsaWs2OCplE8VznI3PL3rBYxKGu57IseDdv5dL+6m/+6m/+6m/+W/I35yrT",
	"ZSG0Uv3YycHTES8pn9rjlMxO3FtbRNliKlkN4kJLpvxKcDfPA/P5YaRtJqEgmq6mXIXiMHfEZSnvAcVs",
	"OePhT987ei7wsKSz3ZpTZWymoYIOO6nBxoFvs+SrDNSg5VSZEl58sxV/TADGPlfx/MEws9zK5baaLmJ1",
	"BrdLpFFziOOAEDpI7QAJfuHYwqsF0Ckhri3MqYHGlkC+1P6jFcQPtzG/T1Wtk6OSFOIim+3RNVclI9jf",
	"AZZfKDkSekqN2iibIgJxvbisFgQQPjjQMAaJTQ3bUsNZnkKZf/lvmDJOGGa4Y2l8NWLqcRBKgZulhZQa",
	"0IUcWiQn93i/BeUYsFnallbw5tA2VenS1aQaFOH26AoS+4L5q0rs49lbBwzqRWjYP53t393uefq0XgGE",
	"fuEh/3gjHJ5qdS3ImQ0lKllpK2tQRemFbdD01iciboOFK9XQd8y+1XrgNXRxXs7R7KK/i7ZLXin8E9jO",
	"C8KFekEyavF5EFqKKs0QvcxOtLI2p6ycdEp5XFghChPHD0ION/uClavBrCOiYDO3I6RgOm+Jlj6dNqhe",
	"Z1lHTrsjnduqgUCdYzwlE5UU9LwW2yqzbVHtXm1jCL9V2HfXvb4LvXetrmDhgghl1a/e+xRauIXvoLNV",
	"R943F69TYXgwUTB1jMkau7A4PRQxN2QP74048VFcUd5fC9iDopP4wc9WZfq2FYm9gw+VDuTrYn/uHUwX",
	"whDcJWVyXzpZeRluol/WJztaGv0+aWc1dP+O66sg2nclB9pi1a0Nj7kxnN7TmZNaGdpBIyxBRUrGXIk0",
	"hXg9hstlyVogttRSdxuKor6h8F0d+TAO85ckHydGac8Yfmmp2/0ljYOFKm5rROBS/TazTZFYV4auQTr6",
	"m21+V2YHIC9OyZYEc3khG2MB0/eLLgh1tyu9B6ehxysZ+0eMF85cpRoghNbhWDh4Jgz4Az4yMAPN+Jqj",
	"dG80FeGY2t9MzeP7blDsp1R3XkPFERvpBSvErc8FFvHmIvnhRUltvcf7SJIrmLPQc2J3YfY7pDy3Djzi",
	"ZnwPwPXsUIo/GAtpL0sDFe+35BTySYbQ1r0tl47Eaqg7EFjVqqt14X0YurXJcBkgL6P6BeNslKgZE0up",
	"527MvDdYAiYHqjfz92JhMNRD90cKjtsMsmQAbAxaKl3Z2Sob1pT//AycwPt5dLTdKqqP/bUyLDxfmbAd",
	"osMdvM25KBQqfXyMhPcasJ9qHSdt3Rgg7gxYwpoMWJQhP/au8d42RNbmjFktK7td3qwvYbtj9qypLlxv",
	"LRqL9dE8jHdAHwtsXBDIMa3FhMs5YeFriKNwwNsY7aW3d5NJV56zTTZdeYW7MovuZOuXrjSFe+eFRVPC",
	"CiZNrVO8VIZjPf7OfLmO3WDOzdYGZ7SqR4stilUVyMG/m9DSXS9TCyRsIWKBl/LK9WVaCc4vHzT2SHiv",
	"yf+mG4MIwMedTfTV4W/r7k8mvotGfhqHSZMbxlcQCIwjFJaoasolH0MrdvfVvar+/QoHGsnO15xe72K+",
	"fOyuZcNh6fncWJgiNP1BHMKZks/L1f2c4WTu5KFyJpXsmWKi9lhsE68wAUUbRCxSvNq+LHTcz7Xof3jJ",
	"s1zZascm2yrJQ4srS57PPVpyBngA+2BiZNEQTLM6JZbZRWqqWoTboe5tkGtzidxHTbaPV2FukdKxMJIn",
	"9ScV4/iOhE+yf725/BHfa3UJ0lACbpmSQWZTXAF2IOh0O5R8ge2/FnsFr0uwF1RMPmjlGoYp2qt/vyv7",
	"/qOBVjecCIyP1r5HaihREv59D/s+UM327PtybcdPYN835RYE+77IKPis7PtXUy4SZzPm6U0PYuf7hIcq",
	"deE1r1ZiquYQb4WRj7T3Jm5l4p+rke3Fn6udD8moZzlenVOaJdzYHsda3uOM6w1VTAkSTQijp7UCoY0S",
	"qUPJbhJ+Pt49veeRGQLfgG3CTrOw3sLxcAtnq4zzbblaGyuBHdGbt1mzXwzd0Y486YWax/eV6P7uBA5R",
	"PolZ6HAVwzRVNtTZpvexTokMyqmX1ysPKRhcmpmzaJ4eHlIWBrLMFUBqmBFjrCEpZBdrHVKZr3D0N+Vz",
	"X9Iq1AArH0AVdTOpBApnBiIl45DUgckh7m2ovYm/aCG9ifEKCEFgW4kcvzLAg3hgCPMlhKvRA5k3yAyZ",
	"3IAd+uxlqMHm78Y5lgjkV11nvx0pfszn/5UYHzExnluVlgXh1mhypAF+aneXzRPRa/riF0Q+rzFisXPq",
	"2brBT5jylNJlVyJJfImsQhsuq3iiiA1ISM0k6E0o6AN+8LiyGquF9oX5EDa1FHhaqOfv36yphf+LNFYX",
	"YiFUecU3xueSES20oe470PM3WN4TW4Ln11ZwQjZK+Jjt+Tow08zYPKgxhHxZG5C0Bswy2YSoz/wnvyC5",
	"6Le0Y726mc2GK3T6sRTm2TC20UQEmdxcOX4M3/yCyOCEegs/WiIIMG8yidYqtB/VsLn43AdJdeTmLAVd",
	"6pSnNPb4TKh08QS7TvyohkxJ30Cqy+AmSjK8h2yyKAKIsW6/86oxwzFv4xBkleFzNujgvwed/X6l/wbX",
	"oZ5nqTZ1qCLi20jjpfpQdRkLfurMuQym1PCg1Djt8pj5PrlY/URgYU9skeWr6PXZiXeyL1/waAK9F0pa",
	"rZIjJlUPGe/yKPSsMCoBlqokMVhzBatN83J3NZ1J02evnNtN4PSFtRJuwVgE3XDO0HxlSsegj7FwdKRk",
	"fjMxG06Fb+CrJDCvSEJ7CwNa8ESYUK2P/ZgZ2zNZCtog6C3oqZA8oasYWAlwqAWMkjnWGssXLbGniVsQ",
	"rrnGyaew53eObHZxChXaHbYqsXefEkEXBT5KmHOQSLF0IiXwEdy7vgh6L1Blib+Qoar8VW6y0chrrxC/",
	"l/jWkZv3Ei/l5IXe3Eo88vD+lu/XQtU2WZQog4XdC3Y7GHGRgL+mE5r4EJWGXjssw5IG2IZRqTiQqFvC",
	"E8MuY2750SVL+Ryb8QjH5t+pIVWz3bsSMmZfULqUwFTU0TwvQWvn+/5+EK0PW5wiyLCyXHxU7nWDe6vW",
	"qSSixgp0GlKlLVXnxZrnzqNcTZlv4lfXvrHuJ9BES+1T2qsipPaamwLnrwIg95ZGv39bB7zC1Tt3cobg",
	"FiYL0qbKEM3EPgWrRWQO6Gi7sUsBGJVcY1WRmJsJXtxlKZeQsDcvnXynO2U9rJ58qtX0n95SAZtMooDl",
	"Yy6ksfgI7AQyQ6TmXyWWSYBfgym3NqSijJ7GnGxMEwExg5tU++Bo6FlVDIwa5RLXdokDXGrHe5coeIfK",
	"TqipDHoYYVnl1WOz+55TL6brS0bmQdaS53B+fvbaKVWEGxPSOVECeRlbdZVLofouNiGee/L+5YIrcOyz",
	"1+gXbG0UPqJ+PGOwhn11+MyN6ikDt9Oo55p57R3h+598JsPKO9enAcGl+psFoOjmgp532VRojYb3kKRJ",
	"lAgSR4iFXmj1xN5IY51LtGeoW/81TzLYp7eMv/RC5bkR2E6IOy0JRZ8rUp+IUIS8MzXUiGG/rGTOnh4e",
	"0rehH3lN0gbOtlJ8hBQRJ7p7WN8G/6VTE/4Jbr/5X+lvfxv+iU1q3R/U/sf0fHmcuJcXUoqLr90fTn/J",
	"aO7/wqZw3Q51NusVPGzqfuylv/26+D1M7f+kXmHF32hD5n9hJzc3ZyatmEJvClNqKhx+GCutMisk5USH",
	"H6PSH6PYPeIJ6Eq/8+ZKkkhybCZkrGZ9dm4hdewUgxbXGBwuKGvvPxWI7DrkypisSKqP+uXXhplI8xTM",
	"flOBR+0bE63H8pdfTzvdzpcOOL9x/3n6lfvv39fmAe0kiYc49ByJu5UdVbX4xRQ815SyPR6mYJaj29qA",
	"jbySdDXdywulWSaduCYrgJCxy7KTT7e/6ZLGySSqITzwwHCPE2ROvUiGvM72YrBcBM8FK6Z0fasaenV/",
	"MxcSY3g9PA4sLYPAHxgh6Huv4MsqH72oxkw7LMhLr+yE3N1Uu/EXMLFsGraWA4h+aM4io6QhWue2SuE5",
	"85vmaReJfTgCx32F7vY1YMfnoa/UYg9yasp+x7Sy+1WHpfuIjPuwhlsYrgbrVhdLrEN0lRFqr2wsmr+j",
	"zNlcVrE8IYmmpSsMGkagQUZkAmFmLLbs7jdUTyhoaaMbH3dI3Nswq+s+KHlZgUw9gzVlZTUA5PBhqXxV",
	"CeUdAopSpoh+hnPmk+/rxNEur6XQqcs2pRyOTdPs+rhpLfofN2v5ZKfQPJRIZyQgiQ3bk4ppKLkF+61F",
	"3kEe011vDJzkr+4kkd3Ptkmrjh3iAw2J0Pk4LoXGR0qvFoDbYOk1uD34OVHx7aqLFRUEbzUlNkfroxHE",
	"RaysjEm2h8Dc3xkSu7XDJGp1oHO5aUFoU3BY16YgEErpUGUl45cOdHbC9Xl38h26A7ayx4Ds8q/rHINi",
	"1b885yDf2woHoegp/4idhOLgooWjUMV+Dde0vuVdpY2NjP1PYblXoeTgU/gyK7ijSa+s2P3hw5Poo7Lu",
	"C0guW/hLwmX3Zv62ZVY+/qcx91vRxGdl8hf01MbsbyvADjBXc+Wl2xyUJ/TqLrDmp1qBu8d5J+7exgih",
	"oyI+hKkUyKBG60om8/3dS5S66gPn9SSyRZFSpo47lOk8QWiiSmOabrHHv6hr/Pe1mehiP6Z8PQg5rhI/",
	"reIPBeZ/jUG0jkHYkobfpZhog+31EYkllP8alcCoRI7VHUv/TxWeCKQTqyibLuTiLQuKl/lbu5APYbbH",
	"LB9OX75mOewYt5ZHE5Lc9RKigPMWzYgVsZQcplvq/+eH3ySY8uWDz76iSsfn4JmcIBUxXiGukOO9jqja",
	"8HjL4hoVWnmsoZUzmKprYDwH1C6ZrXuX5Nn1rXhXCeopcJNpyGX12iYHpQ/8lZc+e1caBFNmzIRrnyeP",
	"Xb+jBLjGTNFpcQOAaeAx6FCnvujS3NjEoDzPVg+fS/PkhPiggYlH7lIgDxCSSvhm2PuuTmJUqKgxwohn",
	"kw+IwpbZefmEj1nxG34NcRnYZgNob1fvtxAEdJBAKeLkPdOtgkjpGOJyOjKmVC+n2fiUrRKutpTSUMzw",
	"By12b1JUqPHhrYpHLVbOOSrWvKNVWbJEEy5kM4m3VGDtW/XUabETyURM1+2GkCg5xvwxLrFFT+WohS6t",
	"fXX4Vbe4CscN45JlPrNWxK202E5Syj4HXcPLGNmxqNuW1ZUHYFvQIN5L3AUJ+qyxRypoD3claH+5plso",
	"8/ow0jW0alwdxznN39qFRRdme8zmXA43xmU0UXpVDKeA8aeJ4eTw3FZDGhr+08RwCmL5vGM4SEV0eZwR",
	"8KKCyhj2noa11NWG0VsGcypE8+iDOWmx2p1x3dbNijrFviNe/jRZIqt4+fNIEinUcyC/J4ZZYRPoslQZ",
	"4TbTxVyuOZ8xNRoZsHfg5SIHbKXWLqeK7UBth+ketd7OYdIcfimB9xMp7BySW+LyMP4nUtkFoXzeOjuO",
	"HaOH3awwAMsE1Yqv2yrpCqE8fi1dWu7umO3T6OldsfAn0tSrWPizU9VhM05Xay6NQ/792fcAq2qJBO+P",
	"//wLoOxzKEyK3xd72zKBFzP9SuoPSuq5c4kFdhJh7B1o3kQgYVXi2Ll74Xkm4wS2eaJbnuZxmJvnVFLH",
	"TJRlQ1xY3pv4WmCFuJRjRZRHkgxoVKYj2JKkajxtPJ/x1FRjG08Mo7WwP745ZUIyT7zhmpBhnI00mMlA",
	"Fsn2dDRZBND3lu/L7GPmwhWk9pha1Qg5HshSFUUNlMcAcSgz5RFlJmpmQqHCcInKRBpAUpH/gXQPJcyw",
	"KhxLuIxNURrKl2My/jrWxao8CM+q+TvnhJUtZ3DTLH7ux3iljRaYp4c/6IW2TySKa+id62gironUNVAB",
	"qU0uxFGJKdNcb/aNFFZwCx9DLart9F1xg4epdu1c0uzn4Fth15CSr/oW3cvRvJdmsFxbxlk0yeQVxIzQ",
	"FnInSlgO+FzC8Fr38GSotC1hee0djCEWhrr3vUVhIq6xzpKQvVSrsQZjVu6s25kAj2tNB4/K0DKwznZY",
	"0vI0nO9bSAP03oIc20mVhNZbwd3w+QeK0m34+e2uJQtVc0Ml5evdUniRej2sRsFW+z9VceRETSjdq/mM",
	"mIDKCfKhUUlmgQ3nFsLqxwqMP/4YyMsKSi4Z4doXSaUKlVTAi8Z3CtkqyxMmJKnoxQECVMNINRr5JE1B",
	"xvTdC7fYhoKoNEIBsSr13NsjayepVWShvmJqPslQSE7RqQWc3fH2VhRBaiE+XiS7vOiakGwRFss8eh8m",
	"e+RRQqQfpGlK9sjrjnJsLMXG4hrk8lnAauF/MBKSJ+Knlgb7Hdi31oB47WdtUi2HD6zHw3zx5+t8v0iU",
	"gTLWZczSbJgIM0H054TxPFHDc98Cop4IYhWtvBr80j1vV1p5YqdJFRk14qAK7m8v3r1Fn5VpkDFgX6ED",
	"lYLkqegjchfMnIgnXLOT0zcMbtJEaZSOYWcqDbuaAE/s5KfGUscnyYzPsU+br7DuoJZqFTnTQhimMymF",
	"HPfZe2UxORWkdTTnZBJV0A8Zql6GskSNayrBfQP2W7+ULdI1TdFQvzJsiSfiGpaOr65BuuepVkOohWQF",
	"GU3gxErV5ZTdFCIG0yHEMQlrJEpUEk5CDTORxFjElApk4nexMFe1APxAK/jOoKlxLyDWdMNZKHMyAebm",
	"cwQWFzd5qvXohcmfdRk3WHa9FnbYNaGZCL8+fOb7+ZWqYU+4KbJdh0pZIceYrkfdCvJbEFT0BGJCXakl",
	"QTLvs0vqiX3p8H6prqhiPeNJwlJuTJddxjDWPIY4PJFzNuIicY+ksj/gwi/ZEEYK62kryxzZOb/AbMoT",
	"9UWqzwg0n4QpcG6sII4QcfAzCJjgrDzbwSLeY2FYt5A52C5T2jFGAtzQvVDCKnUKWHL3eSxWce0tlaau",
	"L/f9VkU8cfR7BbqHKzZuiEwnzt60Nj06OEjcOxNl7NE/HP7DYef2+9v/HwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
