// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3bciNHkiD6K244Y1bkES5UldQzTdrYGusmlbpKxSFZPTMt1IqBTAcQYiIiOyKSKEjGNdk+7AeszQes",
	"7cM+78Puyz7sN2h+QV+yFh4ReQEygQQvKJZa/aAuIjPj4nf3cPf4qRPJWSoFCqM7hz91FOpUCo30x1MW",
	"n+JfM9TG/hVJYVDQP1maJjxihksx+EFLYX/T0RRnzP7r7xSOO4ed/29QDD1wT/XghVJSda6vr7udGHWk",
	"eGoH6Rx2XokrlvAYlJ/wutt5KdWIxzGK+5/9ODNTFMaOijGMMgMJiy65mICZIq2JK4whRTXjWttvrrud",
	"V8KgEizZBXDcTKBRXaECdC92O99K81JmIr7/JZyilpmKEIQ0MKY5r7udd4JlZioV/xF3sIY3FvZiAlIB",
	"9+SikdABRl6i6NhP/Ch2kmNl+JhFtJxUyRSV4Y6ymX9CfyyRQpIAu2I8YaME4fXb5xrGUoGZcg1yLlB1",
	"QUtFZLKARMbAdIQi5mLSH4oTmWYJ8w8H9gEeARtpFAakgEE+LyRcm8EEDaCIU8mF0UMxn6JCojimFFvA",
	"XGZJDCNLgHEmYiZMfyg63Q43ONOboPhaxvn+r7sds0ixc9ihge3fo5H88IZ92DTKnzF6kr/ORdvXPR2c",
	"06Q/hcm1UVxM6LlCC6VjQs1YqhkzncNOzAz2DJ9hp7v6yZhFDnf561yYP3xRvMqFwQkSW0yZntbOm8h4",
	"eYgnjzvdzowLPstmncODuuE0/xFbzqyTbLJKU28t3YB9BnsGleJGqoUl45mMMelCjKkjIUskFv+BKPb7",
	"daC4soTcFhrX3U6QX53D79wCHSA8nKrY8rt9nw8kRz+gI6FjrdG89Xu6I47yAGjmqBez1CxgPkUHGHof",
	"pkyDkKCzKEKtx1kCkRRXqEgULNDArz//m319KMaK9hZDxARMFC6AG5CZAe7GS3l0iepTYatAXSsUYabZ",
	"bCQYT54mcvS1p/4lGqR/sATyd4HP2ARhlMiRhejUYyUHChDsB158/eNQCFl83IeXaKIpjJWcwYClfMAs",
	"eejBTytruXbgXV00N0mdeKinWPd2t0RotTSaxdwcR0aqVRLlcQ1t2lcfacg0KuDxEe3/iiUZgpEw5olB",
	"BaNFLRsmcuJQVx3SUSwf01A0riVXzUWEMEIUEGOCBuOaMZd2zuPmPb4QRi1q2DAK7FldFPYnfchFTz9L",
	"raztgtXefbePmg0yC5xXcdMWLbkw0AttcAbRlIkJwt4M9bQ3l+rSKsoZnyiyAHS9IKMJXteDkX6GEU65",
	"iMGvpAsKtUyuMLaCUiGLPZHWraXrfyQUOPB7yHfJghjT7iEiJWutGlK0LJpiHOQH/CAzsruY0HNUGubc",
	"TIHHGhQzU7TcwgSMGU+csKrd4xY6zrI+E4tNID+V0tgtVLbbXzNgGxDnc/fhfIrhT7i0IlMTMORcWBVl",
	"4flIA4+t2HZSnF5gJjwiggqYyUSMTqxoNrPjipgTSQDTUBBAA/SsUW4WtTLPPXKwanj4mo0wWd33mVXE",
	"UgHOrBRkGqRjVrxCYY5AZ+qKX6HbtJLzR9oRDpeiFsg8bmkcCJyfyvnqek7ZHL45e/staMFSPZUG2Nh4",
	"oDnkHgESMGWQHrULkUnccvwRjqU3NVcm4EKjMp4KEm5lf4wqB0jMx+Pa2RXqLCFiR2FNqe868rJj7Tae",
	"YFmQlRRAkEdntVaTQ5NDTcqUXUj+RTdXVoRpjhrmU6kJXxAxpewvUiDspQmLcIbCdCFlQio2Y12IZZS5",
	"3/IRv2da84mwv+734RRZTHaCn98OW2BHxGsFEV6hWpipZRZMNHaBiyjJyL5jxYR25WrhRQ0ztFqW2LEW",
	"+Q64IafDmY5cQImsaxlmVYGQAOoGvZAzVI6uRgVzwia4ql/smoM6bWMulXRVjbUk8IN5linttHUV+ydM",
	"axix6NIy6EVEb13kWLdfQsom2Idj714pOIAZMqGdTJozR68J0/5NS4ybmVTh2GnS2MkplpxUILBCxdVl",
	"f53NmOhZLJK1K9gMdb5qqzm40DxGcLw6cCKha8UsxjDsDLODgyfRmGMS0z/x0P1CJon7ZdghmiGNPuwo",
	"meD3PD784+jvv8TROOr9+vP/GHYOYdj55b/98r9/+V+//M9f/s+//+df/u+//zzs9OFPNM1o4U2cEUYs",
	"0wjMS4EYaGYQiLEGRqu3BD6SZgp22bmoZErJubOW/Cf2VZZYIg7Eax9ecuH0hJBemPRo+4agI8f+a/sa",
	"qRE7M8Z9OBbArVYeScsNTkXbGbj27nSXuNAUMmrMksQTjJGgp3Iewjc8zonEUr/CZBH8rGdnfwb8kEpl",
	"ujCf8mgKqbK+OHkXnt11hdMClyxxWuCLenYy05MicrTCUxUCqiGwBqv/umGqU5nUMC7XZ2QtlAYaSZkg",
	"o1BWEdiyQrfK3qtie4mLm72SZgO/duXvNNaY7ZFW43MK76xatdFU5jLiX3rPzk5f9uhVi9+Tt2fng5N3",
	"54OT4/NnXw+ev3j94vzFURHMkyJx4jqS8pJjCCXpWjPEWgq1e+T19gfX5PPXQ1uKkWTK6oNzmSl9hm5v",
	"7SFeoGtLVFlpcQMM28/OLTJvIxlJnf/6X/4rxFynCVsAkYdTmCyaenXIBeSLdDaI032aTHQmgI1GCq84",
	"uRVBGtFIh+7NYYfFMy6GHbJK7QMrV595c5awMuxYZk+s3LPWDJJpYWe1n9hBJvSNdO+S+GLw7pWTDUGq",
	"0GROvNs/50qKCQ3Sh2P30DvO5CFT7IKluYJCN59VUt4pgRGauXUPre7QJOKtSKuVaHb4WqnU7WjDTKbL",
	"VphV/VfW3Rgr+SPaj/yM9TaZNOkLYaVzXE+81sa3227J189IsVhlPpeqfJxQZXKB8/BOxZhOw4/15u6W",
	"3ywJ7fIA3coS6sT4M4pZWunauIs7EaNVrpE+bHPkjfC4oCfHPxQakzNuLEZvHmVxrzXv28rmxn03i8d0",
	"W6TeUEKtp8qKpqa1lr4oLbJu+8+5ttzw+OVx4/YjGbeYmN6qncE7IzXRKTh5/hKYMS4qYWTZf+jDGSpL",
	"EEz3uHZk8TSRozNjXbsrzoaiEpdz5zd5UO6IBKqLm1JMxMnXaCqtcvThUTrBcJJmacvbB/Bbu8nVha5C",
	"pdhkJWp58vzlkTsgi+3uq0HJKcUhO22c0JtyEDlb1dGKqOXSntaRgeO3mm1bU9hu1ho2bndhNo4Wv0k2",
	"uR4Ez1b3V3C2CtfbCYtWu3K65B65pzSBO7penUFhJK1L/kzGuJVcua6dzzrQN0MS+SzFEzrM0OVIy1CM",
	"udIGsjSR1gogHnTnrn95dVKQtX/etS+IICC0O/JQaDIlMHbcMUWFboYJMzhntLo5U35wFw6wkiVihiVy",
	"MhR2jX/NMLPLLZ+r/CBHR/443AE6d/TIPXRe+Xwo/JDBPaOhYvhGjgguZ2cvQGejHGZVG8/rODq3KSu5",
	"0cK5em6NNPaMxQiZ4H/NkIwlkmbew8zSNOEY1wmuTc4WfnBH7Sc+VvRO1Su2VWZKmbGfdg47//G7g94f",
	"WW/8/qc/fHH9d7VCZ4vzGnfk1Xxqs+fIiPyZI+ATQQJ8LNVQlEhvvw/viGicS0xjLJMTEPF5qBW72Stv",
	"Z/8//N2trYx2goOyANpKi25nhlr7kFULSVK8Xzf318gSM62ZfIrR5W18oBNUvVRJOmnQWWKOIFWYZwdQ",
	"7O9HZ9HRWxqYsq9OuDaoKkdGJYsf1RWP6oGy6g1QTFZI8z1NRs7ARLG4wRvwvN/ikM5NVKymDqzfyFHz",
	"wXGjTrqBqUH5MW8aCaLRa7/kLpVmXUTzGzn6E3fZL6mSE4W65sj7pXIBV+uglkToXKpLOllxHt/eQb//",
	"+X4lLjlOJMVrZ+yDS0j4vDY5QWSzUTXhoA71kxoF9UwypbE3UYxbHZFOmUZI2AgT0GiCoHUHeCRXpUCQ",
	"46EYdsZooikXk2EHBjC0kpJ2mf+QMqVLj0UkY/+n/dpu2wKreCORce9b/+9A4/S04SyoIOYN+DlzL1q3",
	"gM45t6CdOpuOqKIbzqH9Khro+0+egqpA/2cKLQbtFcsZ8/b1D3L0SIPMTJoZDSNMpPXwZZ8C9Y5hc4vS",
	"UoWV9LWMWuy6xOs+qaTT7ahMCPcvypnAmHzFNUcz5TSHle28sQTJEgi/SkWq3VLK67fPIcErTPrwLD+F",
	"SRag+Y84mKCcoVGLobBAdDGO0Uh+6EIpA6ULOcOT9Hv99nmPiyumOBPu6CXhVzgUPoLrD4bCYutU/qeR",
	"OXSbpJ5KNk9j/g6ds661xKcsSVBMMA+31hwoxzVC5fzt+QlIBcHQBq9jNyji6nTdZhufVt64bB5bk3PM",
	"seYUyR3xSgUld/+2QYoVGZFPvyGU4LfR5Kasgr+6l2AqkH3w+OWxNZjzhdQd/j+AwLlpmL+U1TWXLykN",
	"4HTNVlZfqolN1nlrb9AoHp1ILmoIp0a0vRP8A1jVoA2bpcAFaIykiHVZSccyGyUlSiq08VXNKTaz6t4d",
	"uLUZZNli7thR3zdu7QzDeWx1b0lD6gO97hX+SkTxRFkBPcVMw4xGdy/WYtY/ubktfMrm5QndeH14a6mL",
	"jhgTVEZDygQm/kTSTHEGe0aCwSSx3goXE7d6r+r2jyCaMmXcV9p7Q/RdH966IKkjO6LAhhi6y8dtfcZd",
	"prG6EEJFUhNa8ilq8UpKflU6bG8G3/BgcZfObaNbu5x9CJXkw6Fw2YeFL9s+D/GOPNvbG5d66xAhkYYL",
	"PcWrFPKDc682GMfkKwcSW0vW9NLyot2nXZqscYnvCDLromNWs5SDYD582Qf3qYZZ5lIEKD8gBDcovuXj",
	"YUxFU36FZBGWXCxrMmbCyCyaYlzwvB/GPk1wbIYiEz7loc5ibEHB3+K8RLw52YY8KodyiBJkSgM3/W0J",
	"r06ZhZhUTXYgISgyTEyyhKk80wn2Xllb+8kfDqyo9aHE/SLMTycKJIuGgovy6cIj7YL/vUxwo0GnLPJx",
	"xCuOc1Tk7/lJLAqHnaEwmGAqrdB2wboZKmanSKUmBeETp0SMSgMDnVK9g75cjOSHo6HIM7U0aMMWoKfM",
	"rpFyLu2AT57T3KAlWIJM7atAH8XAxVAgp5xMuxprGl1xzYmCgnaT9vEdHWbEOGZZYv6V1aTbPXfPgOpi",
	"pDAsCbBYsDnsKRZzJnTXOtlJ3CPIAjNMPN6LufqXLsRc/WX/aCgO4B/hs7/su5RkB3RyZYps+BwDMkXh",
	"81RaWCmtT2IC4m6dn37DIx30ZA3fnHw1OPn2q92e79xAwnc7CzZ/Ox5rrLEtT6VxWQtMycxHxx0PPNLw",
	"r8A+cJ1Txz6xZsInwgm9gOlHGvgsTXjEDQw7QiozHXYKFimzL/uAbUmizUnWem1VopUyDCqM8n6NSLvd",
	"oVeAjr6T0wQLTR+fKZI1f/3534aCm5CI0uKkYWvmufnx3BLZbe1jtLdA8mORXMMvH6+U5WILWbQtlO4Q",
	"BDWb0/oSF09xrZs+TuS8IevcJWvob3RdCcZJNkp49CdcgH/N5WRb4hbsik+YkaofKaRwAqtzutas+Vn+",
	"3QbPoW0oPGHavNONX22RAeRX+JySjjaeArcLLK3EQezbIkuSDdGd6uiro4zHZXG5NgTUtM/XXJs1MZ4S",
	"ftv6l6sobnVQHdYjJ1y85ILraSPwrRZVFij1lFtLnv0Jmr19f45FpFxbtdnELEsiyL/XXVrK++Z9nfoT",
	"gw1bK1a8zd4cy9xie+s4pHbfS+us3Xiwj+8kONDaCMwjSatHrtZ1azSrtpXsyptHrfVlxJwmaKU2NlqB",
	"N7D1vIcRdOKruL74Vc4TrqmSJLfXeeyrFHKfh1JPp3IugAvYq7hWLuAaStKCF8SSOVu4b7SrOCkG2w/V",
	"KC7ddEpdFKh+xL3nR18qe21BC2tjW7VmY0EjFRMxR3bA41qCL6zDhiDnp0yabajoleBWNBQExHKy2nOl",
	"nVMEl+ibv0MHy3eG3AKgazHVZBc2Y+oB4eJ63c7+bNHEE24WTXtM12HwZZYkoLDgd9YkGO4UbeU11SHu",
	"LEKBTzMRJzXW1xkXkwR7rmKQ3sk9cx+PcBVYr6i8LRRMOk1s3a5StR43GqJM0Vnt67fPDyCkfcCeT3eh",
	"s639roVLJRQkBfBStU+AWNFQwKc/BR+Yq6Eo2mzkJe053MsV//WZKBtr2kr1/3m6ZY29//xlXmeoK0m8",
	"JPmLPN62rQfyPOGa/GcCgouqb1GcV2roUFdlErzq5nhjTri6ElNc2mApbDgUIf5HZzlMg5GTSYKESZZQ",
	"7p3JY4d2V/qoQJ6mzIE8MhgqJrxatCSSM5KdTm/R1yGPrdYBIp+/vc2e22o14xUpHRtGOc9fXHHZS1kh",
	"peUtEUItx6M5lQkWBWn6PsoZlsXQ0kgNC8vStXm80qQsM9PGlEyMFJqWXul5GQf3ftLWOqv0nk7kHtAZ",
	"Vg7443jGRc3JdaZR1ZvS9oPQqUODq9cOAqccq9sbW2Wr0VRNoO1INixj7R7u4CzujoVB07lc/vUZoejU",
	"WSI3Dbg6PBc5Xhb+FLm3mnkoxgr1NFn4NHaMKXl9bzndeP9oJWbtz/a4FfRzlqYOu9zlfTEQOC+f9XHt",
	"s8vrtPltOGaZyLeg6m2OPlcBu/78cyhK9QA3Pf8cigTHBtaef7YTV7ViVV7iuhSnh5SS1GI7Dhtra/5u",
	"XV/n5rhhfV2lXK4KUO9s6LwP0SNNRad6C5m4dbmnqzF4yQVLQk/A6lYaEyxbp0ouAXZT1qNbkXOg67y2",
	"Ta3qGteVZ35+vrnp2vrFnWFDZ4BNa2uI3cvVY5A11XY3hDtFe+jjfMK6HZJnvbKxDy1PhxYt3/vxJsde",
	"Hzp2Avvx+7r2DhqjTHGzOLP61y17hEyhOs5MbUoT+2uG1YaULveg0KTWeh2Edluk1ymBkUYtljs1JnXt",
	"L7kYy6aDJDh9cXYOOlNjFhV++bGIFS5CkBAVhAZ41gnjOi8CsxqWciKs4Azinv6ZSo2uGxTZH0dW+7q2",
	"WDqcmOb52t0h9f/sgpnLMetC6kLzXaAuYCzlzm93+h7klbXcQivTyenJM3psXUKrvbCXKvmBquSsX9rz",
	"lSS0tREXTC0ozcY6dUNxXjq/5Rp0mnBjx5Z2KT7DXh8OBcCvP/93OC+V4P3687+FpHFKcNHleEaenEK1",
	"b0xcMTudG+SNizPQ/2gQK11JR1vfk/IQaIsJ49QVqFyqa5fsDC8Y8wQ17L19+g18Bm/OX8NnYPCDyRTq",
	"fae9g9FEi7CWk1f1FmNKZpOp79uUiUuMqwVceTPRvFIvS6hjQVEu5jEvlsqKz8ttKWmrzm0v9XMDKgAJ",
	"ZYbB/qjWHXdBZb7BQSgtVl2f9+POa9zDr14/LYdpSO/7M3ePVofmuSz2RNAR0oDlk9idnpJdqNCXIoxK",
	"6ULcYpMlQzHDmDP6ptq2jYGzrHMqufjqxXlNVsmFC70rJrSnG0+vYOl1AUbaAWCJal0VpgW9YnO4ILd8",
	"MEnMuOdo+aILp9b+6rE5s2Czy/bjgDbUTOLFOXPJCXwWrMGIUQVOf3XJP8iRHvzE4+sBdTHTbtUMLixx",
	"ud962ihkswtrpFM5pmIzdOxU6n/sDWsmQDqJ5sRTWaBd1Em0i/5QvKDjBbtYIroLeuX/vwAlM+N69+Sp",
	"wsmCZJHnlBRVj14aiiJUcAQXXxw8uSj1zAjClWtw7X9Dp2ZKsXPJvM4c63hB+JRFlyhi+MrLveOTV51S",
	"WVvnoP+kf+CO7lGwlHcOO0/6B/0nLl1vSlJ/lSTsr5O6FJ/zNVRSJZB+Ff1VFGO3TAPWibXKk3DzKu4c",
	"dr5Cc5xyCt/pkH7DLDYtf3UOv1sJ5H593Hv85R+C2AZvM3GqKmDG/tvZeMGaKtSkURl2S42bV2zAn9ww",
	"U2QxKTE/EO2uc5MvX41730qBvTfMRNO1I7zvVvuVPz44WGpCvcJ21S7UucXgH646gitZ608LTWTJ5vHB",
	"H+palyk6rQng3iNghMj4vv3uycEXNTml0ljRy8ccY9irwAFm9r/oYuCWKGiUL9wodVGDHDCDvEc4GTXZ",
	"bEZg6JyRMHAl3naVPRbHCrVV/l+9fjooaVwLFmY9jO86jgs676+7hDYKylUo82tk8QbSvAuqa8D8Uis2",
	"IiznO98WWk9Jf5YGhL1nHm6vUUysDURYITkuM0N4GkmqsF0B3nXXy5Qs5qZRllCXT40YTnepP9IRMLGQ",
	"AqmxoHsqfcEEV9Qq0DfufKRDUzkfHvNRze9HC4imjPvCe4OCCRMa3UaSutWFbDkvbrsg7Arc7wxydPbB",
	"V+M44Uy7OVTIyn3yYY+2MVpY05AaGu734YRNrHrgGuxiqLOfMw4tAHwjbN9eNGUTDOnATj66zk0C5+B7",
	"rkFCRsBIXvlCD2uUhqV8b0ESS3RZe2THutMJ0jZ9eGVc7iwUut9+O5hxgcCFNnY74ejdmpa+I6wzRjRa",
	"YBh0o2nXD5UZGHbyZpR62IGxTBI594B1beYsCufMWtRJEpqvlB5PlMWKs4aShFoIp7RMI2EqEx+0qbLe",
	"a64NtVvcpA1ehq7G4Mp3Q0i1H1TCXzMkYei5kwqvNonypfOhDywy4Gqgu1DbfHjNbCEvYMvpfOMJ13Jw",
	"ac6GyfJumJvV1NKXFlmV79oFz+sHM/JGQy1lMuXNNAsOThVecZlp4qMjahNVaqE5x1JrzLp1Od6sX1tz",
	"mGBVHU6QCoC74NND4cuDLkQJm/kA7+ODg6YlJHxGFF2/AleCG2rlHx8cbAjLbLYYbn5tRdE1tcZsePsn",
	"p4EONmug0q0r9Mnnmz+pXMNBHz3Z/FFxvcp1t/Nlm5XlF55UdSP1yjVFz+hH2umCICvLKpDk05IG7Ef6",
	"qlELnrEZevXk2udQF2kdyZTa6S4LbjKckc2c+/zs7M+QCcOTSjNvrgE/TFmmrftR9gitULbsAMxY753P",
	"MO+xJTPj+pZO0TmeMx7HCVrj3anTw9wyKz+yhk1oEDiVSal3jrUNQs9Rd8+HdXNglI3H1AUh786j0Hco",
	"rZP5L+gJUd6zsz832Fo3Eec3l8y/dTF7Zphyqtmhhbo2zH0f9NjLWCPD01wUe3FLVtydytvNMo1CAJ7J",
	"mjGwIrMs9zhu+u3KLsdAhf1adPwn6bEiurru/3sOu8uSbEC8pRuF2VMKVZRk0SPfAt9LOGtRm0wJb/KT",
	"kUiGZDB1SxZhxIS1/53pOEPqamzo5bwzxgRDzlWyABdUdM1MRZg1UyT9YmslL4lIbTgdoicYkeHdh7NI",
	"ptjoI6C1wZKFBZy1MKpiueQqFLb5WiP22EHylvq6fY9yd2fIalLA35Qmt9APqaRS6bw5VR6ZtZT3SINO",
	"eISh+W5LLU8uVXPgrDy8pUZP8d0gN11rMvJZHe3W06HPEwwOHrAowtT183af5QqSlHySkHNHfhsq9NVd",
	"1LnfSMtVE3fAXvpxLNUEScJbl3WuON2jImLgxvKkv0jEsOSSylJLnXu1nCH1M7e+Ox3GzjXMp8yQd112",
	"9mQSUykbM+HujWA9ME35kIAfuDY6d0CThYPEsjHkpIcmxuW6bKT1h6KGJcldlqrMpO62Ea4h5UKEfAyH",
	"I2cQaHDXlklZMaYm/ApDwrmS88NCJrl4rvWRmYFXEPM4tHxalQVvFq1c2t/9zd/9zd/9zb8lf3MhM1UW",
	"QmvVj5kOHo/ZIHatnH1xrlmNXp9ITQcrmZk+HjPf+dkHplGbpzJe3Bn6VvtKX1cTFIzK8HqFfmqODR6/",
	"PAa/tfiGKCylO5B0LSc6fPfeknEBfr9wOH97flKBupnWAR3FNjB33XzvCeQrvYhbQfzgPub3CXJ1nCuc",
	"CK7WvGrYc9VhUkS4vwMsP5NizNWMsOzP7yPkV8vLakEA4YOBwgkKi/rW1HDqPz0tvvwbpoxjoLxa6tMp",
	"xyAfBqEUuFlZiMoNzLz2h8jJPt5vQTkaTZa2pRUqH+jcI45W6hNqUETbc3UI8Bn4egV4d/raAoMuwmMa",
	"/ul0/xaa9o/1CiDcHIb+7o6tcHii5BV37lPopAalrWxAVX4P5kY0vfapb/fBwpUekTtm32pjxxq6OCtn",
	"BdL1k4x6DuQtHz+CtbZ8EWokM3dbzY8oBuFSGqncbY5gpkoak1NWTjrlm9NhtHB3Kg5C1jB8BuUmCpuI",
	"yHJ9e0KyL98jLX08bVBNot9ETrsjneuqgeDaWHtKdlRS0PNGbMvMtEW1fbWNIfxa0s1N9vVd6L0reemv",
	"0PTKzcegNux9Vo6C1eZ1ZWb6Bjv36jr6y9bqVBiFwgumjik9YBcWp4ciZSPsUaWCFR9FneL+RsAOipvV",
	"Bj8ZmanrViT2Bt9WbmTbFG2y71CCCgV9Llzu8IWVlReh/vSiPr3OuNFvk+hUQ/dvmLoMon1XcqAtVu3a",
	"6GCVArg9lVmplZEdNKbOLU7J6EuephhvxnC5m08LxJbu97oPRVF/u9lNHfkwTriN82Fi1O2ZYi8tdbsv",
	"CxgsNT/aIAJX2h7p+xSJdd2bGqSjr6Xyu9I7AHlxLrMimMsL2RoLlDDu6NCq8pocxODBKeyxSo74IbDC",
	"mas00fIeSNf125xzjf5IyRmYgWZ8qz5UV6ioKYM7nhj7k8kQUbaDasMM1p0QuJ5ijfRCjZU2Z5/yeHuR",
	"fPeipLZN2m0kySUuwt2SOwzs3iDJtnXgkTbjLyTZzA6l+IM2mPayNFDxfktOcT7JCNu6t+WOa9REcAcC",
	"q9qssEZi/TOO7NpESD/Puw9+BgzGiZwDX0l2tmPmNyYkqHOgejN/L+aaQj2uYqHguO0g6wyArUHrOr51",
	"7pUNa7rmfQJO4O08OrfdKqqPfCET9WuuTNgO0aHqa3suCv39Hh4jUSY9Xe5Ux0n3bgw47gxYQqFkklBn",
	"o3DQWuO9bYms7Rmz2o3xfnmzvvPjjtmzpilnvbWoDXVF8jDeAX0ssXFBIEduLTqUg4SFbyCO6l3jm4z2",
	"0tu7yd2q3K3fIn+rvMJdmUU3svVLRTSh0rmwaEpYoTSdTYrXNX7YjL9T3yBiN5izs7XBmVvVg8WWi1UV",
	"yKG/m9DS3SxTCyTcQ8Ri5RbzVoLz8zuNPTq812Qcuxo1AuDDzl+pPYez2/JX/4fTOErT2zK+QkAARlBY",
	"oaoZE2yCrdjd9xSq+vdrHGgiO9+qdbOL+fyhu5bdzhePH9cUlCy0wZkDbpGvmTvKN3BIGQgpero0bmuk",
	"tQlP6ICRLQIUKdVOr8oY+3Mttu9e0Ky2TtqxhbZO0LjFlQXNpx4cOUU6b70zqbFs96VZnc7KzDI1VQ3A",
	"+6Hu+yDX5raYD5psH65+vEdKp847ntQfVWzhGxK+9ZHbWMfv6L1WVXbFhdg51sO1vK5Pd6fbcbkWdEmO",
	"0z7vW2dwc9dyOSjhGoYprsV8vytz/p3GViU0DowP1pwnaihREv19C3M+UM39mfPl5oEfwZxvSiUI5nyR",
	"QPBJmfMvlu8Ovhuz3uc3VKmL6ohaiamaM7s1Nj3R3qu4lUV/JsemF3+qZj0m455hVJslFSRMmx6jhsGT",
	"jKktVUwJEk0Ic09rBUIbJVKHkt3k97y7eTbPAzMEvkLThJ1mYX0Pp8EtnK0yzu/L1dpaCeyI3rzNmv1m",
	"6M7tyJNeaKp7W4k+GCvEH9tVRnhqeum+uK8Uh49AKy/JIN45qdy7PnGY8hTThUueJL7FB1d5r+oVCnIU",
	"sQUJyblAtQ0FvaUPHlaOTLVRMNdvw6Zqrvuv9CP2b9b08v1NysIlU9tVjvvbSZkARwttqPsG9PwVtSej",
	"exnzJGiaEMYJm8Cer2OfZdrkNvMI82VtQdIK6cxyG6I+9Z/8huSi39KOleh2QRlaITDQJS9iS9O5iQgy",
	"sb1yfBe++Q2RwbG74O3BEkGAeZNVvlGhLTcxbmwX8mLGjYYLeusQfpCjC0pBzRtp/CBHLmvUp1L7ftiu",
	"mxFEidTUOBN0FkWIMcaDMeMJ+qTU0CQ9lUmi817mkFEBH111ImXchxcsmgIt4ZGGi5gZdngBKVtQs3Ou",
	"gVGXZeoWtnfJRQyf+ZupKfFivMhbfJnFfl12q3MZv5Ej/Sp+ceXvd/oIxLzSQbo9NdMdNzWpa2cvAi72",
	"Vka/fWdbyinunaEw4OAWJhtLRemjpftSfqj0t7UEWKLHGRrFIz1wwdfGRq2oZXJFZa4x01OqJIGUCUzg",
	"1XMw0ic596iB3ImSs3967SqqM6HpbpsJ40IbeoRmipm/xty/6qg6QXaFoQs25Uy7vjS+Z0x+Ezngh1T5",
	"RL3Qtr8YmLrdXNDaLmiAC2XZ44K6mY6kmbq+2mSkhGWVV0+XFvYSro3u+q45eX/2kvFxdnb60poHBDfg",
	"wtphnNiNbisod4PyjbxDbuHxt8+XrIkjf77qfqHu7uEj15J8gkbDFwdP7KieMmg7F8/s7nvPpDBKJocg",
	"ZI901EUzr71x+P4nH2tfWwR0EhBcakFUAMql0qlFF2ZcKdLd4dZ5ujme8pQFJr3Q7R5eCW2sVbWn3a2L",
	"VyzJcN+9pX0WputQSMBO0XoOimPR6t/QtgmhBHluZdwY6MqAZAGPDw7ct+FavJpjBZptrfgIhxhWuvao",
	"4Jr+pVId/ol2v/lf6R//GP5JdzXR4HEvr+WPi/ftHwkzKKKF/4tuwuh23HUOvYJrdd2PvfSPXxa/h8n8",
	"n+6ChOJvUjz5X3R9hZ0zE4bPsDfDmbtNK/wwkUpmhguXlhN+jEp/jGP7iCWojG44x6nSDxEZzLmI5bwP",
	"ZwZTy0AxKn6FcYWW9v5TgbquRaeIXRsb1xTq8y816EixFPV+U1cb5buxb8br5xYsf7D/efyF/e/f155K",
	"7eRIyXHjGRFyq85swjXKWxBzUGsEnX/8xV12a7AUW+vfiUvh6qK8bJAKMmFFs1Su2Whe6r2jLjuP73/T",
	"Je2SCVI5VBVA3qEVWlaVCCAuh70YDeO+e3ZC5bpd35nbvbq/ncVJLn+POqCXluHAH1gg6HavzMvqnW50",
	"aTz3pf5j7pWdkLudqn0Hwlv3+ZuFreUAcj80n2m6Iyy3zvvqw2KtYX/dd6vAzd0ROO0rXOhYA3Z6Htro",
	"L1+75+4hvOEh5+2aYblkeHC35Sa0MFqNu3M5X2IdoquMUJsvuGzqjjNrXxkJ+fGYm9a1C1U4RoUicuZO",
	"cTFtv6F0r6ClrdINb3CMvOUZ421Q8rwCmXoGazojbADIwd1S+bqOcTsElDvAc/QzWkC4S7ZGHO0ySdIF",
	"ae9TytHY/qLQHUenN6L/YbOWP3oLdyU50vF3m+4JCQpLDsF+a5E3yG8i22wMHOev7iStqnTXfNvOxDvE",
	"BxkS4aK3GKr37q8VgPfB0htwO/gpkfH1ujS/CoLvNUEjR+uDEcRFXKyMSdgjYO7vDInd2mESuT6oudqj",
	"NXRlPajryhoIpXQB81rGL90fuROuL131vTN3wFT2GJBd/nWTY3Beuob8t+YcrNz4XlftmV+h+YCdhOKW",
	"/BaOQhX7NVzTusSoShtbGfsfw3KvQsnCp/Bl1nBHk15Zs/uDuyfRB2XdF5BctfBXhMvuzfz7lln5+B/H",
	"3G9FE5+UyV/QUxuzv60AG1Bq19oSkByUx+7VXWDNT7UGdw8zQ/vWxohDR0V8cLoXnE/8HRTuXkkpksX+",
	"7iVKXS3cWT2J3KNIKVPHDXpEHRM0SaWBcjVV8W+qqOy2NpMrM6OOKndCjuvET6v4Q4H532MQrWMQpqTh",
	"dykm2mB7c0RiBeW/RyUoKpFjdcfS/2OFJwLpxDLKZkupcauC4nn+1i7kQ5jtIcuHk+cvIYcdMGOYu01d",
	"NkiIAs73aEasiaXkML2ny2f88NsEUz6/89nX1Ix+Cp7JMVERsApxhevWNxFVGx5vWepZoZWHGlo5xZm8",
	"QmA5oHbJbN2bJMq2uHl1DRJDI/D1gvokf2sXgjrM9pAFdQ43YCKaUuJko5AuYPxxhHQOz/tqd+iG/zhC",
	"uiCWT1tIExUBA4FzcMCLCioLN5tuoq42jN5SWleI5sFL67RY7c647r6kdUPgxgUYd8TLHycMvI6XP40o",
	"cNH0J5DfIw2GmwS7kErN3cWvTMSwYHOQ47GuXFvVlpeLQ561Wrt8FrQDtR2me9B6O4cJ0DVitRK1gNtH",
	"Utg5JO+Jy8P4H0llF4TyaevsOLaMHnazxgAsE1Qrvm6rpCuE8vC1dGm5u2O2j6Ond8XCH0lTr2PhT05V",
	"h81YXa2Y0Bb5t2ffwRXXfMQTKhD56TdA2WdYmBR/LvZ2zwRezPQ7qd8pqefOJVXLJlybG9C8jlCsvSjw",
	"zL7wNBNxcq9XBZaneRjm5pmrj9VTaWBEC8tvvnA38UHKKhdQfuTTPi0zFeE9SaqSwbtUYj9nqa7GNh5p",
	"cGuBv7w6AS7AE2/IA9TA3A3TQ1Fk07hS9OLce281IW6fqvkuMTVHrjMiF5OhKM5h7dMoQaYwDjXjHlF6",
	"Kuf+OooiS1JHClFAJgxPhsI+FDinLgyQMBHros7b11Zrn2+Zn5XWFXh7Vs3fOXNYuecUDTeLn/sh5qy6",
	"Beb5H3easfqRRHENvTMVTfkV+nvsXW34NhmvrnpcN/efeSW44czgu1Bmfj9t/uzgYapdO5dudn/p1Lr7",
	"qKJbOZq30gyGKQMMomkmLjEGh7aaa3kDPlcwvNE9PB5JZUpY3phkNaLK71snJnMdMUWF1Fz0UiUnCrVe",
	"u7NuZ4osrjUdPCpDh+o622FFy7vhfJtsN0DvNYqJmVZJaLMV3A2fv3VRui0/v961ZHGNGsr3PLvwIshx",
	"cSlaAwrutd1oFUdW1AB32lSxuWMC1xuEjbRMMrqf3WBY/USi9scfQ3FRQckFOFxXrugM98AFhWykYQlw",
	"4VT08gABqmGkGo18nKYoYvfdM7vYhu5GboQCYlXqubVH1k5Sy8hgffujfJIRF8xFp5ZwdsP0zCjC1GB8",
	"tEx2eVcFLmAZFqs8ehsme+BRQqIfomntQoShiRBzF2hN+BWK1bOA9cJ/MOaCJfzHlgb7Ddi31oB46Wdt",
	"Ui0Hd6zHw3zxp+t8P0ukxjLWRQxpNkq4nhL6c8J4msjRmW8JWU8EsYzW5v4/t8/b9UmbmllSRUaNOKiC",
	"++vzN6/JZwWFIkb7GgxkioKlvE/IXTJzIpYwBccnrwA/pIlUlQseZRp2NUWWmOmPjX3LjpM5W2jqCzWf",
	"8sSlOqdKRta04BpUJgQXkz58K031Uknr59H9E7HrfhWulk3kpKbVw1dovvZLuUe6dlM0NKgJW2IJv8KV",
	"46srFHTHrZIjrIVkBRlN4KS2c3GpHViKEeBshHHshDURJSkJK6FGGU9i6lLkOuDQdzHXl7UAfOtW8I2W",
	"t74LtaY77uqtlXY+S2BxkapXhtn5lOv8WReYpjaHtbCj7q/NRPjlwRPn6pdb202ZBncHKcYwktJwMena",
	"F4RrmodX1iQL15Vi7FBnPTqvK5NFHy7cFSwXFu8X8tJ1iASWJHQ1ZhcuYpwoFmMcnogFjBlP7CMhzfe0",
	"8AsY4VhSczxpwJKd9Qv0tjxR33Hu1IHmozAFzU3tAAkiFn7ulufgrDzZwSK+pc5PdiELNF2QyjJGgky7",
	"xG+HVdeZc8XdZzFfx7XURcoSU13vvtcyYoml30tUPVqxtkNkKrH2pjHp4WCQ2HemUpvDfzj4h4PO9fvr",
	"/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
