// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H37chs30u+rdPGcKksVSlTsbGqPVOcP+SLHjh1pJXm3zgldZXCmSSIaAhMAI5pxqSoPsU/wPVqe5Cs0",
	"MDfODDkkRUr2t/kjZXFmcOn+oW9ooL90AjmJpUBhdOf4S0ehjqXQSH88Z+El/p6gNvavQAqDgv7J4jji",
	"ATNcit5vWgr7mw7GOGH2X/9b4bBz3Plfvbzpnnuqe6+Ukqpzd3fX7YSoA8Vj20jnuPNG3LKIh6B8h3fd",
	"zplUAx6GKLbf+2lixiiMbRVDGCQGIhbccDECM0YaE1cYQoxqwrW239x1O2+EQSVYtAviuJ5Ao7pFBehe",
	"7HZ+keZMJiLc/hAuUctEBQhCGhhSn3fdzgfBEjOWiv+BOxjDe0t7MQKpgHu4aCR2gJE3KDr2E9+K7eRU",
	"GT5kAQ0nVjJGZbhDNvNP6I85KEQRsFvGIzaIEN6dv9QwlArMmGuQU4GqC1oqgskMIhkC0wGKkIvRYV9c",
	"yDiJmH/Ysw/wBNhAozAgBfSyfiHi2vRGaABFGEsujO6L6RgVEuKYUmwGU5lEIQwsAMNEhEyYw77odDvc",
	"4EQvo+I7GWbzv+t2zCzGznGHGrZ/Dwby83v2eVkr/8TgWfY6F21f9zi4pk6/pJ1ro7gY0XOFlkqnxJqh",
	"VBNmOsedkBk8MHyCnW71kyELHO+y17kwP/6Qv8qFwRHSshgzPa7tN5LhfBPPnna6nQkXfJJMOsdHdc1p",
	"/ge27FlHyaiKqXOLG7DPYM+gUtxINbMwnsgQoy6EGDsIWZBY/qeg2D+sI8WtBXJbatx1O6n86hz/6gbo",
	"COHpVOaWn+3HrCE5+A0dhE61RnPu53RPK8oToHlFvZrEZgbTMTrC0PswZhqEBJ0EAWo9TCIIpLhFRaJg",
	"hgb++vPf9vW+GCqaWwgBEzBSOANuQCYGuGsv5sENqq9lWaXoqiDCjJPJQDAePY/k4CeP/jkM0j9YBNm7",
	"wCdshDCI5MBSdOy5khEFiPY9L77+b18ImX98CGdogjEMlZxAj8W8xyw8dO9LZSx3jrzVQXMT1YmHesS6",
	"t7sFoNViNDHji1xLV2BaokkNIRsofNfQ1aV0Myh3wvXVTBucFBoaSBkhI7MhNyKuomTkPkiRV6XRHL6a",
	"EdBMzNqRf9CoqiPHCeNRbfs8rP9Zk2xbNtMVZ6lkhOsQxzCTuHkIK8x/7bDA8FuLmqGSf6BFYYgRGgwL",
	"4Cm0J038SlgpFdZPKNHWDJu0pfOLMRMjvGBaT6UqmtJlogucpu+UJHqc/lgzVBmFK34zt6qKDXRLQ6hb",
	"Vi9IX1u0N87iXmBdFlnSi6wTCFHxWwydtLEiiuDu1IKccGM5ur6Eca81z9uulcZ5Ny+ZeFWmrgn7xags",
	"TtSNtfBFYZB103/JtV0NT89OG6cfyLBFx/RWbQ8ySCbeY5izGuDi5RkwY1gwxhCMBAaZ7XQIV9YTsqbC",
	"AdcOFlbdXBmpEG4564uSTnK+S6aQTsiLcTaDwbBLfzIRjKX18rxpQNa7U11zU17deOVhW/uxNNAqVfJJ",
	"ljT2xcuzE+cchnb2ZYU8Jh1cuz5Sel6toVaK/OWE51Jrucaem9MiGLj1VjNtGc5oshfnV9dudmlvHC1/",
	"o2R01wt9K/qwwrMqXTcTFq1m5XTJFldPoQMXtqn2oDCQt6hmL2SIK8mVu9r+DDez9ZgETISFJ2TI60O4",
	"HiMEEUdh+mLIlTaQxJFkoXZr0MUc/v+bixzW/nnXviBSAaGdua/QJEpg6FaHdaddDyNmcMpodFOmfONI",
	"s7GSJWCGRXLUF3aMvyeY2OEWfYrf5ODEh4IcoSFgimY1kGZMTwRO+8I3aZuxv1FTIbyVA6LL1dUr0Mkg",
	"o5kbG7mFXKc6jnyWopIbzOgPP0Zqe8JChETw3xMkV4ekGRHxQCdxHHEM6wTXMuMXP7sw0wUTUrEJ+6Dq",
	"FVubxbSCQ+J8uma3ZM9hBaSIZifAR4Kk9FCqvijga/8QPhAyiFqujXnMACFsM3dklfVPgay2i77bmaDW",
	"bNRWIOTv1/X9Vg6anfRGtq2h2igW+b5x5I2eww13YctFfu9bOfiZu0hjrORIoa4JL5wpa+VLAXJYXLJT",
	"qW7Atkn2PuwdHR5+T+GUbFrDSDJjycg+u+DP97WBIJFMBuXgTnVBGD/58sheSKY0HowU41YmxWOmESI2",
	"wAg0mnRh24GionUsBYIc9kW/M7TONRejfgd60Lcrk2aZ/RAzpQuPRSBD/6f92k7bEit/I5LhwS/+3wpH",
	"XBtU9LRhMeSu1BL+XLkXrRkah6thp86GIFR0U5/fj6IB3z97BJWJ/q8xD8aZtAzlhHl77jc5eKJBJiZO",
	"jIYBRlKMwEgLidRdzCwYiwordGrdxHzWBU/TB/A63Y5KhHD/ovgUhuSbDBmPGtzOYkipMp33FpAsgvRX",
	"qUiVWKS8O38JEd5idAgvvDayIhI0/wN7I5QTNGrWF5aImuA1GMjPXShE+7qQLXhgilo84OKWKc6EIU0T",
	"8VvsCx+VjJlCYSAdbJ2K+TqitJsEUEuR08ZY6Ts54mKh5TdmUYRihNe0c1ErjL2eKAPi+vz6AqSC1LAD",
	"rwyWaIxyd91mm5JG3jhsHloTZ8hdyKc8MvIu7dAK7uWmTnFFRmTdL3Fd/TSazOIq+ctzseLTYp0iDE/P",
	"Tq2Blg2kNnRU2wwWotdTecYCIymS0NhM5aWaOFSdZf6epFV1mqvr8zUjpPduFTbag/NxaSiFpfvCxaVz",
	"I3ALEerNlZ1e2UUmDjvXK6wy+jdn7i1R1mRkpkhZ9K6D0/yg3add6qxxiB+IMou8w9PrFz8VnUDvvlv7",
	"3X6qYZIY2ioacozC1O4n/877g0wFY36LpKEKJp9VYYkwMgnGGB7CuQsMps3YpxEOTV8kIqDIbK2T1AKj",
	"v+C0AM8MmCfglrtjOQQRMqWBm8NaNFSol3pd1f5eEQsCw8QoiZiC2L8Je2+sdn/24xFcKOmd5f08kEUx",
	"M9pH7AsuivGzJ9qFtw4SwY0GHbPAe8q3HKeoyML0nVgm9TvW14owlspo745OUDHbRSw1J/vbckOhCFFZ",
	"71nHtJutb2YD+fmkL+KIBUjRGdCGzUCPmR3jlHv/+dlL6hu0BAu52L4K9FEIXPQFcjNGt2NqhfEt15ww",
	"kjrL0j7edbgunfvGG3hrxv3QIwPeXrzuXfzyerdBwDXEYLczY9Pz4VBjja17KQ1zSFIy8SEUB6MnGv4f",
	"sM9cw55iIWdC7xO6Iz4STjKkcH2igU/iiAfcQL8jpDLjfidHWXEFsM+oHWDykctkEBWGnfp+bcKdi0V6",
	"AStFGnxcIAg2C4amBNH3EmWyBPR+VJ7A8Nef/+4LbmyzLSNQK6+X9cO2c0hblcUraOYsXJZpvs0mfY8z",
	"qhmr1jc4e44LreNhJKdv6sM2bk9Ov/UZXWVkXiSDiAc/4wz8a/D26vwXwqpgt3zEjFSHgUKy4lmk2ypG",
	"GvOL7Lsldm7bCFTEtPmgG79aYaPXj/Ad12aBy1GYdzEOvwgS1am3itOn47E+0BkXXI8bHTqrH5TlVT1H",
	"a9l2OEKztw8KdRIZYnFtwlYTiOZWmn+vOzeUj83zuvQBrCVTy0e8ytwclDaY3iLk1M57bpy1E0+Np3tx",
	"8VqbNxSrrA9VW8u90WBYVeIpr/hbq4WAOQnZSpwutW/WsGK8+ZmK/jdhfd6bnEZcG5DD3GbntPvENWQG",
	"sdWfeiynAriAvZLd7QJ6PpstM5FZNGUz940GpCBQ1ti+d49hgkxoGFMCtW3Yv+dbn8t4a4GFitRZahDl",
	"GCkZPxmzUz4uBHxuBJVh/01Asw2K3ghuRUMOIJbBag8PR4cuX5jynLJ3aJ/j3pibE3Qhp5rMn2ZOPSJe",
	"3C2a2T8tm3jEzazRxFvEwbMkikBhvt5Zk2C4V7YVx1THuKsABT5PRBjV+BhXXIwiPNBjaWBA72Q+p48Q",
	"xGyEh/BGBFESuu339OyG9S4yWdAFbjQEiaKtg3fnL48g3YWEPQqM+lDrftfSpRQnkAK46Wa76SnF8lxi",
	"vzGcendc9UWeYZ9ls2Z0Lyb71m+MLgNLMfU3yzapsYNfnkH2uJTDRJI/T2Nqm3WcpUnVpH8REVzYtL1h",
	"Wczlrmkzcx6bg1EZcHUp4DQ3wUJMqS/S4JAZ4wSYBiNHowiJkyyi1AOTBZbsrPRJzjxNG1lZ2GiAZoo+",
	"J/zZS4JItpBsd3qFlO4s8FZHiKz/9jZ7ZqvVtJfvMC5p5Tp7seKZFjYpC8ObA0LtikdzKSPM86P1NrI5",
	"58XQXEsNA0vihWlM0sQsMePGjBQMFJqW3tp1kQdb3y9pnVSzyb7KI9qnyKh7Gk64k0hlGicaVb29bD+g",
	"zUMykpnWfCRSqVKMO+0NrUbVaMp2zmq4TIexcA73sN9yzyu+ae8l+/qKWHTpzI11g4eOz3legaU/BZ6t",
	"+u2LoUI9jmY+VQ9DStDbm8+22j+phFz9/g230nzK4thxl7tcAwYCp8X9HK59Bl2dyl66LOaRvAJ0V9nD",
	"qlJv8UZWXxQSG9fdyOqLCIcGFm5ktRM8tQJS3uCC6KBpyFioa8pRYuHBgY2T9F0faybpl3Luy9z2JrtD",
	"vxUXTzTY1/UKQmflMyMuh/GMCxalh2rLU2nMmmmd/zJH2GWpLG5Ezg2t832WnfVsHFeWzvP98lOLiwd3",
	"hQ3HvZaNrSEyLKtB9gUp+2vSnWIm9HHWYd0MyT+tTOxzqx2AbmfW8r0/1tkj+dyxHdiPqwN3RlmiuJld",
	"WQXnhj1AplCdJqY284P9nmD5RLfb3s1VlbUBe5EccRc9su12jn2r+XDHxsTu/DgXQ9m0TQGXr66uQSdq",
	"yILcuz0VocJZGmpDBekJUuvrOoHaFxrVLbeSYc/vl3Vhgnrc9QpxnwS4Quf1WbU4urx4ceJ8I5+K3hfc",
	"CRaK8KWymv4ZS40hZBbCYV/0xXVhb45r0HHEDXBhTaOp9FmO+rgvAP7687/gupB2/9ef/04T92jLXxed",
	"+Gy7nvLdmbhl1nFyjbx3zjX9R41YYUjqzDpctK0M8hZVxHhoXfXi8Rw7ZGeIwJBHllDnz9/Cd/D++h18",
	"BwY/m0ShdnTKjAgahLUkvFa0mlLJZOR2boNxIm4wLOdzZ4fns+z8JDJcjArZ49bWKJ4U8GkR18Vj2DRV",
	"56taPh74lFxKwk2PFqSqunzWqAsqET4jwh8nUl2fCeE2KdzD1++eF2MTAxbcpOeMPFuJZr9Ig8cw4IKp",
	"WR4n0UYhm9hp7X16/eq6ZmP/0z7Nk0/iiNzBlJpGMaE99xVa8wIhVvIznXqgFg48lmnM1AZJTMrBima0",
	"r+sWzwBDOlDhG55Z2y0lP+HDbf9SWDqJwr6wgzZk22lQbJrOyotk2PtE/mpvFJnhgXv2ad+Fci6tTdOF",
	"V9ds1HVnMvgkNaUCy0MYI7O49WlbzoDo+KX7nAU3KEJ47c98nF686VDKp1MRnaPDp4dHbisTBYt557jz",
	"7PDo8BllFJoxyakqhe2vo7qkhevWJD50EztgU2aBMzenrmWzFCOatvVrrLincOebsHPceY3mNOYUttFp",
	"QgFTbIIWYp3jXysBvJ9OD57+7ceM3F7Lc0puZMb+21klqf7PBbtRCXYLd3VUrJYvrhnHhLwhml1nnS/f",
	"DA9+kQIP3jMTjBe28LFbvqLm6dHR3L0jFVSVLx7JdJx/WHWAK9eOPHfAtSLFwubp0Y81KsUuVhbl6CZi",
	"pBHRffvds6MfalLJpLHShw85hrBXogNM7P/RxT4tKKiVH1wrdY5kRphedi0MqeFkMiEydK5IjriTTXaU",
	"BywMFWqrbV6/e94bFObZ7RhmbeJfO24VdD7edYltFIwpIfMnZOESaN4H6ho4XybnT04ukFLdlFrPSYUU",
	"GoS9F55u71CMzNhJKCezZGKITwMZzuqId9ft5AbM0yHrhe5orc8PMVWyXkhNKz4x46dD5k/ieoqhNtYV",
	"vbcbd6rnfO/Ktp5lzl2FATV4fnp2Cn5qoWPA98sZULpFqGg5EniKNuOvHy0Och75gcP1+fVFkez25Rqi",
	"o1iF5u505ZZIXjkb2oriR9vo3/v5NZLvXLgwYfmwgYY9t10tRYD7O+DyCymGXE2Iy962CtDaYuVhtQBA",
	"+kFP4QiFZX1rNFz6Ty/zL/8HI+MUKAZI59jkEOTjAErOm8pAPP3Iz/GbkQQn+3i/BXI0miRuixXaz+hs",
	"kUeVDZMaFtH03MYIfAd+AwU+XL6zxLBunzXM/3G5Ll/sR/+nXgGwSCELZ4D+LpWVeHih5C13UVBIb8Uq",
	"TGUJq1xsoA2b3vkowjaWcOkM1Y6Xb/ngUw0urooBlq51fxmdcMqORDneHi0HROF+yPUx9KxmIygIZCIM",
	"uEt7ev7KHjtSYi+YsZLGZMjKoFO8xREGM6Coby8NwMJ3UDxntgxEdtW3B5J9eYtYejhtUN4LWAan3UHn",
	"rmwguGPeHskOJTmel3JbJqYtq+2rbQzhd3I0sphNzE703q28cTdHpsrNh1GXzN1tS/i4Rm3AITHj97hN",
	"VZZdRlanwsYIrHQ1a6JdvHrbFqenIm1G79GmjxUfeeLE/lLC9oonXZci6z0WbuPahhipv4tsXTcvbQf8",
	"/uNu131rLtLgwFqgLSV/7BLMe3O5+ksWSCVLX29zwdQdNmhYO37T0s9K74DkdlQuI7WybIsDWZkLvS88",
	"vHM4tIK+yo2X9HsjQyjRfnlUiocbxqQa1soNziC9eXB9U2nlWFbrMAoNzV8/cm/sc2bUANta5MVTK3RA",
	"aQerqHwQqmYZ/QsHdmwiDeVmJ5u+AwbDSE6BVwKHts3sEoQIdUY5b5nshVyTd+qi/zlK91ei7JCOv6xM",
	"WndqZktqpvnk0Vdgt25mhLrplll9Au5GMjoQXeqwHaPTTcTVV1F6RurxLSTKsaT7mupW0tY1lFudKZdQ",
	"KBlFlB2eZgDUGJwrMmv1hVk+0bbdtVl/em7Hy7PmYGO9CaMNZZZ7Gu8AH3PLOAfIiRuL3+zPB74EHOU7",
	"kJdZkoW3N6R+u2MA5euyqzmzFZ4UR7hh0GfxR3n1j/UM0JzwWeJMHgQucOVYIQuXKV6X9recf5c+PXA3",
	"nKPbx1vwzI3q0XLLudc5c+jvJrZ0l8vUnAlbcKMrF2G3Epzf32u4xPG9ymefrU4EfIAgbmuENGwd2Gm5",
	"eyqyDYTPXBu9otNPRABGVKigasIEG2Gr5e6zuVs7nQQ7f9x1uVf4cmNvcHWar+Q/djs/PH1aczCQKhs4",
	"4gZMCGlggLlvu4bXyUBIcaAL7bZmWhuXXqccWcGpjykPqSpj7M+13L5/QVNNnN+xhbZI0LjBFQXNY0Tw",
	"ahF02iK6N6kxb/fFSZ3OSsw8msoG4HbQvQ24Nh8tfNSwfbz6cYtIp0RuD/UnJVt4TeBbH7mNdfyB3quH",
	"9e8JUjZmimt3wW4RyevUdMkyTuea5+7YeqqEaxZMftvmx12Z8x907an+KoyJjI/WnCc0FJBEf29gzqeo",
	"2Z45Xzw69gDmfNPuZ2rO53ueX5U5/2r+OuD7Mev9lmwZXVPFTTsxtdpGEmHvTdjKor+SQ3MQfq1mPUbD",
	"A8PUCA3l2TBtDhidxx4lTK2oYgqUaGKYe1orENookTqW7CYl4cP6CQiPzBB4jaaJO83Cegs7qC2crSLP",
	"t+VqrawEdoQ3b7Mm3wzu3Iw89NIj1ZtK9N5QIf7RLpnbo+nMfbGTtIDdYOWMDOKdQ2Xr+sRxyiOmCzc8",
	"inxpbq7SbdUqghwiVoCQTCtZtkWQK325LQCtJ+jmK5E2luecP43u36w5yf1NysI5U5tFEar0ImMmXKXv",
	"VuheA8+vFRPG1fDI8japQxhGbAR7gRvNJNEms5kHmA1rBUgrpD3LVUB96T/5huSin9KOlehqQRkaITDQ",
	"BS9iRdO5CQSJWF05fki/+YZgcOouyXy0IEhp3mSVL1Vov8mBZzneplfW1Z5ZfzXhRsMneusYfpODT1Sj",
	"Bm9RpaWyQBu6jY9SaP31Cu4eAggiqanWFGQFrnquvFW52GIso0i7CxVYzCGhM0d0k5SU4SG8YsEYaAhP",
	"NHwKmWHHnyBmM6rhxzUwqptIF4jv3XARwnf+EntXA2hWqOG47y4CqHMZ38qBfhO+uvV35D0AmA1+No4h",
	"B46A7dFMV4jVpK5dvUp5sVdpffNT4qhuUR1coTDg6JZ2lhYeKxfGLODRArCAR3c9Z2Ng+B3Xxl0yspOM",
	"CV/TZnl89fxn+9bf2kTb0ith5khIcdBJOrWUOv6H5qCni3G991V2tnO2tFDAtZVl9/Te+i4VMKohOz1P",
	"C9LN34jm7oFbMwq6CSvTbDlgvk5pViLWXWybDbGO0eWFUJtQMG+pDBMrW42ELH7mutWG0y3CQ1QoAgxh",
	"ULj0W1fvC3FhzBxLK+UjrBFnXjEIuQlLXpYoU7/AmoKIDQQ5ul+UN0uVnRLKRfgcfgYzSO/yrBFHu8yi",
	"cF7cNqVcsQ7Zjt3Xpex/3EvLx+bSi4kcdPy1k3tCgsKDXOLttxZ5vezmq+XGwGn26k72XQsXerezC3bK",
	"DzIk0ovFQihfbr5QAG5jSS/hbe9LJMO7RXkAJQZvdQcnY+ujEcS54VzkpC9uvr8zJnZrm3FFbZtbWakU",
	"bw6Uwt24Cxd+4b7Cnaz6wlXLO3MHTGmOKbOLvy5zDK4L10B/a85B5cbtuuMg2ZWNj9hJyG8pb+EolLlf",
	"s2pa5yCXsbGSsf8QlnuZSpY+pUoGTaujSa8smP3R/UP0UVn3OSWrFn5FuOzezN+2zJq/sn3Xp0zbYOKr",
	"MvlzPLUx+9sKsB7LikEsXcO+bsQuuOa7WsC7x5nCtbEx4thREh+8XHFj71JKQ9de7u9eotQly1/VQ2SL",
	"IqWIjjXuSDklaroSUL6UQPhNZZ1vajO5PHQ6cn0vcFwkflrFH3LO/ycG0ToGUSxOs0sx0YbbyyMSFZb/",
	"JypBUYmMqzuW/g8VnkihUyrq1ygoXmZv7UI+NBf/ezzyobniYb2EyOm8RTNiQSwlo+mWLtT2za8STPn+",
	"3ntfcKjka/BMTglFwErgqlSDawBVmzXe8ixICSuPNbRyiRN5i8AyQu1ysXXXyaRZXi9pkaAuVShtFNQX",
	"2Vu7ENTNhUQfj6Cur9paL6RzGj+MkM7oua37kFzzDyOkc7B83UKaUORrN+J8beC0xtEydLVZ6C2ldQk0",
	"j15ax/lod7bqtiWtGwI3LsC4o7X8MGHgRWv564gC57cCpPB7ooEKa3UhLdPv6prN2BR8ucLV13Kpmnaz",
	"1i7uBe1AbTcX7H5EertUFr9BX+d0eyCFnVFyS6s8bf+BVHYOlK9bZ4ehXejpbBYYgEVAtVrXbZV0CSiP",
	"X0sXhru7xfYwenpXS/iBNPWiJfzVqep0MlZXKya0Zf7my7d3yzUf8IjOLH35BpB9hblJ8c98blsGeN7T",
	"f6B+r1DPnEsWRXIacW3WwDzVQl60M3RlX3ieiDDaavmTYjePw9y84mIU4YEeSwMDGlh2NbavGh2zUlGd",
	"B97t01RnekuSqmDwzp3Bm7JYl2MbTzS4sVARay7AgzfNA9TAXNW8vsizadyRyXzfe6+aEOfKZN9gbE7c",
	"1UlcjIrFpO3TIEKmMAQti4zSYzktFqemLEkdKEQBiTA8otLYFLqZoB5DxESoDyG9xh0mXCmptM+3vC6U",
	"966cN/JLNXvHVf/edoqG68X3/RhzVn0R9DT/414zVh9IFNfgPa2N7mpzHris1xUyXn059+YD6m8EN5wZ",
	"/EAvbu0eINt42tWunUvXu69KsahgRbCRo7mRZjBMGWBZKX7HtppSYyk/Kxxe6h6eDqQyBS4vTbKy7+Pm",
	"iclcB0zZ5QlcHMRKjhRqvXBmTeWwX6Mf/1V6heXystXnP3e6vig6veQa8GWmG+qXN1rB3fTzcxelW/Hz",
	"u11Lln8kqGal2nUuvAhymFdNaWDBVu8jm6sCL0PKSrMDVWzqFoG7F4ENtIwSqjlpMB39SKL22x998anE",
	"kk++rLjT/ZrO22eFYlKFbKRhEXDhVPR8AylV05ZqNPJpHKMI3Xcv7GAbrj+YL8ZfRs/GHlk7SS0Dg/X3",
	"I7Qq2L9OemYQYGwwPJmHnWMEhpZ587SortFNFtkjjxISfgjT2oUI0wpGzFXYGPFbFNW9gMXCvzfkgkX8",
	"j5YG+xrLt9aAOPO9NqmWo3vW42l/4dfrfL+IpMYi10UIcTKIuB4T+zNgPI/k4MrfGVUDAroCx4o4x+T5",
	"MqkBiyCUwQ2qAxqdts0kKrKSyZj4uNeL7Dtjqc3x34/+ftS5+3j33wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
