// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/rosneft/backend/services/asset-service/internal/service.Store -o store_mock.go -n StoreMock -p mocks

import (
	"context"
	"io"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/rosneft/backend/pkg/blobstore"
)

// StoreMock implements mm_service.Store
type StoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGet          func(ctx context.Context, hash string) (r1 io.ReadCloser, b1 blobstore.Blob, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, hash string)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mStoreMockGet

	funcStat          func(ctx context.Context, hash string) (b1 blobstore.Blob, err error)
	funcStatOrigin    string
	inspectFuncStat   func(ctx context.Context, hash string)
	afterStatCounter  uint64
	beforeStatCounter uint64
	StatMock          mStoreMockStat
}

// NewStoreMock returns a mock for mm_service.Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetMock = mStoreMockGet{mock: m}
	m.GetMock.callArgs = []*StoreMockGetParams{}

	m.StatMock = mStoreMockStat{mock: m}
	m.StatMock.callArgs = []*StoreMockStatParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreMockGet struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockGetExpectation
	expectations       []*StoreMockGetExpectation

	callArgs []*StoreMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockGetExpectation specifies expectation struct of the Store.Get
type StoreMockGetExpectation struct {
	mock               *StoreMock
	params             *StoreMockGetParams
	paramPtrs          *StoreMockGetParamPtrs
	expectationOrigins StoreMockGetExpectationOrigins
	results            *StoreMockGetResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockGetParams contains parameters of the Store.Get
type StoreMockGetParams struct {
	ctx  context.Context
	hash string
}

// StoreMockGetParamPtrs contains pointers to parameters of the Store.Get
type StoreMockGetParamPtrs struct {
	ctx  *context.Context
	hash *string
}

// StoreMockGetResults contains results of the Store.Get
type StoreMockGetResults struct {
	r1  io.ReadCloser
	b1  blobstore.Blob
	err error
}

// StoreMockGetOrigins contains origins of expectations of the Store.Get
type StoreMockGetExpectationOrigins struct {
	origin     string
	originCtx  string
	originHash string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mStoreMockGet) Optional() *mStoreMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for Store.Get
func (mmGet *mStoreMockGet) Expect(ctx context.Context, hash string) *mStoreMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StoreMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &StoreMockGetParams{ctx, hash}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for Store.Get
func (mmGet *mStoreMockGet) ExpectCtxParam1(ctx context.Context) *mStoreMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StoreMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &StoreMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectHashParam2 sets up expected param hash for Store.Get
func (mmGet *mStoreMockGet) ExpectHashParam2(hash string) *mStoreMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StoreMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &StoreMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.hash = &hash
	mmGet.defaultExpectation.expectationOrigins.originHash = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the Store.Get
func (mmGet *mStoreMockGet) Inspect(f func(ctx context.Context, hash string)) *mStoreMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for StoreMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by Store.Get
func (mmGet *mStoreMockGet) Return(r1 io.ReadCloser, b1 blobstore.Blob, err error) *StoreMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StoreMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &StoreMockGetResults{r1, b1, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the Store.Get method
func (mmGet *mStoreMockGet) Set(f func(ctx context.Context, hash string) (r1 io.ReadCloser, b1 blobstore.Blob, err error)) *StoreMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the Store.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the Store.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the Store.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mStoreMockGet) When(ctx context.Context, hash string) *StoreMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StoreMock.Get mock is already set by Set")
	}

	expectation := &StoreMockGetExpectation{
		mock:               mmGet.mock,
		params:             &StoreMockGetParams{ctx, hash},
		expectationOrigins: StoreMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up Store.Get return parameters for the expectation previously defined by the When method
func (e *StoreMockGetExpectation) Then(r1 io.ReadCloser, b1 blobstore.Blob, err error) *StoreMock {
	e.results = &StoreMockGetResults{r1, b1, err}
	return e.mock
}

// Times sets number of times Store.Get should be invoked
func (mmGet *mStoreMockGet) Times(n uint64) *mStoreMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of StoreMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mStoreMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_service.Store
func (mmGet *StoreMock) Get(ctx context.Context, hash string) (r1 io.ReadCloser, b1 blobstore.Blob, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, hash)
	}

	mm_params := StoreMockGetParams{ctx, hash}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.b1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := StoreMockGetParams{ctx, hash}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("StoreMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.hash != nil && !minimock.Equal(*mm_want_ptrs.hash, mm_got.hash) {
				mmGet.t.Errorf("StoreMock.Get got unexpected parameter hash, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originHash, *mm_want_ptrs.hash, mm_got.hash, minimock.Diff(*mm_want_ptrs.hash, mm_got.hash))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("StoreMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the StoreMock.Get")
		}
		return (*mm_results).r1, (*mm_results).b1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, hash)
	}
	mmGet.t.Fatalf("Unexpected call to StoreMock.Get. %v %v", ctx, hash)
	return
}

// GetAfterCounter returns a count of finished StoreMock.Get invocations
func (mmGet *StoreMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of StoreMock.Get invocations
func (mmGet *StoreMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mStoreMockGet) Calls() []*StoreMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*StoreMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *StoreMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mStoreMockStat struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockStatExpectation
	expectations       []*StoreMockStatExpectation

	callArgs []*StoreMockStatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockStatExpectation specifies expectation struct of the Store.Stat
type StoreMockStatExpectation struct {
	mock               *StoreMock
	params             *StoreMockStatParams
	paramPtrs          *StoreMockStatParamPtrs
	expectationOrigins StoreMockStatExpectationOrigins
	results            *StoreMockStatResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockStatParams contains parameters of the Store.Stat
type StoreMockStatParams struct {
	ctx  context.Context
	hash string
}

// StoreMockStatParamPtrs contains pointers to parameters of the Store.Stat
type StoreMockStatParamPtrs struct {
	ctx  *context.Context
	hash *string
}

// StoreMockStatResults contains results of the Store.Stat
type StoreMockStatResults struct {
	b1  blobstore.Blob
	err error
}

// StoreMockStatOrigins contains origins of expectations of the Store.Stat
type StoreMockStatExpectationOrigins struct {
	origin     string
	originCtx  string
	originHash string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStat *mStoreMockStat) Optional() *mStoreMockStat {
	mmStat.optional = true
	return mmStat
}

// Expect sets up expected params for Store.Stat
func (mmStat *mStoreMockStat) Expect(ctx context.Context, hash string) *mStoreMockStat {
	if mmStat.mock.funcStat != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Set")
	}

	if mmStat.defaultExpectation == nil {
		mmStat.defaultExpectation = &StoreMockStatExpectation{}
	}

	if mmStat.defaultExpectation.paramPtrs != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by ExpectParams functions")
	}

	mmStat.defaultExpectation.params = &StoreMockStatParams{ctx, hash}
	mmStat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStat.expectations {
		if minimock.Equal(e.params, mmStat.defaultExpectation.params) {
			mmStat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStat.defaultExpectation.params)
		}
	}

	return mmStat
}

// ExpectCtxParam1 sets up expected param ctx for Store.Stat
func (mmStat *mStoreMockStat) ExpectCtxParam1(ctx context.Context) *mStoreMockStat {
	if mmStat.mock.funcStat != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Set")
	}

	if mmStat.defaultExpectation == nil {
		mmStat.defaultExpectation = &StoreMockStatExpectation{}
	}

	if mmStat.defaultExpectation.params != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Expect")
	}

	if mmStat.defaultExpectation.paramPtrs == nil {
		mmStat.defaultExpectation.paramPtrs = &StoreMockStatParamPtrs{}
	}
	mmStat.defaultExpectation.paramPtrs.ctx = &ctx
	mmStat.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStat
}

// ExpectHashParam2 sets up expected param hash for Store.Stat
func (mmStat *mStoreMockStat) ExpectHashParam2(hash string) *mStoreMockStat {
	if mmStat.mock.funcStat != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Set")
	}

	if mmStat.defaultExpectation == nil {
		mmStat.defaultExpectation = &StoreMockStatExpectation{}
	}

	if mmStat.defaultExpectation.params != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Expect")
	}

	if mmStat.defaultExpectation.paramPtrs == nil {
		mmStat.defaultExpectation.paramPtrs = &StoreMockStatParamPtrs{}
	}
	mmStat.defaultExpectation.paramPtrs.hash = &hash
	mmStat.defaultExpectation.expectationOrigins.originHash = minimock.CallerInfo(1)

	return mmStat
}

// Inspect accepts an inspector function that has same arguments as the Store.Stat
func (mmStat *mStoreMockStat) Inspect(f func(ctx context.Context, hash string)) *mStoreMockStat {
	if mmStat.mock.inspectFuncStat != nil {
		mmStat.mock.t.Fatalf("Inspect function is already set for StoreMock.Stat")
	}

	mmStat.mock.inspectFuncStat = f

	return mmStat
}

// Return sets up results that will be returned by Store.Stat
func (mmStat *mStoreMockStat) Return(b1 blobstore.Blob, err error) *StoreMock {
	if mmStat.mock.funcStat != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Set")
	}

	if mmStat.defaultExpectation == nil {
		mmStat.defaultExpectation = &StoreMockStatExpectation{mock: mmStat.mock}
	}
	mmStat.defaultExpectation.results = &StoreMockStatResults{b1, err}
	mmStat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStat.mock
}

// Set uses given function f to mock the Store.Stat method
func (mmStat *mStoreMockStat) Set(f func(ctx context.Context, hash string) (b1 blobstore.Blob, err error)) *StoreMock {
	if mmStat.defaultExpectation != nil {
		mmStat.mock.t.Fatalf("Default expectation is already set for the Store.Stat method")
	}

	if len(mmStat.expectations) > 0 {
		mmStat.mock.t.Fatalf("Some expectations are already set for the Store.Stat method")
	}

	mmStat.mock.funcStat = f
	mmStat.mock.funcStatOrigin = minimock.CallerInfo(1)
	return mmStat.mock
}

// When sets expectation for the Store.Stat which will trigger the result defined by the following
// Then helper
func (mmStat *mStoreMockStat) When(ctx context.Context, hash string) *StoreMockStatExpectation {
	if mmStat.mock.funcStat != nil {
		mmStat.mock.t.Fatalf("StoreMock.Stat mock is already set by Set")
	}

	expectation := &StoreMockStatExpectation{
		mock:               mmStat.mock,
		params:             &StoreMockStatParams{ctx, hash},
		expectationOrigins: StoreMockStatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStat.expectations = append(mmStat.expectations, expectation)
	return expectation
}

// Then sets up Store.Stat return parameters for the expectation previously defined by the When method
func (e *StoreMockStatExpectation) Then(b1 blobstore.Blob, err error) *StoreMock {
	e.results = &StoreMockStatResults{b1, err}
	return e.mock
}

// Times sets number of times Store.Stat should be invoked
func (mmStat *mStoreMockStat) Times(n uint64) *mStoreMockStat {
	if n == 0 {
		mmStat.mock.t.Fatalf("Times of StoreMock.Stat mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStat.expectedInvocations, n)
	mmStat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStat
}

func (mmStat *mStoreMockStat) invocationsDone() bool {
	if len(mmStat.expectations) == 0 && mmStat.defaultExpectation == nil && mmStat.mock.funcStat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStat.mock.afterStatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Stat implements mm_service.Store
func (mmStat *StoreMock) Stat(ctx context.Context, hash string) (b1 blobstore.Blob, err error) {
	mm_atomic.AddUint64(&mmStat.beforeStatCounter, 1)
	defer mm_atomic.AddUint64(&mmStat.afterStatCounter, 1)

	mmStat.t.Helper()

	if mmStat.inspectFuncStat != nil {
		mmStat.inspectFuncStat(ctx, hash)
	}

	mm_params := StoreMockStatParams{ctx, hash}

	// Record call args
	mmStat.StatMock.mutex.Lock()
	mmStat.StatMock.callArgs = append(mmStat.StatMock.callArgs, &mm_params)
	mmStat.StatMock.mutex.Unlock()

	for _, e := range mmStat.StatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmStat.StatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStat.StatMock.defaultExpectation.Counter, 1)
		mm_want := mmStat.StatMock.defaultExpectation.params
		mm_want_ptrs := mmStat.StatMock.defaultExpectation.paramPtrs

		mm_got := StoreMockStatParams{ctx, hash}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStat.t.Errorf("StoreMock.Stat got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStat.StatMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.hash != nil && !minimock.Equal(*mm_want_ptrs.hash, mm_got.hash) {
				mmStat.t.Errorf("StoreMock.Stat got unexpected parameter hash, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStat.StatMock.defaultExpectation.expectationOrigins.originHash, *mm_want_ptrs.hash, mm_got.hash, minimock.Diff(*mm_want_ptrs.hash, mm_got.hash))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStat.t.Errorf("StoreMock.Stat got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStat.StatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStat.StatMock.defaultExpectation.results
		if mm_results == nil {
			mmStat.t.Fatal("No results are set for the StoreMock.Stat")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmStat.funcStat != nil {
		return mmStat.funcStat(ctx, hash)
	}
	mmStat.t.Fatalf("Unexpected call to StoreMock.Stat. %v %v", ctx, hash)
	return
}

// StatAfterCounter returns a count of finished StoreMock.Stat invocations
func (mmStat *StoreMock) StatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStat.afterStatCounter)
}

// StatBeforeCounter returns a count of StoreMock.Stat invocations
func (mmStat *StoreMock) StatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStat.beforeStatCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Stat.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStat *mStoreMockStat) Calls() []*StoreMockStatParams {
	mmStat.mutex.RLock()

	argCopy := make([]*StoreMockStatParams, len(mmStat.callArgs))
	copy(argCopy, mmStat.callArgs)

	mmStat.mutex.RUnlock()

	return argCopy
}

// MinimockStatDone returns true if the count of the Stat invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockStatDone() bool {
	if m.StatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StatMock.invocationsDone()
}

// MinimockStatInspect logs each unmet expectation
func (m *StoreMock) MinimockStatInspect() {
	for _, e := range m.StatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Stat at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStatCounter := mm_atomic.LoadUint64(&m.afterStatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StatMock.defaultExpectation != nil && afterStatCounter < 1 {
		if m.StatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Stat at\n%s", m.StatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Stat at\n%s with params: %#v", m.StatMock.defaultExpectation.expectationOrigins.origin, *m.StatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStat != nil && afterStatCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Stat at\n%s", m.funcStatOrigin)
	}

	if !m.StatMock.invocationsDone() && afterStatCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Stat at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StatMock.expectedInvocations), m.StatMock.expectedInvocationsOrigin, afterStatCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetInspect()

			m.MinimockStatInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetDone() &&
		m.MinimockStatDone()
}
